const { readFileSync, existsSync } = require('fs');
const { join } = require('path');

function readSource(relativePath) {
    const full = join(process.cwd(), relativePath);
    if (!existsSync(full)) return '';
    return readFileSync(full, 'utf8');
}

describe('admin library route regressions.test', () => {
    it('bare shell: no luxury/surfaces paint sheets; flat bare CSS', () => {
        const html = readSource('admin-library.html');
        expect(html).toContain('lux-shell.css');
        expect(html).toContain('lux-page-bare-lite.css');
        expect(html).not.toMatch(/lux-page-bare\.css(?!-lite)/);
        expect(html).toContain('lux-page-bare-lite.css');
        expect(html).toMatch(/class="[^"]*lux-page-bare/);
        expect(html).not.toMatch(/href=["'][^"']*index-luxury\.css/);
        expect(html).not.toMatch(/href=["'][^"']*lux-surfaces\.css/);
        expect(existsSync(join(process.cwd(), 'assets/css', 'admin-library-route.css'))).toBe(false);
        const bare = readSource('assets/css/lux-page-bare-lite.css');
        expect(bare).toContain('body.lux-page-bare');
        expect(bare).not.toMatch(/body\.lux-page-bare\s*\{[^}]*backdrop-filter:\s*none/);
        expect(bare).toContain('.lux-page-shell[data-lux-layout-only="1"]');
        const shell = readSource('assets/css/lux-shell.css');
        expect(shell).toContain('body.lux-page-bare .lux-page-shell');
        expect(shell).not.toContain('body.lux-page-bare .lux-page-shell :is(.page-hero, .lux-panel, .lux-alert)');
        expect(html).toContain('data-lux-layout-only="1"');
        expect(html).toMatch(/admin-library-shell[\s\S]*data-lux-glass-root="1"/);
        expect(html).not.toMatch(/alib-workspace[\s\S]*data-lux-glass-root="1"/);
    });

    it('loads shared panel SSOT stack with library layout CSS', () => {
        const html = readSource('admin-library.html');
        expect(html).toContain('lux-modals.css');
        expect(html).toContain('libshell2');
        expect(html).toContain('admin-library-catalog-card lux-soft-chrome home-hover-chip');
        expect(html).toContain('alib-panel alib-panel--entry lux-soft-chrome home-hover-chip');
        expect(html).toContain('admin-library-metric-card home-hover-chip');
        expect(html).toContain('admin-library-schema-add-form home-hover-chip');
        expect(html).toContain('admin-library-schema-droplist-editor-body home-hover-chip');
        expect(html).toContain('admin-library-sections-panel lux-soft-chrome home-hover-chip');
        expect(html).toContain('admin-library-sections-modal');
        expect(html).toContain('lux-glass-dialog-head admin-library-modal-head');
        expect(html).toContain('lux-glass-dialog-body admin-library-modal-body');
        expect(html).toContain('admin-library-modal-foot');
        expect(html).toContain('lux-ghost-btn lux-glass-dialog-close-btn');
        expect(html).toContain('admin-library-sections-add-row lux-soft-chrome home-hover-chip');
        expect(html).toContain('lux-section-kicker admin-library-sections-panel-kicker');
        expect(html).toContain('lux-primary-btn home-hover-chip');
        expect(html).toContain('lux-secondary-btn home-hover-chip close-btn');
        expect(html).not.toContain('admin-library-route.css');
        expect(html).toContain('lux-soft-chrome');
        expect(html).toContain('admin-library-shell');
        expect(html).toContain('lux-secondary-btn admin-library-schema-editor-btn');
        const bare = readSource('assets/css/lux-page-bare-lite.css');
        expect(bare).toContain('#page-library .admin-library-shell');
        expect(bare).toContain('#page-library .alib-workspace');
        expect(bare).toContain('#page-library .admin-library-catalog-card');
        expect(bare).toContain('.admin-library-droplist-header-cell');
        const libraryBlock = bare.slice(bare.indexOf('/* ── Library workspace'));
        expect(libraryBlock).not.toContain('--alib-fade-');
        expect(libraryBlock).not.toContain('--lib-fade-');
        const controls = readSource('assets/css/lux-controls.css');
        expect(controls).toContain('.lux-destructive-btn');
        const adminLibraryJs = readSource('assets/js/pages/admin-library.js');
        expect(adminLibraryJs).toContain('renderAdminLibrary();');
        expect(adminLibraryJs).toContain('loadDeferredAdminLibraryScripts');
        expect(adminLibraryJs).toMatch(/ensureAdminLibraryState\(\);\s*renderAdminLibrary\(\);/);
        expect(adminLibraryJs).toContain("row.className = 'admin-library-schema-field-row home-hover-chip'");
        expect(adminLibraryJs).toContain("row.className = 'admin-library-section-row lux-soft-chrome home-hover-chip'");
        expect(adminLibraryJs).toContain('lux-card-copy admin-library-section-row-title');
        expect(adminLibraryJs).toContain('lux-empty-state admin-library-sections-empty');
        expect(adminLibraryJs).toMatch(/setAdminLibrarySectionsModalOpen[\s\S]*?classList\.toggle\('is-open'/);
        expect(html).toContain('library-sections-overlay');
        expect(html).toContain('lux-glass-dialog-overlay');
        const primitives = readSource('assets/css/lux-layout-primitives.css');
        expect(adminLibraryJs).toContain('lux-secondary-btn lux-destructive-btn home-hover-chip admin-library-section-remove-btn');
        expect(adminLibraryJs).toContain('lux-destructive-btn home-hover-chip');
        expect(adminLibraryJs).toContain('lux-secondary-btn home-hover-chip');
        expect(primitives).toContain('.admin-library-modal-title.lux-glass-dialog-title');
        expect(primitives).toContain('.admin-library-section-row-title.lux-card-copy');
        expect(adminLibraryJs).toContain('lux-secondary-btn admin-library-schema-btn-remove home-hover-chip');
        const fouc = readSource('assets/css/lux-fouc-ht.css');
        expect(fouc).toContain('.admin-library-modal) :is(');
        expect(fouc).toContain('.admin-library-schema-field-row.home-hover-chip');
        expect(fouc).toContain('.alib-panel.lux-soft-chrome.home-hover-chip');
        expect(fouc).toContain('.admin-library-metric-card.home-hover-chip');
        expect(fouc).toContain('.admin-library-tab-btn.home-hover-chip');
        expect(fouc).toContain('.admin-library-empty-state.home-hover-chip');
        expect(fouc).toContain('.admin-library-sections-add-row.lux-soft-chrome');
        expect(fouc).toContain('.admin-library-sections-empty.lux-empty-state');
        expect(html).not.toContain('luxury-index-runtime.js');
        expect(html).not.toContain('luxury-home-model.js');
        expect(html).not.toContain('features/ui.js');
        expect(html).not.toContain('lux-scroll-rail.js');
        const modals = readSource('assets/css/lux-modals.css');
        expect(modals).toContain('.admin-library-schema-section');
        expect(modals).toContain('.admin-library-sections-modal.lux-glass-dialog-card');
        expect(modals).toContain('.admin-library-sections-list');
        expect(modals).toContain('.admin-library-schema-droplist-editor-body');
        expect(modals).toMatch(/\.lux-glass-dialog-overlay[\s\S]*?\.is-open\s*>\s*\*[\s\S]*?opacity:\s*1/);
        expect(modals).not.toMatch(/\.admin-library-schema-field-row\s*\{[^}]*background:\s*var\(--lux-panel-modal-section/);
    });
});
