import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('admin-library route regressions', () => {
    it('keeps the shell free of dead imports and inline handlers', () => {
        const html = readSource('admin-library.html');
        const css = readSource('assets/css/admin-library-route.css');
        const sharedSurfaceCss = readSource('assets/css/lux-surfaces.css');
        const sharedControlCss = readSource('assets/css/lux-controls.css');

        expect(html).not.toContain('assets/js/shared/messenger.js');
        expect(html).not.toContain('assets/js/pages/gradebook.js');
        expect(html).not.toContain('assets/js/pages/lms.js');
        expect(html).not.toContain('assets/js/pages/registration.js');
        expect(html).not.toContain('assets/js/pages/planner.js');
        expect(html).not.toContain('assets/js/pages/directories.js');
        expect(html).not.toContain('assets/js/pages/student-registration.js');
        expect(html).not.toContain('assets/js/pages/admin-registration.js');
        expect(html).not.toContain('onclick=');
        expect(html).not.toContain('oninput=');
        expect(html).not.toContain('onchange=');
        expect(html).not.toContain('setInterval(');
        expect(html).not.toContain('Ãƒ');
        expect(html).toContain('<nav id="prof-nav" aria-label="Professor navigation stub"');
        expect(html).toContain('<nav id="top-nav" aria-label="Top navigation stub"');
        expect(html).toContain('<nav id="admin-nav" aria-label="Admin navigation stub"');
        expect(html).not.toContain('assets/css/library-route.css');
        expect(html).not.toContain('assets/css/index-home-dashboard.css');
        expect(html).toContain('assets/css/admin-library-route.css?v=20260602-alibrebuild15');
        expect(html).toContain('assets/js/shared/utilities.js?v=20260602-alibfade2');
        expect(html).toContain('assets/js/features/index-luxury.js?v=20260602-alibroute1');
        expect(html).toContain('id="admin-library-critical-layout"');
        expect(html).toMatch(/admin-library-critical-layout[\s\S]*body\.lux-entry-admin-library #page-library \.alib-workspace/);
        expect(html).toMatch(/admin-library-critical-layout[\s\S]*\.alib-workspace[\s\S]*display:\s*grid !important/);
        expect(html).toMatch(/admin-library-critical-layout[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
        expect(html).not.toMatch(/admin-library-critical-layout[\s\S]*library-page-hero/);
        expect(html).toContain('ensureAdminLibraryRouteVisualState');
        expect(html).toContain('window.ensureAdminLibraryRouteVisualState = ensureAdminLibraryRouteVisualState');
        expect(html).toContain("body.classList.remove('lux-route-library')");
        expect(html).toContain('class="lux-home-grid is-admin admin-library-page"');
        expect(html).toContain('class="alib-workspace"');
        expect(html).not.toContain('library-filter-shell');
        expect(html).not.toContain('ADMIN_LIBRARY_PAGE_SHELL_HTML');
        expect(html).not.toContain('MutationObserver');
        expect(html).toContain('<section class="lux-hero admin-library-hero"');
        expect(html).not.toContain('library-page-hero');
        expect(html).toContain('class="lux-hero-stage admin-library-hero-stage"');
        expect(html).toContain('class="lux-hero-main admin-library-hero-main"');
        expect(html).toContain('class="lux-hero-side admin-library-hero-summary"');
        expect(html).toContain('class="lux-hero-side-head admin-library-hero-summary-card"');
        expect(html).toContain('class="admin-library-hero-summary-copy"');
        expect(html).toContain('class="lux-hero-signal-list admin-library-hero-signal-grid"');
        expect(html).toContain('class="lux-hero-signal admin-library-hero-signal-card admin-library-hero-signal-card--visible"');
        expect(html).toContain('id="admin-library-hero-total"');
        expect(html).toContain('id="admin-library-hero-visible"');
        expect(html).toContain('id="admin-library-hero-parameters"');
        expect(html).toContain('class="page-hero-badge wave2-chip wave2-chip--hero"');
        expect(html).toContain('class="lux-tab-fill lux-select-card lux-tab-btn active"');
        expect(html).not.toContain('library-tab-fill');
        expect(html).toContain('<button class="mob-sheet-btn" type="button" id="mob-act-admin"><span class="mob-sheet-icon"');
        expect(html).not.toContain('<button class="mob-sheet-btn" id="mob-act-admin"><div class="mob-sheet-icon"');
        expect(html).toContain('data-admin-library-nav-home="true"');
        expect(html).toContain('data-admin-library-open-params="true"');
        expect(html).toContain('data-admin-library-add-book="true"');
        expect(html).toContain('class="lux-primary-btn wave2-action-btn wave2-action-btn--primary"');
        expect(html).toContain('class="lux-secondary-btn wave2-action-btn wave2-action-btn--secondary"');
        expect(html).toContain('class="alib-form-grid"');
        expect(html).toContain('class="alib-filter-stack"');
        expect(html).toContain('id="book-title" name="book_title" type="text" class="lux-control"');
        expect(html).not.toContain('library-field-input');
        expect(html).toContain('alib-field-wide');
        expect(html).toContain('data-admin-library-search="query"');
        expect(html).toContain('class="admin-library-metric-row admin-library-metric-row--compact"');
        expect(html).not.toContain('admin-library-metric-row lux-strip-grid');
        expect(html).toContain('class="admin-library-metric-card wave2-summary-card"');
        expect(html).not.toContain('admin-library-metric-card wave2-summary-card lux-strip-card');
        expect(html).toContain('class="admin-library-metric-label wave2-summary-label"');
        expect(html).toContain('class="wave2-summary-value"');
        expect(html).toContain("chip.className = 'admin-library-chip wave2-chip wave2-chip--pill';");
        expect(html).toContain('data-admin-library-picker-field="topic"');
        expect(html).toContain('class="alib-panel alib-panel--entry"');
        expect(html).toContain('class="alib-panel alib-panel--filters"');
        expect(html).not.toMatch(/alib-panel--(?:entry|filters)[^"]*lux-strip-card/);
        expect(html).toContain('class="lux-picker-field"');
        expect(html).not.toMatch(/class="[^"]*library-picker-field/);
        expect(html).toContain('class="lux-control"');
        expect(html).toContain('class="lux-picker-btn"');
        expect(html).not.toMatch(/class="[^"]*library-picker-btn/);
        expect(html).toContain('class="lux-picker-panel lux-picker-panel-scroll"');
        expect(html).toContain('class="lux-filter-hidden-select"');
        expect(html).toContain('class="lux-strip-card admin-library-catalog-card"');
        expect(html).not.toMatch(/class="(?:library-catalog-card|library-page-hero|content-box)\b/);
        expect(html).toContain('data-admin-library-modal-overlay="true"');
        expect(html).toContain('class="modal-content lux-panel admin-library-modal"');
        expect(html).toContain('class="modal-header admin-library-modal-head"');
        expect(html).toContain('class="modal-body admin-library-modal-body"');
        expect(html).toContain('class="modal-footer admin-library-modal-foot"');
        expect(html).toContain('class="lux-control admin-library-modal-input"');
        expect(html).toContain("event.target.closest('[data-admin-library-remove-param]')");
        expect(html).toContain("button.dataset.adminLibraryRemoveParam = 'true'");
        expect(html).toContain('renderAdminLibraryChipGroup');
        expect(html).toContain('createAdminLibraryCatalogRow');
        expect(html).toContain('renderAdminLibraryEmptyStateRow');
        expect(html).toContain("row.className = 'admin-library-catalog-row';");
        expect(html).toContain("cell.className = 'admin-library-catalog-cell';");
        expect(html).toContain("cell.className = 'admin-library-catalog-cell admin-library-pdf-cell';");
        expect(html).toContain("cell.className = 'admin-library-catalog-cell admin-library-action-cell';");
        expect(html).toContain("button.className = 'admin-library-remove-btn wave2-action-btn wave2-action-btn--danger';");
        expect(html).toContain("row.className = 'admin-library-empty-row';");
        expect(html).toContain("cell.className = 'admin-library-empty-cell admin-library-catalog-cell';");
        expect(html).not.toMatch(/className = 'library-empty-row'/);
        expect(html).toContain('class="admin-library-empty-state"');
        expect(html).toContain('class="admin-library-empty-state-title"');
        expect(html).toContain('class="admin-library-empty-state-copy"');
        expect(html).toContain("const heroTotal = document.getElementById('admin-library-hero-total');");
        expect(html).toContain("const heroVisible = document.getElementById('admin-library-hero-visible');");
        expect(html).toContain("const heroParameters = document.getElementById('admin-library-hero-parameters');");
        expect(html).toContain('createAdminLibraryPickerOption');
        expect(html).toContain('createAdminLibrarySelectOption');
        expect(html).toContain('setAdminLibraryParamModalOpen');
        expect(html).toContain("overlay.classList.toggle('active', Boolean(isOpen));");
        expect(html).toContain("document.body.classList.toggle('admin-library-modal-open', Boolean(isOpen));");
        expect(html).not.toContain("overlay.style.display = 'flex'");
        expect(html).not.toContain("overlay.style.display = 'none'");
        expect(html).not.toContain("document.body.style.overflow = 'hidden'");
        expect(html).not.toContain("document.body.style.overflow = ''");
        expect(html).not.toContain("cell.style.textAlign = 'center'");
        expect(html).not.toContain("cell.style.color = 'var(--lux-text-muted)'");
        expect(html).not.toContain("cell.style.padding = '28px'");
        expect(html).toContain('window.__KIU_STANDALONE_MOBILE_SHELL_CONFIG = {');
        expect(html).toContain("activeTarget: 'library'");
        expect(html).toContain('assets/js/pages/standalone-mobile-shell.js?v=20260520-admin-library-mobile1');
        expect(html).not.toContain('(function initMobileExperience(){');
        expect(html).toContain('assets/js/features/navigation.js?v=20260429-shellinit1');
        expect(html).toContain('assets/js/features/ui.js?v=20260429-peopleisolation1');
        expect(html).not.toContain('lux-route-library lux-route-admin-library');
        expect(css).not.toContain('.adlib-table');
        expect(css).not.toContain('.adlib-modal-overlay');
        expect(css).not.toContain('.adlib-modal');
        expect(css).not.toContain('.adlib-delete-btn');
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-admin-library .admin-library-modal-overlay {");
        expect(css).toContain('backdrop-filter: var(--alib-fade-blur);');
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-admin-library .admin-library-modal {");
        expect(css).toContain('body.lux-route-admin-library.admin-library-modal-open {');
        expect(css).toContain('body.lux-route-admin-library .admin-library-empty-cell {');
        expect(css).not.toContain('lux-route-library');
        expect(css).toContain('.admin-library-modal-head');
        expect(css).toContain('.admin-library-modal-body');
        expect(css).toContain('.admin-library-modal-foot');
        expect(css).toContain('.admin-library-modal-input');
        expect(css).toContain('.admin-library-catalog-cell {');
        expect(css).toContain('.admin-library-pdf-cell {');
        expect(css).toContain('.admin-library-action-cell');
        expect(css).toContain('.wave2-action-btn--danger {');
        expect(css).toContain('.admin-library-empty-row {');
        expect(css).toContain('.admin-library-empty-state {');
        expect(css).toContain('.admin-library-empty-state-title {');
        expect(css).toContain('.admin-library-empty-state-copy {');
        expect(css).toContain('.admin-library-hero-stage');
        expect(css).toContain('.admin-library-scroll-wrap');
        expect(sharedSurfaceCss).toContain('.wave2-summary-card {');
        expect(sharedSurfaceCss).toContain('.wave2-summary-label {');
        expect(sharedSurfaceCss).toContain('.wave2-summary-value {');
        expect(sharedSurfaceCss).toContain('.wave2-chip--pill {');
        expect(sharedControlCss).toContain('.wave2-action-btn {');
        expect(css).not.toContain('.wave2-action-btn {');
        expect(css).not.toContain('.wave2-chip--pill {');
        expect(css).not.toContain('--alib-index-panel-bg');
        expect(css).not.toContain('--alib-index-surface-blur');
        expect(css).not.toContain('library-field-input');
        expect(css).not.toContain('var(--lib-fade-surface)');
    });

    it('inherits index home surfaces instead of library-route overrides', () => {
        const css = readSource('assets/css/admin-library-route.css');
        const luxuryCss = readSource('assets/css/index-luxury.css');
        const themePrimer = readSource('assets/js/theme-primer.js');
        const utilitiesSource = readSource('assets/js/shared/utilities.js');
        const luxuryJs = readSource('assets/js/features/index-luxury.js');

        expect(css).toContain('Layout and table chrome');
        expect(css).toContain('--alib-fade-blur');
        expect(css).toContain('var(--lux-transparency-blur');
        expect(css).not.toContain('Light workspace redesign');
        expect(css).not.toContain('Kill library-route lib-fade blur');
        expect(css).toContain('#page-library .alib-panel');
        expect(css).toMatch(/#page-library \.alib-panel[\s\S]*padding:\s*24px/);
        expect(css).toMatch(/#page-library \.alib-panel-title[\s\S]{0,220}font-size:\s*18px/);
        expect(css).toMatch(/#page-library \.alib-panel-title[\s\S]{0,220}text-transform:\s*none/);
        expect(luxuryCss).toContain('body.lux-nonhome-page:not(.lux-route-admin-library)');
        expect(luxuryCss).toContain(':not(.lux-route-admin-library) .lux-hero,');
        expect(luxuryCss).toContain(':not(.lux-route-admin-library):not(.lux-route-staff) .lux-strip-card');
        expect(css).toContain('background: var(--alib-fade-surface) !important');
        expect(css).toContain('backdrop-filter: var(--alib-fade-blur) !important');
        expect(css).toContain('background-image: none !important');
        expect(themePrimer).toContain('shouldSkipFlatSurfaceOverrides');
        expect(themePrimer).toContain("classList.contains('lux-route-admin-library')");
        expect(utilitiesSource).toContain('admin-library-metric-card');
        expect(utilitiesSource).toContain('admin-library-catalog-row');
        expect(utilitiesSource).toContain('alib-panel');
        expect(utilitiesSource).toContain('shouldKeepAdminLibraryFadeCssBackground');
        expect(utilitiesSource).not.toContain('isAdminLibraryPageSurface');
        expect(luxuryJs).toMatch(/if \(entry === 'admin-library'\) \{[\s\S]*tokens\.add\('admin-library'\)/);
        expect(luxuryJs).not.toMatch(/if \(entry === 'admin-library'\) \{[\s\S]*tokens\.add\('library'\)/);
        expect(css).toContain('.alib-panel-head');
        expect(css).toMatch(/\.alib-panel-head[\s\S]*background:\s*transparent/);
        expect(css).not.toMatch(/blur\(24px\)/);
        expect(css).not.toContain('color: #201912');
    });

    it('keeps equal split workspace with compact catalog metrics', () => {
        const css = readSource('assets/css/admin-library-route.css');
        const html = readSource('admin-library.html');
        const libraryJs = readSource('assets/js/pages/library.js');

        expect(css).toContain('#page-library .alib-workspace');
        expect(css).toContain('body.lux-entry-admin-library #page-library .alib-workspace');
        expect(css).toMatch(/\.alib-workspace[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
        expect(css).toMatch(/\.alib-workspace[\s\S]*gap:\s*24px/);
        expect(css).toMatch(/\.alib-workspace[\s\S]*max-width:\s*100%/);
        expect(css).not.toMatch(/#page-library \.alib-panel[\s\S]*min-height:\s*320px/);
        expect(css).not.toContain('max-width: min(1120px, 100%)');
        expect(css).toContain('#page-library .lux-home-grid.is-admin');
        expect(css).not.toContain('--alib-index-panel-bg');
        expect(css).toContain('.alib-panel-title');
        expect(css).toContain('@media (max-width: 520px)');
        expect(css).toMatch(/\.alib-form-grid[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\)/);
        expect(css).toMatch(/\.alib-filter-stack[\s\S]*grid-template-columns:\s*1fr/);
        expect(css).toContain('.admin-library-metric-row--compact');
        expect(css).toMatch(/\.admin-library-metric-card[\s\S]*display:\s*flex/);
        expect(css).not.toMatch(/\.admin-library-metric-card[\s\S]*min-height:\s*94px/);
        expect(html).toContain('alib-workspace');
        expect(html).toContain('alib-panel--entry');
        expect(html).toContain('alib-panel--filters');
        expect(html).not.toContain('lux-strip-grid--adaptive');
        expect(libraryJs).toMatch(/lux-route-admin-library[\s\S]*return root/);
        expect(libraryJs).toContain('hasAdminLibraryWorkspace');
        expect(libraryJs).toMatch(/hasAdminLibraryWorkspace\(root\)[\s\S]*return root/);
    });
});
