import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

function readRegisteredChunk(relativePath, registrationName) {
    const source = readSource(relativePath);
    const pattern = new RegExp(`${registrationName}\\('([^']+)'\\)`);
    const match = source.match(pattern);

    if (!match) {
        throw new Error(`Registration payload ${registrationName} was not found in ${relativePath}.`);
    }

    return Buffer.from(match[1], 'base64').toString('utf8');
}

describe('admin-tools route regressions', () => {
    it('keeps admin-tools route styling scoped and efficient-tier safe', () => {
        const html = readSource('admin-tools.html');
        const css = readSource('assets/css/admin-tools-luxury.css');
        const utilities = readSource('assets/js/shared/utilities.js');
        const luxury = readSource('assets/js/features/index-luxury.js');
        const adminToolsBundle = readRegisteredChunk('assets/js/features/index-admin-tools.js', '__kiuRegisterLuxuryAdminToolsChunk');
        const adminToolsBundleSource = readSource('assets/js/features/index-admin-tools.bundle-source.js');
        const registration = readSource('assets/js/pages/registration.js');
        const adminRegistration = readSource('assets/js/pages/admin-registration.js');
        const adminRegistrationTrack = readSource('assets/js/pages/admin-registration-track.js');
        const initialState = readSource('assets/js/data/initial-state.js');
        const planner = readSource('assets/js/pages/planner.js');

        expect(html).toContain('assets/css/admin-tools-luxury.css?v=20260606-regmanage3');
        expect(html).toContain('assets/js/shared/utilities.js?v=20260606-coursemodal1');
        expect(html).toContain('assets/js/pages/admin-registration-track.js?v=20260606-regmanage3');
        expect(html).toContain('assets/js/pages/admin-registration.js?v=20260606-regmanage3');
        expect(html).toContain('assets/css/lux-tokens.css?v=20260606-luxscrollbar1');
        expect(html).toContain('assets/css/lux-layout-primitives.css?v=20260606-luxscrollbar1');
        expect(html).toContain('assets/js/shared/lux-scroll-rail.js?v=20260606-scrollrail1');
        expect(html).toContain('assets/js/pages/curriculum-semester-picker.js?v=20260606-semesterpro1');
        expect(html).toContain('assets/js/pages/curriculum-library-scroll.js?v=20260606-scrollrail1');
        expect(html).toContain('assets/js/pages/registration.js?v=20260606-luxscrollbar1');
        expect(html).toContain('assets/js/features/index-admin-tools.js?v=20260606-semesterpro1');
        expect(html).toContain('assets/js/pages/admin-tools-index-alignment.js?v=20260606-panelalign1');
        expect(html).not.toContain('assets/js/pages/lms.js');
        expect(html).not.toContain('assets/js/pages/student-registration.js');
        expect(html).not.toContain('Ãƒ');
        expect(html).not.toContain('onclick=');
        expect(html).not.toContain('setInterval(');
        expect(html).not.toContain('<style>');
        expect(html).not.toContain('style="display:none;"');
        expect(html).not.toContain('style="display: none;"');
        expect(html).toContain('window.__KIU_STANDALONE_MOBILE_SHELL_CONFIG = {');
        expect(html).toContain("activeTarget: 'admin-tools'");
        expect(html).toContain('assets/js/pages/standalone-mobile-shell.js?v=20260520-admin-tools-mobile1');
        expect(html).not.toContain('(function initMobileExperience(){');
        expect(css).not.toContain('Ã¢');
        expect(css).not.toContain('transition: all');
        expect(css).not.toContain('body.lux-unified-shell .lux-primary-btn');
        expect(css).not.toContain('body.lux-unified-shell .lux-panel');
        expect(css).toContain('body.lux-unified-shell.lux-route-admin-tools .lux-primary-btn');
        expect(css).toContain('body.lux-unified-shell.lux-route-admin-tools .lux-panel');
        expect(css).toContain('--atools-fade-surface');
        expect(css).toContain('#lux-admin-tools-shell .lux-strip-card');
        expect(css).toContain('--atools-fade-control');
        expect(css).toContain('var(--atools-fade-blur) !important');
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-admin-tools .modal-overlay {");
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-admin-tools #lux-admin-tools-shell .lux-admin-tools-page .lux-subcard,");
        expect(luxury).toContain('function ensureLuxuryAdminToolsBundle() {');
        expect(luxury).toContain('function scheduleLuxuryAdminToolsChunkRetry()');
        expect(luxury).toContain('window.ensureLuxuryAdminToolsBundle = ensureLuxuryAdminToolsBundle');
        expect(luxury).not.toContain('data-admin-tools-add-module="1"');
        expect(luxury).not.toContain('onclick="addCurriculumLibraryModule()"');
        expect(luxury).not.toContain('oninput="debouncedFilterSubjects(this.value)"');
        expect(luxury).not.toContain('onchange="toggleConditionBox()"');
        expect(luxury).not.toContain('onclick="addSubjectToSystem()"');
        expect(luxury).not.toContain('onclick="switchAdminRegTab(');
        expect(adminToolsBundle).toContain('data-admin-tools-add-module="1"');
        expect(adminToolsBundle).toContain('data-admin-tools-prereq-search="1"');
        expect(adminToolsBundle).toContain('data-admin-tools-toggle-condition="1"');
        expect(adminToolsBundle).toContain('data-admin-tools-save-subject="1"');
        expect(adminToolsBundle).toContain('data-admin-reg-tab-bar');
        expect(adminToolsBundle).not.toContain('data-admin-tools-reg-tab="prog"');
        expect(adminToolsBundle).toContain('renderAdminRegTabBar(adminRegActiveTab || \'prog\')');
        expect(adminToolsBundle).not.toContain('id="new-subject-semester"');
        expect(adminToolsBundle).toContain('id="new-subject-semesters"');
        expect(adminToolsBundle).toContain('id="new-subject-semester-lux-btn"');
        expect(adminToolsBundle).toContain('lux-semester-scroll-panel');
        expect(adminToolsBundle).toContain('lux-semester-mode-segment');
        expect(adminToolsBundle).toContain('new-subject-semester-mode-single');
        expect(adminToolsBundle).toContain('new-subject-semester-mode-multiple');
        expect(adminToolsBundle).toContain('new-subject-semester-mode-hint');
        expect(adminToolsBundle).toContain('Select semester');
        expect(adminToolsBundle).toContain('initCurriculumSemesterPicker');
        expect(adminToolsBundle).toContain('initCurriculumLibraryRowScroll');
        expect(adminToolsBundle).toContain('data-builder-section="basics"');
        expect(adminToolsBundle).toContain('data-builder-section="availability"');
        expect(adminToolsBundle).toContain('lux-admin-tools-builder-body');
        expect(registration).toContain('data-curriculum-subject-scroll');
        expect(registration).toContain('data-lux-scroll-rail');
        expect(registration).toContain('lux-scroll-rail__dock');
        expect(registration).toContain('lux-scroll-rail__spine');
        expect(registration).toContain('lux-scrollbar curriculum-library-list');
        expect(registration).toContain('lux-scrollbar lux-scroll-rail__viewport');
        expect(adminToolsBundle).toContain('lux-scrollbar lux-admin-tools-builder-body');
        expect(registration).toContain('curriculum-library-scroll-btn');
        expect(registration).toContain('curriculum-library-scroll-controls');
        expect(registration).toContain('formatCurriculumSubjectSubtitle');
        expect(registration).toContain('semesters,');
        expect(registration).toContain('normalizeSubjectSemesters');
        expect(registration).toContain('lux-curriculum-subject-card');
        expect(registration).not.toContain('lux-program-ects');
        expect(css).toContain('.lux-curriculum-subject-card');
        expect(css).toContain('.curriculum-library-row-scroll');
        expect(css).toContain('.lux-scroll-rail__dock');
        const layoutPrimitives = readSource('assets/css/lux-layout-primitives.css');
        const luxTokens = readSource('assets/css/lux-tokens.css');
        const scrollRailJs = readSource('assets/js/shared/lux-scroll-rail.js');
        expect(layoutPrimitives).toContain('.lux-scroll-rail__btn');
        expect(layoutPrimitives).toContain('.lux-scroll-rail__dock');
        expect(luxTokens).toContain('--lux-scroll-rail-dock-bg');
        expect(scrollRailJs).toContain('initLuxScrollRail');
        expect(css).not.toContain('grid-template-columns: 36px minmax(0, 1fr) 36px');
        expect(css).toContain('.lux-curriculum-subject-card__chips .lux-status-pill');
        expect(css).toContain('backdrop-filter: none');
        expect(css).toContain('var(--atools-fade-surface-soft)');
        expect(css).toContain('var(--atools-fade-blur)');
        expect(css).toContain('width: 100%');
        expect(css).toContain('--atools-curriculum-card-head-bg');
        expect(css).toContain('--atools-curriculum-card-footer-detail');
        expect(css).toContain('--atools-curriculum-card-base: #122433');
        expect(css).toContain('--atools-curriculum-card-head-bg: transparent');
        expect(css).toContain('.lux-curriculum-subject-card__head.lux-modern-surface');
        const indexLuxuryCss = readSource('assets/css/index-luxury.css');
        expect(luxury).toContain('curriculum-library-scroll-btn');
        expect(luxury).toContain('lux-scroll-rail__btn');
        expect(luxury).toContain('lux-scroll-rail__dock');
        expect(luxury).toContain('curriculum-library-panel--detail');
        expect(luxury).toContain('lux-curriculum-subject-card__chips');
        expect(utilities).toContain('lux-curriculum-subject-card');
        expect(utilities).toContain('lux-curriculum-subject-card__head');
        expect(utilities).toContain('lux-curriculum-subject-card__footer');
        expect(utilities).toContain('!el.classList.contains(\'lux-curriculum-subject-card\')');
        expect(utilities).toContain('curriculum-library-row-list');
        expect(indexLuxuryCss).toContain('body:not(.lux-route-admin-tools) #curriculum-library-modules-root .lux-surface');
        expect(indexLuxuryCss).toContain('body.lux-route-admin-tools #lux-admin-tools-shell .lux-curriculum-subject-card.lux-modern-surface');
        expect(indexLuxuryCss).toContain('.lux-admin-tools-index-panel .lux-admin-tools-index-panel-shell.lux-modern-surface');
        expect(css).toContain('.lux-admin-tools-index-panel :is(');
        expect(css).toContain('.lux-admin-tools-index-panel-shell');
        expect(utilities).toContain('lux-admin-tools-index-panel-shell');
        const alignment = readSource('assets/js/pages/admin-tools-index-alignment.js');
        expect(alignment).toContain("panel.setAttribute('data-lux-index-glass-root', '1')");
        expect(alignment).not.toContain("panel.classList.add('lux-admin-tools-index-panel');\n            clearPresentationalInlineStyle(panel);");
        expect(css).toContain('.lux-admin-tools-builder-section');
        expect(css).toContain('.registration-antireq-option');
        expect(css).toContain('.lux-semester-scroll-panel');
        expect(css).toContain('.lux-semester-chip-tray');
        expect(adminToolsBundle).toContain('bindAdminRegistrationCmsDelegates()');
        expect(adminToolsBundle).toContain('refreshRegistrationWorkspace');
        expect(adminToolsBundle).toContain('function canRenderLuxuryAdminToolsWorkspace()');
        expect(adminToolsBundle).toContain('getNavigationAuthRole() === \'admin\'');
        expect(adminToolsBundle).not.toContain('getEffectiveRole() !== \'admin\' && !shell.dataset.rendered');
        expect(html).toContain('userHasPortalPrivilegeForAuthUser(\'access_admin_tools\')');
        expect(registration).not.toContain('onclick="addCurriculumLibraryModule()"');
        expect(registration).not.toContain('onchange="selectCurriculumLibraryModule(');
        expect(registration).not.toContain('onclick="editCurriculumLibraryModule(');
        expect(registration).not.toContain('onclick="deleteCurriculumLibraryModule(');
        expect(registration).not.toContain('onclick="focusCurriculumSubjectBuilder()"');
        expect(registration).toContain('data-curriculum-add-module="1"');
        expect(registration).toContain('data-curriculum-module-select=');
        expect(registration).toContain('data-curriculum-edit-module=');
        expect(registration).toContain('data-curriculum-delete-module=');
        expect(registration).toContain('data-curriculum-focus-builder="1"');
        expect(registration).toContain('data-curriculum-delete-subject=');
        expect(adminRegistration).toContain('function bindAdminRegistrationCmsDelegates()');
        expect(adminRegistration).toContain('bindAdminRegistrationCmsDelegates();');
        expect(adminRegistration).not.toMatch(/onclick=|oninput=|onchange=|onmouseover=|onmouseout=/);
        expect(adminRegistration).not.toContain('function renderAdminRegStructures(');
        expect(adminRegistration).not.toContain('function renderAdminRegModulesAdvanced(');
        expect(adminRegistration).not.toContain('function updateConcTable(');
        expect(adminRegistration).not.toContain('onclick="addNewAdminRegModule(\'prog\')"');
        expect(adminRegistration).not.toContain('onclick="addNewAdminRegModule(\'free\')"');
        expect(adminRegistration).not.toContain('onchange="selectProgModule(');
        expect(adminRegistration).not.toContain('onchange="selectFreeModule(');
        expect(adminRegistration).not.toContain('onclick="editProgSubModule(');
        expect(adminRegistration).not.toContain('onclick="editFreeSubModule(');
        expect(adminRegistration).toContain('data-admin-reg-add-module="prog"');
        expect(adminRegistration).toContain('data-admin-reg-add-module="free"');
        expect(adminRegistration).toContain('data-admin-reg-select-module=');
        expect(adminRegistration).toContain('data-admin-reg-module-tab="prog"');
        expect(adminRegistration).toContain('data-admin-reg-module-tab="free"');
        expect(adminRegistration).toContain('data-admin-reg-edit-module=');
        expect(adminRegistration).toContain('data-admin-reg-delete-module=');
        expect(adminRegistration).toContain('data-admin-reg-add-subject=');
        expect(adminRegistration).toContain('data-admin-reg-edit-submodule=');
        expect(adminRegistration).toContain('data-admin-reg-delete-submodule=');
        expect(adminRegistrationTrack).toContain('ADMIN_REG_BUILTIN_TABS');
        expect(adminRegistrationTrack).toContain('ADMIN_REG_TRACK_MIGRATION_VERSION = 1');
        expect(adminRegistrationTrack).toContain('function migrateAdminRegistrationCmsToTrackModel');
        expect(adminRegistrationTrack).toContain('function renderAdminRegTabBar(activeTab)');
        expect(adminRegistrationTrack).toContain('data-admin-reg-manage-tab=');
        expect(adminRegistrationTrack).toContain('function openAdminRegTabManage');
        expect(adminRegistrationTrack).toContain('function renderAdminRegPanelHeadActions');
        expect(adminRegistrationTrack).toContain('data-admin-reg-panel-head-actions');
        expect(adminRegistrationTrack).toContain('admin-reg-panel-manage-tab-btn');
        expect(adminRegistration).toContain('function resetAdminRegistrationCmsDelegates');
        expect(adminRegistration).toContain('adminRegistrationCmsDelegateRoot');
        expect(adminToolsBundleSource).toContain('resetAdminRegistrationCmsDelegates');
        expect(adminRegistrationTrack).toContain('admin-reg-icon-action');
        expect(adminToolsBundleSource).toContain('data-admin-reg-panel-head-actions');
        expect(adminToolsBundleSource).toContain('lux-admin-tools-registration-panel-head');
        expect(adminRegistrationTrack).toContain('data-admin-reg-add-program');
        expect(adminRegistrationTrack).toContain('data-admin-reg-select-program');
        expect(adminRegistrationTrack).toContain('data-admin-reg-toggle-group');
        expect(adminRegistrationTrack).toContain('data-admin-reg-manage-course=');
        expect(adminRegistrationTrack).toContain('buildAdminRegManageGearMarkup');
        expect(adminRegistrationTrack).toContain('function convertTrackTabForStudent');
        expect(adminRegistrationTrack).toContain('window.renderAdminRegTrackTab = renderAdminRegTrackTab');
        expect(adminRegistration).toContain('selectedTrack: {}');
        expect(adminRegistration).toContain('handleAdminRegTrackDelegateClick(event)');
        expect(adminRegistration).toContain('renderAdminRegTrackTab(container, tabConfig)');
        expect(adminRegistration).toContain('getValidAdminRegTabIds(getAdminRegistrationFaculty())');
        expect(adminRegistration).toContain('renderAdminRegTabBar(safeTab)');
        expect(initialState).toContain('trackData: {}, customTabs: []');
        expect(css).toContain('.admin-reg-tab-add-btn');
        expect(adminRegistration).toContain('data-admin-reg-add-conc-program="1"');
        expect(adminRegistration).toContain('data-admin-reg-select-conc-program=');
        expect(adminRegistration).toContain('data-admin-reg-delete-conc-program=');
        expect(adminRegistration).toContain('data-admin-reg-add-conc-group=');
        expect(adminRegistration).toContain('data-admin-reg-toggle-conc-group=');
        expect(adminRegistration).toContain('data-admin-reg-edit-conc-group=');
        expect(adminRegistration).toContain('data-admin-reg-delete-conc-group=');
        expect(adminRegistration).toContain('data-admin-reg-add-conc-subject=');
        expect(adminRegistration).toContain('data-admin-reg-edit-conc-course=');
        expect(adminRegistration).toContain('data-admin-reg-delete-conc-course=');
        expect(adminRegistration).not.toContain('onclick="editConcGroup(');
        expect(adminRegistration).not.toContain('onclick="deleteConcGroup(');
        expect(adminRegistration).not.toContain('onclick="addSubjectToConcGroup(');
        expect(adminRegistration).not.toContain('onclick="editConcCourseName(');
        expect(adminRegistration).not.toContain('onclick="removeConcCourse(');
        expect(adminRegistration).toContain('data-admin-reg-add-minor-program="1"');
        expect(adminRegistration).toContain('data-admin-reg-select-minor-program=');
        expect(adminRegistration).toContain('data-admin-reg-delete-minor-program=');
        expect(adminRegistration).toContain('data-admin-reg-add-minor-group=');
        expect(adminRegistration).toContain('data-admin-reg-toggle-minor-group=');
        expect(adminRegistration).toContain('data-admin-reg-edit-minor-group=');
        expect(adminRegistration).toContain('data-admin-reg-delete-minor-group=');
        expect(adminRegistration).toContain('data-admin-reg-add-minor-subject=');
        expect(adminRegistration).toContain('class="admin-reg-subject-quick-matches"');
        expect(adminRegistration).toContain('class="admin-reg-no-results" hidden');
        expect(adminRegistration).toContain('class="subject-quick-match admin-reg-subject-quick-match"');
        expect(adminRegistration).toContain('class="admin-reg-course-modal-overlay"');
        expect(adminRegistration).toContain('class="admin-reg-course-modal-card"');
        expect(adminRegistration).toContain('class="admin-reg-course-modal-filter-grid"');
        expect(adminRegistration).toContain('class="course-item admin-reg-course-item"');
        expect(adminRegistration).toContain('class="admin-reg-course-item-meta"');
        expect(adminRegistration).toContain('class="admin-reg-course-item-cta"');
        expect(adminRegistration).toContain('class="admin-reg-program-head"');
        expect(adminRegistration).toContain('class="admin-reg-program-option');
        expect(adminRegistration).toContain('class="admin-reg-program-subject-row"');
        expect(adminRegistration).toContain('class="admin-reg-program-layout admin-reg-program-layout--wide"');
        expect(adminRegistration).toContain('class="admin-reg-program-option admin-reg-program-option--wide');
        expect(adminRegistration).toContain('class="admin-reg-program-pane-progress"');
        expect(adminRegistration).toContain('item.hidden = true;');
        expect(adminRegistration).toContain('noResults.hidden = visibleCount !== 0;');
        expect(adminRegistration).toContain('input.hidden = true;');
        expect(registration).toContain('class="admin-recent-card"');
        expect(registration).toContain('class="admin-recent-status ${statusClass}"');
        expect(registration).toContain('admin-provision-btn');
        expect(registration).toContain('class="admin-provision-empty-state"');
        expect(registration).toContain('class="admin-edit-staff-overlay"');
        expect(registration).toContain('class="admin-edit-staff-card"');
        expect(registration).toContain('class="admin-edit-staff-form"');
        expect(registration).toContain('class="edit-sched-row admin-edit-staff-row"');
        expect(registration).toContain('admin-edit-staff-row-control');
        expect(registration).toContain('class="admin-edit-staff-btn is-primary"');
        expect(registration).not.toContain('data-edit-staff-overlay="1" style="position:fixed;');
        expect(registration).not.toContain('const btnStyle = `display:flex; align-items:center; justify-content:flex-start; gap:12px;');
        expect(css).toContain('.admin-reg-subject-quick-matches {');
        expect(css).toContain('.admin-reg-no-results {');
        expect(css).toContain('#course-selection-modal-bg.admin-reg-course-modal-overlay');
        expect(css).toContain('#course-selection-modal-bg .admin-reg-course-modal-filter-grid');
        expect(css).toContain('#course-selection-modal-bg .admin-reg-course-item');
        expect(css).toContain('#course-selection-modal-bg .admin-reg-course-item-meta');
        expect(css).toContain('var(--atools-fade-modal-overlay)');
        expect(css).toContain('var(--atools-fade-modal-fill)');
        expect(css).toContain('var(--atools-fade-modal-head-bg)');
        expect(adminRegistration).toContain("modal.dataset.luxCourseModal = '1'");
        expect(adminRegistration).toContain('queueLuxuryTransparencyRefresh(undefined, { roots: [modal] })');
        expect(utilities).toContain("el.closest?.('#course-selection-modal-bg')");
        expect(luxury).toContain("node.closest?.('#course-selection-modal-bg')");
        expect(css).toContain('.admin-reg-program-head {');
        expect(css).toContain('.admin-reg-program-subject-row {');
        expect(css).toContain('.admin-reg-program-layout--wide {');
        expect(css).toContain('.admin-reg-program-pane-progress {');
        expect(css).toContain('.curriculum-library-module-option {');
        expect(css).toContain('.curriculum-library-panel--detail {');
        expect(css).not.toContain('[style*="ECTS"]');
        expect(css).not.toContain('[style*="color:#7c3aed"]');
        expect(css).not.toContain('[style*="color:#7C3AED"]');
        expect(css).not.toContain('[style*="color:rgb(124, 58, 237)"]');
        expect(css).toContain('.admin-recent-card {');
        expect(css).toContain('.admin-recent-status.is-pending {');
        expect(css).toContain('.admin-provision-btn {');
        expect(css).toContain('.admin-provision-empty-state {');
        expect(css).toContain('.admin-edit-staff-overlay {');
        expect(css).toContain('.admin-edit-staff-row {');
        expect(css).toContain('.admin-edit-staff-btn.is-primary {');
        expect(registration).not.toContain('bar.style.background =');
        expect(registration).not.toContain('txt.style.color =');
        expect(registration).not.toContain('statStatus.style.color =');
        expect(registration).not.toContain('econStatus.style.color =');
        expect(adminRegistration).not.toContain('ectsText.style.color =');
        expect(adminRegistration).not.toContain('progressBar.style.background =');
        expect(adminRegistration).toContain('data-admin-reg-edit-minor-course=');
        expect(adminRegistration).toContain('function loadAvailableSubjects()');
        expect(adminRegistration).not.toContain('function filterAndDisplaySubjects(');
        expect(adminRegistration).not.toContain('function addSelectedSubject(');
        expect((adminRegistration.match(/function renderFreeTab\(container, modules, tabType\)/g) || [])).toHaveLength(1);
        expect((adminRegistration.match(/function renderConcTab\(container, modules, tabType\)/g) || [])).toHaveLength(1);
        expect(adminRegistration).not.toContain('renderConcTab(container, modules, safeTab)');
        expect(adminRegistration).not.toContain('renderProgTab(container, modules, safeTab)');
        expect(planner).toContain('function bindAdminToolsPlannerDelegates()');
        expect(planner).toContain('bindAdminRegistrationCmsDelegates()');
        expect(planner).toContain('function getAdminOpsToneClass(value) {');
        expect(planner).not.toContain('onclick="refreshAdminSystemOpsDashboard(true)"');
        expect(planner).not.toContain('onclick="selectPaletteSubject(');
        expect(planner).toContain('data-admin-planner-refresh-system-ops="1"');
        expect(planner).toContain('data-admin-planner-palette-subject=');
        expect(planner).toContain('data-admin-planner-palette-name=');
        expect(planner).toContain("root.className = 'content-box admin-card admin-system-ops-root';");
        expect(planner).toContain('admin-system-ops-head');
        expect(planner).toContain('class="admin-system-ops-stat-grid"');
        expect(planner).toContain('admin-system-ops-section-card');
        expect(planner).not.toContain('regIcon.style.color =');
        expect(planner).not.toContain("root.style.marginTop = '24px';");
        expect(planner).not.toContain("root.style.marginBottom = '24px';");
        expect(planner).not.toContain("mc.style.display = 'block';");
        expect(planner).not.toContain("mc.style.display = 'none';");
        expect(planner).not.toContain("ctxBadge.style.background = 'rgba(255,255,255,0.2)'");
        expect(planner).not.toContain('class="content-box surface-card" style="padding:16px;"');
        expect(css).toContain('.admin-system-ops-root {');
        expect(css).toContain('.admin-system-ops-head {');
        expect(css).toContain('.admin-system-ops-stat-grid {');
        expect(css).toContain('.admin-system-ops-section-card {');
        expect(css).toContain('.admin-system-ops-pill.is-ready {');
    });

    it('keeps structured registration modals on the admin-tools glass and transparency contract', () => {
        const html = readSource('admin-tools.html');
        const css = readSource('assets/css/admin-tools-luxury.css');
        const utilities = readSource('assets/js/shared/utilities.js');
        const sharedRegistration = readSource('assets/js/pages/registration-shared.js');
        const adminRegistrationTrack = readSource('assets/js/pages/admin-registration-track.js');
        const luxury = readSource('assets/js/features/index-luxury.js');

        expect(html).toContain('assets/js/pages/registration-shared.js?v=20260606-regmanage3');
        expect(adminRegistrationTrack).toContain('builtinTabOverrides');
        expect(adminRegistrationTrack).toContain('hiddenBuiltinTabs');
        expect(sharedRegistration).toContain('buildAdminRegBuiltinTabRemoveVerification');
        expect(css).toContain('#kiu-admin-reg-manage-modal.registration-structured-modal-backdrop');
        expect(html).toContain('assets/js/features/index-luxury.js?v=20260606-coursemodal1');
        expect(css).toContain('--atools-fade-modal-overlay');
        expect(css).toContain('--atools-fade-modal-fill');
        expect(css).toContain('--atools-fade-modal-head-bg');
        expect(css).toContain('#kiu-structured-form-modal .registration-structured-modal-card');
        expect(css).toContain('background: var(--atools-fade-modal-fill) !important');
        expect(css).toContain('backdrop-filter: var(--atools-fade-blur) !important');
        expect(css).toContain('html.lux-high-transparency body.lux-route-admin-tools:not(.lux-light-mode) #kiu-structured-form-modal .registration-structured-modal-card');
        expect(css).toContain('html.lux-high-transparency body.lux-route-admin-tools:not(.lux-light-mode) #course-selection-modal-bg .admin-reg-course-modal-card');
        expect(utilities).toContain("el.closest?.('#kiu-structured-form-modal')");
        expect(utilities).toContain("el.closest?.('#course-selection-modal-bg')");
        expect(sharedRegistration).toContain("modal.dataset.luxStructuredModal = '1'");
        expect(sharedRegistration).toContain('queueLuxuryTransparencyRefresh(undefined, { roots: [modal] })');
        expect(luxury).toContain("node.closest?.('#kiu-structured-form-modal')");
        expect(luxury).toContain("node.closest?.('#course-selection-modal-bg')");
    });

    it('binds registration CMS delegates after the container is created post-load', () => {
        let delegateRoot = null;
        let clickHandler = null;
        document.body.innerHTML = '';

        function resetAdminRegistrationCmsDelegatesLikeProduction() {
            if (delegateRoot && clickHandler) {
                delegateRoot.removeEventListener('click', clickHandler);
            }
            delegateRoot = null;
            clickHandler = null;
        }

        function bindAdminRegistrationCmsDelegatesLikeProduction() {
            const root = document.getElementById('admin-reg-content-container');
            if (!root) return;
            if (delegateRoot === root && clickHandler) return;
            resetAdminRegistrationCmsDelegatesLikeProduction();
            clickHandler = (event) => {
                const addModuleTrigger = event.target.closest('[data-admin-reg-add-module]');
                if (!addModuleTrigger) return;
                window.__adminRegAddModuleTab = addModuleTrigger.getAttribute('data-admin-reg-add-module');
            };
            root.addEventListener('click', clickHandler);
            delegateRoot = root;
        }

        bindAdminRegistrationCmsDelegatesLikeProduction();
        expect(delegateRoot).toBeNull();

        const container = document.createElement('div');
        container.id = 'admin-reg-content-container';
        container.innerHTML = '<button type="button" data-admin-reg-add-module="prog">Add Module</button>';
        document.body.appendChild(container);

        bindAdminRegistrationCmsDelegatesLikeProduction();
        expect(delegateRoot).toBe(container);

        container.querySelector('[data-admin-reg-add-module="prog"]').click();
        expect(window.__adminRegAddModuleTab).toBe('prog');

        const replacement = document.createElement('div');
        replacement.id = 'admin-reg-content-container';
        replacement.innerHTML = '<button type="button" data-admin-reg-add-module="free">Add Module</button>';
        document.body.replaceChild(replacement, container);
        window.__adminRegAddModuleTab = '';

        bindAdminRegistrationCmsDelegatesLikeProduction();
        expect(delegateRoot).toBe(replacement);

        replacement.querySelector('[data-admin-reg-add-module="free"]').click();
        expect(window.__adminRegAddModuleTab).toBe('free');
    });
});
