const { readFileSync, existsSync } = require('fs');
const { join } = require('path');

function readSource(relativePath) {
    const full = join(process.cwd(), relativePath);
    if (!existsSync(full)) return '';
    return readFileSync(full, 'utf8');
}

describe('admin tools route regressions.test', () => {
    it('bare shell: no luxury/surfaces paint sheets; flat bare CSS', () => {
        const html = readSource('admin-tools.html');
        expect(html).toContain('lux-shell.css');
        expect(html).toContain('lux-page-bare-lite.css');
        expect(html).not.toMatch(/lux-page-bare\.css(?!-lite)/);
        expect(html).toContain('lux-page-bare-lite.css');
        expect(html).toMatch(/class="[^"]*lux-page-bare/);
        // Must not load the shared luxury paint sheet (looks like full design if present)
        expect(html).not.toMatch(/href=["'][^"']*index-luxury\.css/);
        expect(html).not.toMatch(/href=["'][^"']*lux-surfaces\.css/);
        expect(existsSync(join(process.cwd(), 'assets/css', 'admin-tools-luxury.css'))).toBe(false);
        const bare = readSource('assets/css/lux-page-bare-lite.css');
        expect(bare).toContain('body.lux-page-bare');
        // Global bare blur kill forbidden; scoped admin-tools page-shell demotion is OK.
        expect(bare).not.toMatch(/body\.lux-page-bare\s*\{[^}]*backdrop-filter:\s*none/);
        expect(bare).toContain('.lux-page-shell[data-lux-layout-only="1"]');
        // Layout rules must be present
        expect(bare).toContain('#admin-curriculum-search');
        expect(bare).toContain('admin-reg-program-layout');
        // No per-route visual overrides fighting global dashboard CTA buttons
        expect(bare).not.toMatch(/--lux-btn-pill-radius/);
        expect(bare).not.toMatch(/--lux-btn-frame-width/);
        expect(bare).not.toContain('content: none');
        const shell = readSource('assets/css/lux-shell.css');
        expect(shell).toContain('body.lux-page-bare .lux-page-shell');
        expect(shell).not.toContain('body.lux-page-bare .lux-page-shell :is(.page-hero, .lux-panel, .lux-alert)');
    });

    it('keeps admin-tools glass on outer panels only; page-shell is a layout wrapper', () => {
        const keep = readSource('assets/js/shared/lux-transparency.js');
        const transparency = readSource('assets/js/shared/lux-transparency.js');
        const alignment = readSource('assets/js/pages/admin-tools-index-alignment.js');
        const markup = readSource('assets/js/features/index-admin-tools.plain.js');
        expect(keep).toContain("el?.getAttribute?.('data-lux-layout-only') === '1'");
        expect(keep).toContain("el?.getAttribute?.('data-lux-glass-root') === '1'");
        expect(keep).not.toContain("el.classList.contains('lux-admin-tools-index-subpanel')");
        expect(markup.match(/data-lux-glass-root="1"/g)).toHaveLength(3);
        expect(markup).toMatch(/class="lux-control" id="admin-curriculum-search"/);
        expect(markup).toMatch(/class="lux-control" id="filter-curriculum-semester"/);
        expect(transparency).not.toContain("#lux-admin-tools-shell .admin-reg-tab");
        expect(transparency).not.toContain("el.classList.contains('admin-reg-tab') && el.closest?.('#lux-admin-tools-shell')");
        expect(transparency).toContain('isCssOwnedSurface');
        expect(transparency).toContain("'[data-lux-glass-root=\"1\"]'");
        expect(alignment).not.toContain("classList.add('lux-admin-tools-index-panel')");
        expect(alignment).not.toContain("data-lux-index-glass-root', '1'");
    });

    it('admin-tools plain chunk stays in sync with bundle-source SSOT', () => {
        const plain = readSource('assets/js/features/index-admin-tools.plain.js');
        const bundleSource = readSource('assets/js/features/index-admin-tools.bundle-source.js');
        const plainBanner = '/* Generated by scripts/regen-admin-tools-bundle.js — do not edit. SSOT: index-admin-tools.bundle-source.js */\n';
        const bundleBody = bundleSource.replace(/^\s*\/\*[\s\S]*?\*\/\s*/, '');
        expect(plain).toBe(plainBanner + bundleBody);
    });

    it('registration.js does not add lux-admin-tools-index-subpanel', () => {
        const reg = readSource('assets/js/pages/registration.js');
        expect(reg).not.toMatch(/classList\.add\(['"]lux-admin-tools-index-subpanel['"]\)/);
        expect(reg).not.toMatch(/class="[^"]*lux-admin-tools-index-subpanel/);
    });

    it('transparency.js has early-strip guard for layout-only and glass-root hosts', () => {
        const transparency = readSource('assets/js/shared/lux-transparency.js');
        expect(transparency).toContain("el.getAttribute('data-lux-layout-only') === '1'");
        expect(transparency).toMatch(/data-lux-layout-only[\s\S]*stripInlineGlassPaint/);
        expect(transparency).toMatch(/data-lux-glass-root="1"[\s\S]*stripInlineGlassPaint/);
        expect(transparency).toContain('.lux-page-shell[data-lux-layout-only="1"]');
    });

    it('staff and students-admin use outer glass-root panels; nested directory is soft-chrome only', () => {
        const staff = readSource('assets/js/pages/staff-command-center.js');
        const students = readSource('assets/js/pages/students-command-center.js');
        expect(staff).toMatch(/staff-hub-shell"[^>]*data-lux-glass-root="1"/);
        expect(staff).toMatch(/staff-hub-profile"[^>]*data-lux-glass-root="1"/);
        expect(staff).toContain('lux-soft-chrome staff-hub-directory-panel');
        expect(staff).not.toMatch(/lux-panel staff-hub-directory-panel/);
        expect(students).toMatch(/students-hub-shell"[^>]*data-lux-glass-root="1"/);
        expect(students).toMatch(/students-hub-profile"[^>]*data-lux-glass-root="1"/);
        expect(students).toContain('lux-soft-chrome students-hub-directory-panel');
        expect(students).not.toMatch(/lux-panel students-hub-directory-panel/);
    });

    it('bare-lite scopes admin-tools layout + registration workspace chrome via shared tokens', () => {
        const bare = readSource('assets/css/lux-page-bare-lite.css');
        // Page-shell demotion via layout-only attribute (not per-route CSS)
        expect(bare).toContain('.lux-page-shell[data-lux-layout-only="1"]');
        // Layout rules
        expect(bare).toContain('admin-reg-program-layout');
        expect(bare).toContain('lux-admin-curriculum-grid');
        expect(bare).toContain('lux-admin-curriculum-search-wrap');
        // Registration workspace component chrome (shared panel tokens)
        expect(bare).toContain('.admin-reg-program-option.is-active');
        expect(bare).toContain('.admin-reg-track-group-card');
        expect(bare).toContain('.admin-reg-manage-gear-btn');
        expect(bare).toContain('--lux-panel-border-soft');
        expect(bare).toContain('--lux-panel-surface-soft');
        expect(bare).not.toContain('--atools-fade-');
        // Outer glass-roots use global FOUC panel SSOT (not bare-lite paint)
        expect(bare).not.toContain('--home-desk-glass-surface');
        expect(bare).not.toMatch(/#lux-admin-tools-shell \.lux-panel\s*\{[^}]*background:/);
        expect(bare).not.toMatch(/data-lux-glass-root[\s\S]{0,80}--home-desk-glass/);
        // No CTA flatten / sheen kill / token overrides — global dashboard CSS owns those
        expect(bare).not.toMatch(/\.lux-primary-btn/);
        expect(bare).not.toMatch(/\.lux-secondary-btn/);
        expect(bare).not.toMatch(/\.lux-ghost-btn/);
        expect(bare).not.toContain('--lux-btn-pill-radius');
    });

    it('admin-tools surface uses lux CTAs only — no orphan neo / edit-staff / icon-action', () => {
        const files = [
            'admin-tools.html',
            'assets/js/features/index-admin-tools.plain.js',
            'assets/js/features/index-admin-tools.bundle-source.js',
            'assets/js/pages/registration-shared.js',
            'assets/js/pages/registration.js',
            'assets/js/pages/admin-registration-track.js',
        ];
        for (const rel of files) {
            const source = readSource(rel);
            expect(source, rel).not.toContain('social-neo-btn');
            expect(source, rel).not.toContain('admin-edit-staff-btn');
            expect(source, rel).not.toContain('admin-reg-icon-action');
            expect(source, rel).not.toContain('kiu-btn');
        }
        const plain = readSource('assets/js/features/index-admin-tools.plain.js');
        expect(plain).toContain('lux-primary-btn lux-glass-dialog-submit-btn');
        expect(plain).toContain('lux-ghost-btn lux-glass-dialog-cancel-btn');
        const shared = readSource('assets/js/pages/registration-shared.js');
        expect(shared).toContain("className = 'lux-primary-btn lux-glass-dialog-submit-btn'");
        expect(shared).toContain("className = 'lux-ghost-btn lux-glass-dialog-close-btn'");
        const track = readSource('assets/js/pages/admin-registration-track.js');
        expect(track).toContain('lux-icon-btn admin-reg-manage-gear-btn');
    });

    it('curriculum ops tiles and nested rails use shared shell primitives', () => {
        const plain = readSource('assets/js/features/index-admin-tools.plain.js');
        const fouc = readSource('assets/css/lux-fouc-ht.css');
        const bare = readSource('assets/css/lux-page-bare-lite.css');
        expect(plain).toContain('lux-stat lux-soft-chrome home-hover-chip');
        expect(plain).toContain('lux-admin-tools-curriculum-panel lux-soft-chrome');
        expect(plain).toContain('lux-admin-tools-registration-panel lux-soft-chrome');
        expect(plain).not.toContain('lux-admin-curriculum-ops-tile');
        expect(fouc).toContain('--lux-panel-blur-filter');
        expect(fouc).toContain('body.lux-unified-shell .lux-soft-chrome');
        expect(fouc).toContain('.lux-section-card:not([data-lux-layout-only="1"])');
        expect(fouc).toMatch(
            /body\.lux-unified-shell\s+:is\(\.page-hero,\s*\.lux-panel,\s*\.lux-alert[\s\S]*?\)[\s\S]{0,400}var\(--lux-panel-surface\)/
        );
        expect(fouc).not.toContain('lux-admin-curriculum-ops-tile');
        expect(bare).not.toContain('--home-desk-glass-surface');
        expect(bare).not.toContain('lux-admin-curriculum-ops-tile');
    });
});
