import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { JSDOM } from 'jsdom';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('career-market route regressions', () => {
    it('keeps the extracted route assets and lazy modal shells intact', () => {
        const html = readSource('career-market.html');
        const routeJs = readSource('assets/js/pages/career-market.js');

        const dom = new JSDOM(html);
        const { document } = dom.window;

        expect(html).toContain('assets/css/career-market-route.css?v=20260531-routeglass15');
        expect(html).toContain('assets/js/pages/career-market.js?v=20260516-career-route1');
        expect(html).not.toContain('<style>');
        expect(html).not.toContain('(function initCareerMarketPage() {');

        expect(document.getElementById('career-provider-modal')).toBeNull();
        expect(document.getElementById('career-instructions-modal')).toBeNull();
        expect(document.getElementById('career-tool-modal')).toBeNull();
        expect(document.getElementById('career-provider-modal-template')).not.toBeNull();
        expect(document.getElementById('career-instructions-modal-template')).not.toBeNull();
        expect(document.getElementById('career-tool-modal-template')).not.toBeNull();
        expect(document.getElementById('career-reports-new')).toBeNull();
        expect(document.getElementById('career-vacancy-output')).toBeNull();
        expect(document.getElementById('career-history-items')).not.toBeNull();
        expect(document.getElementById('career-message-list')).not.toBeNull();
        expect(html).toContain('class="career-report-document career-tool-report-document"');
        expect(html).toContain('class="career-report-section-title career-tool-section-title"');
        expect(html).toContain('class="career-report-section-copy career-tool-section-copy"');
        expect(html).toContain('class="career-provider-field-label"');
        expect(html).toContain('class="career-provider-field-select"');
        expect(html).toContain('class="career-provider-field-input"');
        expect(html).toContain('class="career-provider-field-textarea"');
        expect(html).toContain('class="career-provider-field-file-input"');
        expect(html).toContain('class="career-provider-route-title"');
        expect(html).toContain('class="career-provider-meta-line"');
        expect(html).toContain('class="career-provider-health career-provider-health-copy"');
        expect(document.getElementById('mobile-bottom-nav')?.hasAttribute('hidden')).toBe(true);
        expect(document.getElementById('mobile-action-sheet')?.hasAttribute('hidden')).toBe(true);
        expect(document.getElementById('mob-badge-msg')?.hasAttribute('hidden')).toBe(true);
        expect(document.getElementById('mob-badge-notif')?.hasAttribute('hidden')).toBe(true);
        expect(html).not.toContain('style="display:none;"');

        expect(routeJs).toContain('function ensureCareerTemplateContent(templateId, rootId)');
        expect(routeJs).toContain("window.__kiuCareerDebug = {");
        expect(routeJs).toContain('function createCareerHistoryItemNode(item, index)');
        expect(routeJs).toContain('function handleCareerHistorySelection(index)');
        expect(routeJs).toContain("container.dataset.careerHistoryBound = '1';");
        expect(routeJs).toContain('container.replaceChildren(fragment);');
        expect(routeJs).toContain('function setCareerOverlayBodyState(isOpen, stateClass) {');
        expect(routeJs).toContain('function setElementShown(element, shown, displayValue) {');
        expect(routeJs).toContain('Add image<input type="file" accept="image/*" data-add-image="');
        expect(routeJs).toContain('hidden></label>');
        expect(routeJs).toContain('setElementShown(empty, false);');
        expect(routeJs).toContain('setElementShown(list, true);');
        expect(routeJs).toContain('setElementShown(list, false);');
        expect(routeJs).toContain('setTimeout(function() { setElementShown(sheet, false); }, 300);');
        expect(routeJs).toContain('setElementShown(sheet, true);');
        expect(routeJs).toContain('isElementShown(sheet) ? closeSheet() : openSheet();');
        expect(routeJs).toContain('setElementShown(nav, isMob());');
        expect(routeJs).toContain("setCareerOverlayBodyState(true, 'career-modal-open');");
        expect(routeJs).toContain("setCareerOverlayBodyState(false, 'career-modal-open');");
        expect(routeJs).toContain("setCareerOverlayBodyState(true, 'career-sheet-open');");
        expect(routeJs).toContain("setCareerOverlayBodyState(false, 'career-sheet-open');");
        expect(routeJs).toContain('data-agent-id="');
        expect(routeJs).toContain('class="career-agent-log-title"');
        expect(routeJs).toContain('class="career-agent-log-status"');
        expect(routeJs).toContain('class="career-agent-finding-card"');
        expect(routeJs).toContain('class="career-agent-finding-head"');
        expect(routeJs).toContain('class="career-agent-finding-title"');
        expect(routeJs).toContain('class="career-agent-finding-confidence"');
        expect(routeJs).toContain('class="career-agent-finding-points"');
        expect(routeJs).toContain('class="career-intake-gate-title"');
        expect(routeJs).toContain('class="career-intake-gate-copy"');
        expect(routeJs).toContain('class="career-intake-gate-note"');
        expect(routeJs).toContain('class="career-review-item-label"');
        expect(routeJs).toContain('class="career-review-item-value"');
        expect(routeJs).toContain('class="career-agent-mini-card"');
        expect(routeJs).toContain('class="career-agent-mini-title"');
        expect(routeJs).toContain('class="career-agent-mini-copy"');
        expect(routeJs).toContain('career-instruction-section-title-input');
        expect(routeJs).toContain('career-instruction-section-remove-btn');
        expect(routeJs).toContain('career-instruction-block-label');
        expect(routeJs).toContain('career-instruction-add-text-btn');
        expect(routeJs).toContain('career-instruction-add-image-btn');
        expect(routeJs).toContain('class="career-field-label"');
        expect(routeJs).toContain('class="career-field-select"');
        expect(routeJs).toContain('class="career-field-input"');
        expect(routeJs).toContain('class="career-field-textarea"');
        expect(routeJs).toContain('class="career-report-section-title"');
        expect(routeJs).toContain('class="career-report-section-copy"');
        expect(routeJs).toContain('class="career-report-grid career-report-score-grid"');
        expect(routeJs).toContain('class="career-score-box career-report-score-card"');
        expect(routeJs).toContain('class="career-report-table-row career-report-table-row--head"');
        expect(routeJs).toContain('class="career-report-table-head-cell"');
        expect(routeJs).toContain('class="career-report-table-cell"');
        expect(routeJs).toContain('class="career-score-box-label"');
        expect(routeJs).toContain('class="career-score-box-value"');
        expect(routeJs).toContain('class="career-report-saved-title"');
        expect(routeJs).toContain('class="career-report-saved-date"');
        expect(routeJs).toContain('class="career-report-saved-stream"');
        expect(routeJs).toContain('class="lux-hero-main career-workspace-hero-main"');
        expect(routeJs).toContain('class="career-workspace-badge career-workspace-badge-card');
        expect(routeJs).toContain('class="career-primary-action career-reports-new-btn"');
        expect(routeJs).toContain('class="career-primary-action career-vacancy-run-btn"');
        expect(routeJs).toContain('class="career-step-icon ');
        expect(routeJs).toContain('class="career-step-label"');
        expect(routeJs).toContain('class="career-secondary-action career-wizard-save-draft-btn"');
        expect(routeJs).toContain('class="career-wizard-actions-main"');
        expect(routeJs).toContain('class="career-secondary-action career-wizard-back-btn"');
        expect(routeJs).toContain('class="career-primary-action career-wizard-next-btn"');
        expect(routeJs).toContain('class="career-section-note career-report-status-note career-report-status-note--running"');
        expect(routeJs).toContain('class="career-section-note career-report-status-note career-report-status-note--error"');
        expect(routeJs).toContain('class="career-section-note career-report-status-note career-report-status-note--empty"');
        expect(routeJs).toContain('class="career-section-note career-report-status-note career-report-summary-note"');
        expect(routeJs).toContain('class="career-primary-action career-report-provider-open-btn"');
        expect(routeJs).toContain('class="career-section-note career-vacancy-empty-note career-vacancy-status-note career-vacancy-status-note--settings"');
        expect(routeJs).toContain('class="career-section-note career-vacancy-empty-note career-vacancy-status-note career-vacancy-status-note--running"');
        expect(routeJs).toContain('class="career-section-note career-vacancy-empty-note career-vacancy-status-note career-vacancy-status-note--error"');
        expect(routeJs).toContain('class="career-primary-action career-vacancy-provider-open-btn"');
        expect(routeJs).toContain('class="career-report-document career-vacancy-output-shell"');
        expect(routeJs).toContain('class="career-section-note career-report-empty-note"');
        expect(routeJs).toContain('class="career-report-section career-vacancy-section"');
        expect(routeJs).toContain('class="career-section-note career-vacancy-empty-note"');
        expect(routeJs).not.toContain('style="--career-agent-rgb:');
        expect(routeJs).not.toContain("empty.style.display = 'none'");
        expect(routeJs).not.toContain("list.style.display = 'none'");
        expect(routeJs).not.toContain("element.style.display = shown ? (displayValue || '') : 'none';");
        expect(routeJs).not.toContain("document.body.style.overflow = 'hidden';");
        expect(routeJs).not.toContain("document.body.style.overflow = '';");
        expect(routeJs).not.toContain("career-history-items').innerHTML");
        expect(readSource('assets/css/career-market-route.css')).toContain('body.lux-route-career-market.career-modal-open,');
        expect(readSource('assets/css/career-market-route.css')).toContain('body.lux-route-career-market.career-sheet-open {');
        expect(readSource('assets/css/career-market-route.css')).toContain(".career-agent-node[data-agent-id='coordinator']");
        expect(readSource('assets/css/career-market-route.css')).toContain(".career-agent-node[data-agent-id='writer']");
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-log-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-log-status');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-finding-card');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-finding-head');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-finding-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-finding-confidence');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-finding-points');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-intake-gate-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-intake-gate-copy');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-intake-gate-note');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-review-item-label');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-review-item-value');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-mini-card');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-mini-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-agent-mini-copy');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-instruction-section-title-input');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-instruction-section-remove-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-instruction-block-label');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-instruction-add-text-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-instruction-add-image-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-field-label');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-field-select');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-field-input');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-field-textarea');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-field-label');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-field-select');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-field-input');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-field-textarea');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-field-file-input');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-route-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-meta-line');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-provider-health-copy');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-section-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-section-copy');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-tool-report-document');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-tool-section-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-tool-section-copy');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-score-grid');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-score-card');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-table-head-cell');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-table-cell');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-score-box-label');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-score-box-value');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-saved-item');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-saved-title');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-saved-date');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-saved-stream');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-vacancy-section');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-vacancy-output-shell');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-empty-note');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-vacancy-empty-note');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-workspace-hero-main');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-workspace-badge-card');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-reports-new-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-vacancy-run-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-step-icon');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-step-label');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-wizard-save-draft-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-wizard-actions-main');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-wizard-back-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-wizard-next-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-status-note');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-vacancy-status-note');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-report-provider-open-btn');
        expect(readSource('assets/css/career-market-route.css')).toContain('.career-vacancy-provider-open-btn');
    });
});
