import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('exams delegation regressions', () => {
    it('keeps the exams console and lazy companion modules on delegated actions and field handlers', () => {
        const baseSource = readSource('assets/js/pages/exams-console.js');
        const builderSource = readSource('assets/js/pages/exams-console-builder.js');
        const adminSource = readSource('assets/js/pages/exams-console-admin.js');
        const attemptsSource = readSource('assets/js/pages/exams-console-attempts.js');
        const routeCss = readSource('assets/css/exam-studio.css');
        const combined = `${baseSource}\n${builderSource}\n${adminSource}\n${attemptsSource}`;

        expect(baseSource).toContain('function invokeExamDelegate(fnName, rawArgs, target)');
        expect(baseSource).toContain('data-exam-call="setExamTab"');
        expect(baseSource).toContain('data-exam-change-call="${updateFunc}"');
        expect(builderSource).toContain('function setAutoGenVariantCount(value)');
        expect(builderSource).toContain('data-exam-call="saveAndSubmitExamTemplate"');
        expect(builderSource).toContain('data-exam-input-call="syncExamTemplateField"');
        expect(builderSource).toContain('class="ex2-field ex2-field--compact ex2-field--points"');
        expect(builderSource).toContain('class="ex2-field-label-11">Points</span>');
        expect(builderSource).toContain('class="ex2-input ex2-input--points"');
        expect(builderSource).toContain('class="ex2-field ex2-field--compact ex2-field--options"');
        expect(builderSource).toContain('class="ex2-input ex2-input--options"');
        expect(builderSource).toContain('class="ex2-question-card-title ex2-question-card-title--builder"');
        expect(builderSource).toContain('class="ex2-status ex2-question-card-status is-neutral"');
        expect(builderSource).toContain('class="ex2-meta ex2-question-card-meta"');
        expect(builderSource).toContain('class="ex2-field-label">Question text</span>');
        expect(builderSource).toContain('class="ex2-field-label">Correct option</span>');
        expect(builderSource).toContain('class="ex2-field-label">Options</span>');
        expect(builderSource).toContain('class="ex2-option-index">');
        expect(builderSource).toContain('class="ex2-list-copy-truncate"');
        expect(builderSource).toContain('class="ex2-list-item ex2-list-item--compact"');
        expect(builderSource).toContain('class="ex2-list-item-head"');
        expect(builderSource).toContain('class="ex2-list-item-title"');
        expect(builderSource).toContain('class="ex2-list-item-meta"');
        expect(builderSource).toContain('class="ex2-field-label">Exam title</span>');
        expect(builderSource).toContain('class="ex2-field-label">Subject</span>');
        expect(builderSource).toContain('class="ex2-field-label">Number of variants</span>');
        expect(builderSource).toContain('class="ex2-field-label">Questions per variant</span>');
        expect(builderSource).toContain('class="ex2-qnav-label">Question</label>');
        expect(builderSource).toContain('class="ex2-qnav-count">of ${total}</span>');
        expect(builderSource).toContain('class="ex2-empty ex2-builder-empty"');
        expect(builderSource).toContain('class="ex2-builder-empty-copy"');
        expect(builderSource).toContain('class="ex2-warning ex2-builder-warning"');
        expect(builderSource).toContain('class="ex2-builder-warning-copy"');
        expect(builderSource).toContain('class="step-num ex2-progress-step-num"');
        expect(builderSource).toContain('class="step-label ex2-progress-step-label"');
        expect(builderSource).toContain('class="ex2-panel-head ex2-panel-head--flush"');
        expect(builderSource).toContain('class="ex2-builder-section-title"');
        expect(builderSource).toContain('class="ex2-builder-section-copy"');
        expect(builderSource).toContain('class="ex2-form-grid ex2-form-grid--mt-12"');
        expect(builderSource).toContain('class="ex2-inline-actions ex2-inline-actions--mt-14 ex2-inline-actions--gap-10"');
        expect(builderSource).toContain('class="ex2-inline-actions ex2-inline-actions--mt-8"');
        expect(builderSource).toContain('class="ex2-review-copy"');
        expect(builderSource).toContain('class="ex2-review-card-title"');
        expect(builderSource).toContain('ex2-review-card-meta');
        expect(builderSource).toContain('ex2-list-card ex2-list-card--pad-16');
        expect(builderSource).toContain('class="ex2-list-card ex2-list-card--pad-16 ex2-variant-summary-card"');
        expect(builderSource).toContain('class="ex2-variant-summary-title"');
        expect(builderSource).toContain('ex2-variant-summary-meta');
        expect(builderSource).toContain('class="ex2-review-card ex2-review-card--accent"');
        expect(builderSource).toContain('class="ex2-review-copy ex2-review-copy--tight"');
        expect(builderSource).toContain('class="ex2-review-summary-card"');
        expect(builderSource).toContain('class="ex2-review-summary-value"');
        expect(builderSource).toContain('class="ex2-review-summary-label"');
        expect(builderSource).toContain('class="ex2-builder-title ex2-builder-title--mt-8"');
        expect(builderSource).toContain('class="ex2-panel ex2-panel--animated"');
        expect(builderSource).toContain('class="ex2-divider ex2-divider--14"');
        expect(builderSource).toContain('class="ex2-btn is-secondary ex2-btn--full-center"');
        expect(builderSource).toContain('class="ex2-sidebar-stat-label"');
        expect(builderSource).toContain('class="ex2-sidebar-stat-value"');
        expect(builderSource).not.toContain('style="margin:0;min-width:80px;"');
        expect(builderSource).not.toContain('style="width:70px;"');
        expect(builderSource).not.toContain('style="margin:0;min-width:110px;"');
        expect(builderSource).not.toContain('style="width:86px;"');
        expect(builderSource).not.toContain('style="max-width:320px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;"');
        expect(builderSource).not.toContain('style="padding:0;"');
        expect(builderSource).not.toContain('style="margin-top:12px;"');
        expect(builderSource).not.toContain('style="margin-top:14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap;"');
        expect(builderSource).not.toContain('style="font-size:12px;"');
        expect(builderSource).not.toContain('style="margin-top:8px;"');
        expect(builderSource).not.toContain('style="margin-top:10px;"');
        expect(builderSource).not.toContain('style="padding:16px;"');
        expect(builderSource).not.toContain('style="border-color:rgba(var(--lux-accent-rgb),0.3);"');
        expect(builderSource).not.toContain('style="font-size:13px;color:var(--lux-text-muted);line-height:1.6;"');
        expect(builderSource).not.toContain('style="animation: exSlideIn .3s ease;"');
        expect(builderSource).not.toContain('style="width:100%;justify-content:center;"');
        expect(adminSource).toContain('function setExamSplitStudentCount(value)');
        expect(adminSource).toContain('data-exam-call="saveExamSchedule"');
        expect(adminSource).toContain('data-exam-change-call="updateExamScheduleField"');
        expect(adminSource).toContain('class="ex2-field-label">Feedback for the Professor/TA (required)</span>');
        expect(adminSource).toContain('class="ex2-cohort-check-label">');
        expect(adminSource).toContain('class="ex2-mini-list-item">');
        expect(adminSource).toContain('class="ex2-mini-list-item ex2-mini-list-item--muted"');
        expect(adminSource).toContain('class="ex2-field-label">Approved Template</span>');
        expect(adminSource).toContain('class="ex2-field-label">Start</span>');
        expect(adminSource).toContain('class="ex2-field-label">Overflow room</span>');
        expect(adminSource).toContain('class="ex2-copy-muted ex2-copy-muted--mt-6"');
        expect(adminSource).toContain('class="ex2-collision-item">');
        expect(adminSource).toContain('class="ex2-collision-item ex2-collision-item--overflow"');
        expect(adminSource).toContain('class="ex2-form-grid ex2-form-grid--mt-8"');
        expect(adminSource).toContain('class="ex2-btn is-secondary ex2-btn--mt-10"');
        expect(adminSource).toContain('class="ex2-panel-title"');
        expect(adminSource).toContain('class="ex2-panel-copy"');
        expect(adminSource).toContain('class="ex2-empty-state ex2-review-queue-empty"');
        expect(adminSource).toContain('class="ex2-empty-state ex2-schedule-groups-empty"');
        expect(adminSource).toContain('class="ex2-empty-state ex2-schedule-sessions-empty"');
        expect(adminSource).toContain('class="ex2-empty-state-copy"');
        expect(adminSource).toContain('class="ex2-status ex2-session-published-pill is-approved ex2-status--ml-6"');
        expect(adminSource).toContain('class="ex2-meta ex2-cohort-card-meta"');
        expect(adminSource).toContain('class="ex2-card-copy ex2-cohort-card-copy"');
        expect(adminSource).toContain('class="ex2-review-grid"');
        expect(adminSource).toContain('class="ex2-quiz-card ex2-quiz-card--static ex2-review-queue-card"');
        expect(adminSource).toContain('class="ex2-quiz-card-head ex2-quiz-card-head--mb-12 ex2-review-queue-head"');
        expect(adminSource).toContain('class="ex2-inline-actions ex2-inline-actions--gap-10 ex2-review-queue-status-row"');
        expect(adminSource).toContain('class="ex2-copy-muted ex2-review-queue-author-copy"');
        expect(adminSource).toContain('class="ex2-tag ex2-review-queue-faculty-tag"');
        expect(adminSource).toContain('class="ex2-quiz-card-title ex2-quiz-card-title--lg"');
        expect(adminSource).toContain('class="ex2-quiz-card-meta ex2-quiz-card-meta--mb-12"');
        expect(adminSource).toContain('class="ex2-review-summary-card"');
        expect(adminSource).toContain('class="ex2-review-summary-value"');
        expect(adminSource).toContain('class="ex2-review-summary-label"');
        expect(adminSource).toContain('class="ex2-status ex2-session-status-chip is-');
        expect(adminSource).toContain('class="ex2-status ex2-session-published-pill is-approved ex2-status--ml-6"');
        expect(adminSource).toContain('class="ex2-session-head-main"');
        expect(adminSource).toContain('class="ex2-session-card-title"');
        expect(adminSource).toContain('class="ex2-meta ex2-session-card-meta"');
        expect(adminSource).toContain('class="ex2-card-copy ex2-session-card-copy"');
        expect(adminSource).toContain('class="ex2-inline-actions ex2-session-action-row"');
        expect(adminSource).toContain('class="ex2-session-stat-card"');
        expect(adminSource).toContain('class="ex2-session-stat-value"');
        expect(adminSource).toContain('class="ex2-session-stat-label"');
        expect(adminSource).toContain('class="ex2-inline-actions ex2-inline-actions--mt-16 ex2-review-queue-action-row"');
        expect(adminSource).toContain('class="ex2-divider ex2-divider--20"');
        expect(adminSource).toContain('class="ex2-summary-title"');
        expect(adminSource).toContain('class="ex2-session-summary-card"');
        expect(adminSource).toContain('class="ex2-session-summary-value"');
        expect(adminSource).toContain('class="ex2-session-summary-label"');
        expect(adminSource).toContain('class="ex2-digital-pin"');
        expect(adminSource).toContain('class="ex2-digital-pin-label"');
        expect(adminSource).toContain('class="ex2-digital-pin-value"');
        expect(adminSource).toContain('class="fas fa-calendar-plus ex2-heading-icon"');
        expect(adminSource).not.toContain('style="font-size:12px;color:var(--lux-text-muted);margin:6px 0;"');
        expect(adminSource).not.toContain('style="margin-top:8px;"');
        expect(adminSource).not.toContain('style="margin-top:10px;"');
        expect(adminSource).not.toContain('style="margin-left:6px;"');
        expect(adminSource).not.toContain('style="display:grid;gap:14px;"');
        expect(adminSource).not.toContain('style="cursor:default;"');
        expect(adminSource).not.toContain('style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;flex-wrap:wrap;gap:8px;"');
        expect(adminSource).not.toContain('style="font-size:17px;font-weight:700;margin:0 0 6px;"');
        expect(adminSource).not.toContain('style="font-size:13px;color:var(--lux-text-muted);margin-bottom:12px;"');
        expect(adminSource).not.toContain('style="margin-top:16px;"');
        expect(adminSource).not.toContain('style="border-top:1px solid var(--lux-border);margin:20px 0;"');
        expect(adminSource).not.toContain('style="font-size:15px;font-weight:700;margin-bottom:6px;"');
        expect(adminSource).not.toContain('style="margin-top:16px;padding:14px;border-radius:14px;border:1px solid var(--lux-border);text-align:center;"');
        expect(attemptsSource).toContain('data-exam-call="runExamStudentAction"');
        expect(attemptsSource).toContain('data-exam-input-call="updateExamManualGradeDraft"');
        expect(attemptsSource).toContain('class="ex2-panel-title"');
        expect(attemptsSource).toContain('class="ex2-panel-copy"');
        expect(attemptsSource).toContain('class="ex2-empty-copy"');
        expect(attemptsSource).toContain('class="ex2-select-card-title"');
        expect(attemptsSource).toContain('class="ex2-select-card-copy"');
        expect(attemptsSource).toContain('class="ex2-select-card-state"');
        expect(attemptsSource).toContain('class="ex2-attempt-identity"');
        expect(attemptsSource).toContain('class="ex2-attempt-student-name"');
        expect(attemptsSource).toContain('class="ex2-attempt-student-meta"');
        expect(attemptsSource).toContain('class="ex2-attempt-meta-item"');
        expect(attemptsSource).toContain('class="ex2-muted ex2-manual-note"');
        expect(attemptsSource).toContain('class="ex2-manual-score-label"');
        expect(attemptsSource).toContain('class="ex2-input is-small ex2-manual-score-input"');
        expect(attemptsSource).toContain('class="ex2-btn is-primary ex2-manual-score-save"');
        expect(attemptsSource).toContain('class="ex2-inline-actions ex2-manual-grade-actions"');
        expect(attemptsSource).toContain('class="ex2-btn is-primary ex2-manual-grade-save"');
        expect(attemptsSource).toContain('class="ex2-activity-metric"');
        expect(attemptsSource).toContain('class="ex2-activity-metric-value"');
        expect(attemptsSource).toContain('class="ex2-activity-metric-label"');
        expect(attemptsSource).toContain('class="ex2-results-meta-item"');
        expect(attemptsSource).toContain('class="ex2-response-summary-copy"');
        expect(routeCss).toContain('.ex2-panel-head--flush');
        expect(routeCss).toContain('.ex2-inline-actions--mt-8');
        expect(routeCss).toContain('.ex2-inline-actions--gap-10');
        expect(routeCss).toContain('.ex2-question-card-title--builder');
        expect(routeCss).toContain('.ex2-question-card-status');
        expect(routeCss).toContain('.ex2-question-card-meta');
        expect(routeCss).toContain('.ex2-field-label');
        expect(routeCss).toContain('.ex2-option-index');
        expect(routeCss).toContain('.ex2-builder-section-title');
        expect(routeCss).toContain('.ex2-builder-section-copy');
        expect(routeCss).toContain('.ex2-select-card-title');
        expect(routeCss).toContain('.ex2-select-card-copy');
        expect(routeCss).toContain('.ex2-select-card-state');
        expect(routeCss).toContain('.ex2-activity-metric');
        expect(routeCss).toContain('.ex2-activity-metric-value');
        expect(routeCss).toContain('.ex2-activity-metric-label');
        expect(routeCss).toContain('.ex2-attempt-identity');
        expect(routeCss).toContain('.ex2-attempt-student-name');
        expect(routeCss).toContain('.ex2-attempt-student-meta');
        expect(routeCss).toContain('.ex2-attempt-meta-item');
        expect(routeCss).toContain('.ex2-manual-note');
        expect(routeCss).toContain('.ex2-manual-score-label');
        expect(routeCss).toContain('.ex2-manual-score-input');
        expect(routeCss).toContain('.ex2-manual-grade-actions');
        expect(routeCss).toContain('.ex2-manual-score-save');
        expect(routeCss).toContain('.ex2-manual-grade-save');
        expect(routeCss).toContain('.ex2-results-meta-item');
        expect(routeCss).toContain('.ex2-response-summary-copy');
        expect(routeCss).toContain('.ex2-list-copy-truncate');
        expect(routeCss).toContain('.ex2-list-item--compact');
        expect(routeCss).toContain('.ex2-list-item-head');
        expect(routeCss).toContain('.ex2-list-item-title');
        expect(routeCss).toContain('.ex2-list-item-meta');
        expect(routeCss).toContain('.ex2-builder-empty');
        expect(routeCss).toContain('.ex2-builder-empty-copy');
        expect(routeCss).toContain('.ex2-builder-warning');
        expect(routeCss).toContain('.ex2-builder-warning-copy');
        expect(routeCss).toContain('.ex2-qnav-label');
        expect(routeCss).toContain('.ex2-qnav-count');
        expect(routeCss).toContain('.ex2-progress-step-num');
        expect(routeCss).toContain('.ex2-progress-step-label');
        expect(routeCss).toContain('.ex2-review-card-title');
        expect(routeCss).toContain('.ex2-review-card-meta');
        expect(routeCss).toContain('.ex2-variant-summary-card');
        expect(routeCss).toContain('.ex2-variant-summary-title');
        expect(routeCss).toContain('.ex2-variant-summary-meta');
        expect(routeCss).toContain('.ex2-sidebar-stat-label');
        expect(routeCss).toContain('.ex2-sidebar-stat-value');
        expect(routeCss).toContain('.ex2-review-copy--tight');
        expect(routeCss).toContain('.ex2-btn--full-center');
        expect(routeCss).toContain('.ex2-copy-muted--mt-6');
        expect(routeCss).toContain('.ex2-review-queue-head');
        expect(routeCss).toContain('.ex2-review-queue-status-row');
        expect(routeCss).toContain('.ex2-review-queue-action-row');
        expect(routeCss).toContain('.ex2-review-queue-author-copy');
        expect(routeCss).toContain('.ex2-review-queue-faculty-tag');
        expect(routeCss).toContain('.ex2-review-queue-empty');
        expect(routeCss).toContain('.ex2-collision-item--overflow');
        expect(routeCss).toContain('.ex2-schedule-groups-empty');
        expect(routeCss).toContain('.ex2-schedule-sessions-empty');
        expect(routeCss).toContain('.ex2-cohort-check-label');
        expect(routeCss).toContain('.ex2-mini-list-item--muted');
        expect(routeCss).toContain('.ex2-form-grid--mt-8');
        expect(routeCss).toContain('.ex2-btn--mt-10');
        expect(routeCss).toContain('.ex2-panel-title');
        expect(routeCss).toContain('.ex2-panel-copy');
        expect(routeCss).toContain('.ex2-empty-state-copy');
        expect(routeCss).toContain('.ex2-status--ml-6');
        expect(routeCss).toContain('.ex2-session-head-main');
        expect(routeCss).toContain('.ex2-session-action-row');
        expect(routeCss).toContain('.ex2-session-status-chip');
        expect(routeCss).toContain('.ex2-session-published-pill');
        expect(routeCss).toContain('.ex2-cohort-card-meta');
        expect(routeCss).toContain('.ex2-cohort-card-copy');
        expect(routeCss).toContain('.ex2-review-summary-card');
        expect(routeCss).toContain('.ex2-review-summary-value');
        expect(routeCss).toContain('.ex2-review-summary-label');
        expect(routeCss).toContain('.ex2-session-summary-card');
        expect(routeCss).toContain('.ex2-session-summary-value');
        expect(routeCss).toContain('.ex2-session-summary-label');
        expect(routeCss).toContain('.ex2-session-head-main');
        expect(routeCss).toContain('.ex2-session-action-row');
        expect(routeCss).toContain('.ex2-session-status-chip');
        expect(routeCss).toContain('.ex2-session-published-pill');
        expect(routeCss).toContain('.ex2-session-stat-card');
        expect(routeCss).toContain('.ex2-session-stat-value');
        expect(routeCss).toContain('.ex2-session-stat-label');
        expect(routeCss).toContain('.ex2-review-grid');
        expect(routeCss).toContain('.ex2-session-card-title');
        expect(routeCss).toContain('.ex2-session-card-meta');
        expect(routeCss).toContain('.ex2-session-card-copy');
        expect(routeCss).toContain('.ex2-digital-pin');
        expect(combined).not.toContain('onclick=');
        expect(combined).not.toContain('onchange=');
        expect(combined).not.toContain('oninput=');
        expect(combined).not.toContain('ondragover=');
        expect(combined).not.toContain('ondrop=');
    });
});
