import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('library route regressions', () => {
    it('keeps library as a real standalone route with its own shell bootstrap', () => {
        const html = readSource('library.html');
        const indexHtml = readSource('index.html');
        const pageScript = readSource('assets/js/pages/library.js');
        const appSource = readSource('assets/js/app/app.js');
        const navigationSource = readSource('assets/js/features/navigation.js');
        const routeCss = readSource('assets/css/library-route.css');
        const sharedSurfaceCss = readSource('assets/css/lux-surfaces.css');
        const sharedControlCss = readSource('assets/css/lux-controls.css');

        expect(indexHtml).toContain('id="page-library"');
        expect(appSource).toContain("const LIBRARY_RUNTIME_SCRIPT = 'assets/js/pages/library.js?v=20260527-libraryshell4';");
        expect(appSource).toContain('window.ensurePortalLibraryRuntimeLoaded = function ensurePortalLibraryRuntimeLoaded()');
        expect(navigationSource).toContain('const PORTAL_STANDALONE_ROUTE_IDS = new Set([');
        expect(navigationSource).toContain("'library'");

        expect(html).toContain('id="page-library"');
        expect(html).toContain('assets/css/library-route.css?v=20260530-libglass3');
        expect(html).toContain('assets/js/pages/library.js?v=20260527-libraryshell4');
        expect(html).toContain('assets/js/features/navigation.js?v=20260429-shellinit1');
        expect(html).toContain('bootStandaloneLibraryPage');
        expect(html).not.toContain("window.location.replace(target);");
        expect(html).not.toContain('assets/js/shared/social-hub.js');
        expect(html).not.toContain('assets/js/shared/social-render.js');
        expect(html).not.toContain('assets/js/shared/social-media.js');
        expect(html).not.toContain('assets/js/shared/messenger.js');
        expect(html).not.toContain('assets/js/pages/gradebook.js');
        expect(html).not.toContain('assets/js/pages/lms.js');
        expect(html).not.toContain('assets/js/pages/registration.js');
        expect(html).not.toContain('assets/js/pages/planner.js');
        expect(html).not.toContain('assets/js/pages/directories.js');
        expect(html).not.toContain('assets/js/pages/student-registration.js');
        expect(html).not.toContain('assets/js/pages/admin-registration.js');
        expect(html).not.toContain('window.__KIU_STANDALONE_MOBILE_SHELL_CONFIG = {');
        expect(html).not.toContain('assets/js/pages/standalone-mobile-shell.js?v=20260518-standalone-shell1');
        expect(html).not.toContain('data-library-search-field="query"');
        expect(html).not.toContain('data-library-picker-field="topic"');
        expect(html).not.toContain('setInterval(');

        expect(pageScript).toContain('const LIBRARY_PAGE_SHELL_MARKUP = `');
        expect(pageScript).toContain('library-page-hero lux-summary-surface lux-summary-surface--hero');
        expect(pageScript).toContain('library-catalog-card lux-summary-surface lux-summary-surface--panel');
        expect(pageScript).toContain('function ensureLibraryPageShell()');
        expect(pageScript).toContain('function renderLibraryPageShellContext()');
        expect(pageScript).toContain('function renderLibraryPage()');
        expect(pageScript).toContain('function ensureSharedLibraryState()');
        expect(pageScript).toContain('function renderSharedLibraryCatalog()');
        expect(pageScript).toContain('root.innerHTML = LIBRARY_PAGE_SHELL_MARKUP;');
        expect(pageScript).toContain("window.renderLibraryPageShellContext = renderLibraryPageShellContext;");
        expect(pageScript).toContain("window.renderLibraryPage = renderLibraryPage;");
        expect(pageScript).toContain("window.renderSharedLibraryCatalog = renderSharedLibraryCatalog;");
        expect(pageScript).toContain('function createLibraryRow(book, index)');
        expect(pageScript).toContain('function createLibraryPickerOption(field, option, currentValue)');
        expect(pageScript).toContain('function createLibrarySelectOption(value, label)');
        expect(pageScript).toContain('library-hero-side library-hero-summary');
        expect(pageScript).toContain('class="page-hero-badge wave2-chip wave2-chip--hero"');
        expect(pageScript).toContain('class="lux-hero-side-head library-hero-summary-card"');
        expect(pageScript).toContain('class="library-hero-summary-copy"');
        expect(pageScript).toContain('class="lux-hero-signal-list library-hero-signal-grid"');
        expect(pageScript).toContain('class="lux-hero-signal library-hero-signal-card library-hero-signal-card--visible"');
        expect(pageScript).toContain('class="library-hero-signal-label"');
        expect(pageScript).toContain('class="library-hero-signal-value"');
        expect(pageScript).toContain('class="library-hero-signal-copy"');
        expect(pageScript).toContain('class="lux-strip-card surface-card library-overview-card library-hero-metric wave2-summary-card');
        expect(pageScript).toContain('class="lux-card-title wave2-summary-label"');
        expect(pageScript).toContain('class="wave2-summary-value"');
        expect(pageScript).toContain('class="wave2-summary-copy"');
        expect(pageScript).toContain("cell.className = 'library-catalog-cell';");
        expect(pageScript).toContain("cell.className = 'library-catalog-cell library-catalog-pdf-cell';");
        expect(pageScript).toContain("link.className = 'library-pdf-link library-catalog-pdf-link';");
        expect(pageScript).toContain("row.className = 'library-catalog-row';");
        expect(pageScript).toContain("row.className = 'library-empty-row library-catalog-empty-row';");
        expect(pageScript).toContain("cell.className = 'library-empty-cell library-catalog-cell library-catalog-empty-cell';");
        expect(pageScript).toContain('tbody.replaceChildren(fragment);');
        expect(pageScript).toContain('panel.replaceChildren(fragment);');
        expect(pageScript).toContain('el.replaceChildren(fragment);');
        expect(pageScript).toContain('class="tab active library-tab-fill lux-tab-fill lux-select-card lux-tab-btn"');
        expect(pageScript).toContain('function renderLibraryEmptyState(tbody)');
        expect(pageScript).toContain("renderLibraryPicker(field, options, defaultLabel);");
        expect(pageScript).toContain('library-filter-panel');
        expect(pageScript).toContain('library-filter-grid');
        expect(pageScript).toContain('library-filter-field library-filter-field--search');
        expect(pageScript).toContain('library-filter-field library-filter-field--picker');
        expect(pageScript).toContain('class="library-field-input lux-control library-filter-input"');
        expect(pageScript).toContain('class="lux-picker-btn library-picker-btn library-filter-picker-btn"');
        expect(pageScript).toContain('class="library-picker-btn-copy library-filter-picker-copy lux-picker-copy"');
        expect(pageScript).toContain('class="lux-picker-panel lux-picker-panel-scroll library-picker-panel library-filter-picker-panel"');
        expect(pageScript).toContain('class="library-hidden-select library-filter-hidden-select lux-filter-hidden-select"');
        expect(routeCss).toContain('body.lux-route-library .library-page-hero');
        expect(routeCss).toContain('body.lux-route-library .library-hero-summary {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-summary-card {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-summary-copy {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-signal-grid {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-signal-card {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-signal-label {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-signal-value {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-signal-copy {');
        expect(routeCss).toContain('body.lux-route-library .library-widget-strip {');
        expect(sharedSurfaceCss).toContain('.wave2-summary-card {');
        expect(sharedSurfaceCss).toContain('.wave2-summary-label {');
        expect(sharedSurfaceCss).toContain('.wave2-summary-value {');
        expect(sharedSurfaceCss).toContain('.wave2-summary-copy {');
        expect(sharedSurfaceCss).toContain('.wave2-chip--hero {');
        expect(routeCss).toContain('body.lux-route-library .library-hero-metric {');
        expect(pageScript).toContain('class="library-field-input lux-control library-filter-input"');
        expect(pageScript).toContain('class="filter-shell library-filter-shell library-filter-panel surface-card lux-summary-surface lux-summary-surface--panel"');
        expect(routeCss).toContain('body.lux-route-library .library-filter-grid {');
        expect(sharedControlCss).toContain('.lux-picker-field {');
        expect(routeCss).not.toContain('body.lux-route-library .library-filter-field {');
        expect(sharedControlCss).toContain('.lux-filter-hidden-select {');
        expect(sharedControlCss).toContain('.lux-picker-copy {');
        expect(routeCss).not.toContain('body.lux-route-library .library-filter-hidden-select {');
        expect(routeCss).not.toContain('body.lux-route-library .library-filter-shell .library-filter-picker-btn {');
        expect(routeCss).not.toContain('body.lux-route-library .library-filter-picker-panel .lux-picker-option {');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-cell {');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-pdf-cell {');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-row:hover .library-catalog-cell');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-empty-row');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-empty-cell');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-footer {');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-count {');
        expect(routeCss).toContain('body.lux-route-library .library-catalog-pdf-link {');
        expect(routeCss).toContain('--lib-fade-surface');
        expect(routeCss).toContain('#page-library .lux-strip-card.surface-card');
        expect(routeCss).toContain('--lib-fade-control');
        expect(routeCss).toContain('.library-filter-shell .lux-picker-btn.library-picker-btn');
        expect(routeCss).toContain('.library-filter-shell .library-filter-input.lux-control');
        expect(routeCss).toContain('body.lux-route-library #page-library .lux-summary-surface {');
        expect(routeCss).toContain('body.lux-route-library .library-tabs {');
        expect(routeCss).toContain('body.lux-route-library .library-tabs .tab.active {');
        expect(sharedControlCss).toContain('.lux-tab-strip {');
        expect(sharedControlCss).toContain('.lux-tab-fill {');
        expect(sharedControlCss).toContain('.lux-tab-btn {');
    });
});
