import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('LMS protected quiz module split', () => {
    it('moves protected quiz launch/runtime helpers out of lms.js and into the dedicated module', () => {
        const lmsHtml = readSource('lms.html');
        const lmsSource = readSource('assets/js/pages/lms.js');
        const protectedQuizRuntimeSource = readSource('assets/js/pages/lms-protected-quiz-runtime.js');

        expect(lmsHtml).toContain('assets/js/pages/lms-protected-quiz-runtime.js?v=20260604-lmsprotected2');
        expect(protectedQuizRuntimeSource).toContain('function getProtectedQuizLaunchParams()');
        expect(protectedQuizRuntimeSource).toContain('function getProtectedQuizClientRuntime()');
        expect(protectedQuizRuntimeSource).toContain('async function refreshProtectedQuizClientRuntime(force = false)');
        expect(protectedQuizRuntimeSource).toContain('async function launchProtectedQuizInAntiCheat(resourceKey, quizId)');
        expect(protectedQuizRuntimeSource).toContain('openProtectedQuizLaunchPopup({');
        expect(protectedQuizRuntimeSource).not.toMatch(
            /launchProtectedQuizInAntiCheat[\s\S]*openAntiCheatDesktopApp\(\);[\s\S]*alert\(`Protected quizzes only open/
        );
        expect(protectedQuizRuntimeSource).toContain('window.attemptProtectedAppLaunch = attemptProtectedAppLaunch');
        expect(protectedQuizRuntimeSource).toContain('frame.hidden = true;');
        expect(protectedQuizRuntimeSource).toContain('link.hidden = true;');
        expect(protectedQuizRuntimeSource).toContain('function renderProtectedQuizLaunchShell(resourceKey, quiz, subjectLabel, groupLabel)');
        expect(protectedQuizRuntimeSource).toContain('function bootstrapProtectedQuizRouteFromUrl()');
        expect(protectedQuizRuntimeSource).toContain('function schedulePendingProtectedQuizLaunchResume()');
        expect(protectedQuizRuntimeSource).toContain('const PROTECTED_QUIZ_MONITOR_REFRESH_MS = 5000;');
        expect(protectedQuizRuntimeSource).toContain('function stopProtectedQuizMonitorAutoRefresh()');
        expect(protectedQuizRuntimeSource).toContain('function armProtectedQuizMonitorAutoRefresh(courseKey)');
        expect(protectedQuizRuntimeSource).toContain('async function refreshProtectedQuizMonitorLiveData(force = false)');
        expect(protectedQuizRuntimeSource).toContain('async function performProtectedMonitoringAction(resourceKey, quizId, studentId, action)');
        expect(protectedQuizRuntimeSource).toContain('async function renderLmsMonitoringSection(courseId, options = {})');
        expect(protectedQuizRuntimeSource).toContain('monitorOverride: monitor');
        expect(protectedQuizRuntimeSource).toContain('refreshProtectedQuizMonitorLiveData(true)');
        expect(protectedQuizRuntimeSource).toContain('window.refreshProtectedQuizMonitorLiveData = refreshProtectedQuizMonitorLiveData');
        expect(protectedQuizRuntimeSource).toContain('class="lms-student-quiz-cover lms-protected-launch-shell"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-student-quiz-cover-inner lms-protected-launch-inner"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-student-quiz-cover-title lms-protected-launch-title"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-student-quiz-cover-copy lms-protected-launch-copy"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-launch-support-copy"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-student-quiz-cover-actions lms-protected-launch-actions"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-blue lms-student-quiz-cover-btn lms-protected-launch-action-btn is-open-browser"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-outline lms-student-quiz-cover-btn lms-protected-launch-action-btn is-open-app"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-outline lms-student-quiz-cover-btn lms-protected-launch-link lms-protected-launch-action-btn is-install"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-panel lms-protected-monitor-page-shell"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-card-head lms-protected-monitor-page-head"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-card-title lms-protected-monitor-page-title"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-panel lms-protected-monitor-shell"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-card-head lms-protected-monitor-shell-head"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-card-title lms-protected-monitor-shell-title"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-stack lms-route-stack-mt-16 lms-protected-monitor-shell-list"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-copy lms-protected-monitor-status-line"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-copy lms-protected-monitor-latest-copy"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-pill lms-protected-monitor-pill is-warning-count"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-pill lms-protected-monitor-pill is-violation-count"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-pill lms-protected-monitor-pill ${attempt.antiCheatConnected ? \'is-connected\' : \'is-disconnected\'}"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-pill lms-protected-monitor-shell-pill is-students"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-route-pill lms-protected-monitor-shell-pill is-live"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-outline lms-quiz-action-btn is-compact lms-protected-monitor-action-btn is-block"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-outline lms-quiz-action-btn is-compact lms-protected-monitor-action-btn is-force-submit"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-outline lms-quiz-action-btn is-compact lms-protected-monitor-action-btn is-approve-reconnect"');
        expect(protectedQuizRuntimeSource).toContain('class="kiu-btn-outline lms-quiz-action-btn lms-protected-monitor-page-refresh lms-protected-monitor-action-btn is-refresh"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-details"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-metrics"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-audit-title"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-audit-item"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-audit-copy"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-audit-meta"');
        expect(protectedQuizRuntimeSource).toContain('class="lms-protected-monitor-audit-empty">No audit trail yet.</div>');
        const routeCss = readSource('assets/css/lms-route.css');
        expect(routeCss).toContain('.lms-protected-launch-inner {');
        expect(routeCss).toContain('.lms-protected-launch-copy {');
        expect(routeCss).toContain('.lms-protected-launch-support-copy {');
        expect(routeCss).toContain('.lms-protected-launch-actions {');
        expect(routeCss).toContain('.lms-protected-launch-action-btn.is-open-browser {');
        expect(routeCss).toContain('.lms-protected-launch-action-btn.is-open-app {');
        expect(routeCss).toContain('.lms-protected-launch-action-btn.is-install {');
        expect(routeCss).toContain('.lms-protected-monitor-page-head,');
        expect(routeCss).toContain('.lms-protected-monitor-page-copy,');
        expect(routeCss).toContain('.lms-protected-monitor-page-refresh,');
        expect(routeCss).toContain('.lms-protected-monitor-shell-list {');
        expect(routeCss).toContain('.lms-protected-monitor-empty-note {');
        expect(routeCss).toContain('.lms-protected-monitor-status-line {');
        expect(routeCss).toContain('.lms-protected-monitor-latest-copy {');
        expect(routeCss).toContain('.lms-protected-monitor-pill.is-warning-count {');
        expect(routeCss).toContain('.lms-protected-monitor-pill.is-violation-count {');
        expect(routeCss).toContain('.lms-protected-monitor-pill.is-connected,');
        expect(routeCss).toContain('.lms-protected-monitor-pill.is-override,');
        expect(routeCss).toContain('.lms-protected-monitor-shell-pill.is-students {');
        expect(routeCss).toContain('.lms-protected-monitor-action-btn.is-block,');
        expect(routeCss).toContain('.lms-protected-monitor-action-btn.is-unblock,');
        expect(routeCss).toContain('.lms-protected-monitor-action-btn.is-reset-warnings,');
        expect(routeCss).toContain('.lms-protected-monitor-audit-title {');
        expect(routeCss).toContain('.lms-protected-monitor-audit-item {');
        expect(routeCss).toContain('.lms-protected-monitor-audit-copy {');
        expect(routeCss).toContain('.lms-protected-monitor-audit-meta,');
        expect(lmsSource).not.toContain('function getProtectedQuizLaunchParams()');
        expect(lmsSource).not.toContain('function getProtectedQuizClientRuntime()');
        expect(lmsSource).not.toContain('async function refreshProtectedQuizClientRuntime(force = false)');
        expect(lmsSource).not.toContain('async function launchProtectedQuizInAntiCheat(resourceKey, quizId)');
        expect(lmsSource).not.toContain('function renderProtectedQuizLaunchShell(resourceKey, quiz, subjectLabel, groupLabel)');
        expect(lmsSource).not.toContain('function bootstrapProtectedQuizRouteFromUrl()');
        expect(lmsSource).not.toContain('async function performProtectedMonitoringAction(resourceKey, quizId, studentId, action)');
        expect(lmsSource).not.toContain('async function renderLmsMonitoringSection(courseId)');
    });
});
