import { describe, expect, it } from 'vitest';

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('LMS classroom tabs module split', () => {
    it('moves LMS classroom tabs and tab coordinator ownership out of lms.js and into the dedicated runtime module', () => {
        const lmsHtml = readSource('lms.html');
        const lmsSource = readSource('assets/js/pages/lms.js');
        const classroomSource = readSource('assets/js/pages/lms-classroom-tabs-runtime.js');
        expect(lmsHtml).toMatch(/assets\/js\/pages\/lms-classroom-tabs-runtime\.js\?v=/);

        expect(classroomSource).toContain('function openLMSGroups(subjectId, titleString, iconClass)');
        expect(classroomSource).toContain('function renderLmsBulkGroupTools(subjectId, subjectTitle, groups = [])');
        expect(classroomSource).toContain('function renderLmsSessionsSection(courseId = currentCourseId)');
        expect(classroomSource).toContain('function renderLmsMembersSection(courseId)');
        expect(classroomSource).toContain('function renderLmsInteractionSection(courseId = currentCourseId)');
        expect(classroomSource).toContain('function renderLmsAttendanceSection(courseId = currentCourseId)');
        expect(classroomSource).toContain('function getLmsSectionEnhancementContext(tab, courseId = currentCourseId)');
        expect(classroomSource).toContain("const markers = resourceKey && typeof getLmsSessionMarkersForGroup === 'function'");
        expect(classroomSource).toContain('function switchLMSTab(tab, options = {})');
        expect(classroomSource).not.toContain('kiu-btn');
        expect(classroomSource).toContain('function isLmsElementShown(element) {');
        expect(classroomSource).toContain('return Boolean(element) && !element.hidden;');
        expect(classroomSource).toContain('monitoringTab.hidden = ![USER_ROLES.PROFESSOR, USER_ROLES.TA, USER_ROLES.ADMIN].includes(effectiveRole);');
        expect(classroomSource).toContain('gradebookTab.hidden = false;');
        expect(classroomSource).toContain('class="lux-empty-state lms-route-empty-state--centered"');
        expect(classroomSource).toContain('class="lux-card-copy lms-route-copy-mt-10"');
        expect(classroomSource).toContain('class="lms-route-min-w-0"');
        expect(classroomSource).toContain('class="lms-bulk-copy lms-route-copy-mt-5"');
        expect(classroomSource).toContain('class="lms-bulk-head lms-bulk-head--plain"');
        expect(classroomSource).toContain('class="lms-route-panel lms-route-panel-compact lms-bulk-panel is-collapsed"');
        expect(classroomSource).toContain('class="lms-route-card lms-route-panel-compact lms-bulk-card"');
        expect(classroomSource).toContain('class="lms-route-card lms-route-panel-compact lms-session-official-card lms-next-session-card');
        expect(classroomSource).toContain('class="lms-route-panel lms-route-panel-compact lms-session-marker-composer"');
        expect(classroomSource).toContain('class="lms-route-card lms-route-panel-compact lms-session-marker-card is-');
        expect(classroomSource).toContain('class="lms-member-row"');
        expect(classroomSource).toContain('class="lms-route-avatar lms-member-row__avatar ${tone}"');
        expect(classroomSource).toContain('class="lms-member-row__name"');
        expect(classroomSource).toContain('class="lms-member-row__badges"');
        expect(classroomSource).toContain('class="lms-member-row-list"');
        expect(classroomSource).toContain('class="lms-member-section"');
        expect(classroomSource).toContain('canManageLmsGroupContent()');
        expect(classroomSource).toContain('class="lms-member-row__meta"');
        expect(classroomSource).toContain('class="lms-route-panel lms-member-overview-panel"');
        expect(classroomSource).toContain('class="lms-route-card-head lms-member-overview-head"');
        expect(classroomSource).toContain('class="lms-route-card-title lms-member-overview-title"');
        expect(classroomSource).toContain('class="lms-route-copy lms-route-copy-mt-4 lms-member-overview-copy"');
        expect(classroomSource).toContain('class="lms-route-actions lms-member-overview-actions"');
        expect(classroomSource).toContain('class="lms-route-card lms-route-panel-compact lms-deep-card is-');
        expect(classroomSource).toContain('class="lms-route-card lms-route-panel-compact lms-deep-panel"');
        expect(classroomSource).toContain('class="lms-route-panel lms-route-panel-compact lms-deep-toolkit"');
        expect(classroomSource).not.toContain('class="lms-route-card lms-route-panel-compact lms-deep-column"');
        expect(classroomSource).not.toContain('function renderLmsDeepWorkflowBoard');
        expect(classroomSource).not.toContain('function computeLmsQuizAnalytics');
        expect(classroomSource).not.toContain('function ensureLmsInteractionModerationForKey');
        expect(classroomSource).toContain('contentArea.insertAdjacentHTML(\'afterbegin\', injectedMarkup);');
        expect(classroomSource).toContain('class="lms-route-panel lms-attendance-panel"');
        expect(classroomSource).toContain('class="lms-route-table-shell lms-attendance-table-shell"');
        expect(classroomSource).toContain('class="kiu-table lms-attendance-table"');
        expect(classroomSource).toContain('class="lms-attendance-status-badge ');
        expect(classroomSource).toContain('class="lms-route-select lms-attendance-select"');
        expect(classroomSource).toContain('class="lms-route-title lms-route-title-mt-10"');
        expect(classroomSource).toContain('class="lms-route-copy lms-route-copy-mt-8"');
        expect(classroomSource).toContain('class="lms-route-copy lms-route-copy-mt-4"');
        expect(classroomSource).toContain('class="lms-route-copy lms-route-copy-mt-6"');
        expect(classroomSource).toContain('class="lms-route-copy lms-route-copy-mt-12"');
        expect(classroomSource).toContain('class="lms-route-card-head lms-route-card-head-mb-16"');
        expect(classroomSource).toContain('class="lms-route-card lms-route-panel-compact lux-strip-card lux-lms-group-card"');
        expect(classroomSource).not.toContain('class="lux-card lux-lms-group-card"');
        expect(classroomSource).not.toContain('class="lux-card-body"');
        expect(classroomSource).not.toContain('class="lms-bulk-panel is-collapsed"');
        expect(classroomSource).not.toContain('class="lms-bulk-card"');
        expect(classroomSource).not.toContain('class="lms-session-marker-composer is-collapsed"');
        expect(classroomSource).not.toContain('class="lms-session-marker-card is-');
        expect(classroomSource).not.toContain('style="min-height:220px; display:flex; align-items:center; justify-content:center; text-align:center;"');
        expect(classroomSource).not.toContain('style="margin-top:5px;"');
        expect(classroomSource).not.toContain('style="padding:0; border-bottom:0;"');
        expect(classroomSource).not.toContain('style="margin-top:10px;"');
        expect(classroomSource).not.toContain('style="margin-top:8px;"');
        expect(classroomSource).not.toContain('style="margin-top:4px;"');
        expect(classroomSource).not.toContain('style="margin-top:6px;"');
        expect(classroomSource).not.toContain('style="margin-top:12px;"');
        expect(classroomSource).not.toContain('style="margin-bottom:16px;"');
        expect(classroomSource).not.toContain("element.style.display = shown ? displayValue : 'none';");
        expect(classroomSource).not.toContain("monitoringTab.style.display = [USER_ROLES.PROFESSOR, USER_ROLES.TA, USER_ROLES.ADMIN].includes(effectiveRole) ? '' : 'none';");
        expect(classroomSource).not.toContain("gradebookTab.style.display = '';");

        expect(lmsSource).not.toContain('function openLMSGroups(subjectId, titleString, iconClass)');
        expect(lmsSource).not.toContain('function renderLmsBulkGroupTools(subjectId, subjectTitle, groups = [])');
        expect(lmsSource).not.toContain('function renderLmsSessionsSection(courseId = currentCourseId)');
        expect(lmsSource).not.toContain('function renderLmsMembersSection(courseId)');
        expect(lmsSource).not.toContain('function renderLmsInteractionSection(courseId = currentCourseId)');
        expect(lmsSource).not.toContain('function renderLmsAttendanceSection(courseId = currentCourseId)');
        expect(lmsSource).not.toContain('function getLmsSectionEnhancementContext(tab, courseId = currentCourseId)');
        expect(lmsSource).not.toContain('function switchLMSTab(tab)');
    });
});
