import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('LMS assignments module split', () => {
    it('moves LMS assignment workspace rendering and submission helpers out of lms.js and into the dedicated module', () => {
        const lmsHtml = readSource('lms.html');
        const lmsSource = readSource('assets/js/pages/lms.js');
        const assignmentsSource = readSource('assets/js/pages/lms-assignments-runtime.js');
        const routeCss = readSource('assets/css/lux-page-bare-lite.css');

        expect(assignmentsSource).toContain('function buildLmsSubmissionDraftKey(resourceKey, assignmentId, userId = getCurrentUserId() || \'student\')');
        expect(assignmentsSource).toContain('window.submitAssignment = window.submitAssignment || submitAssignment');
        expect(readSource('assets/js/pages/lms-classroom-tabs-runtime.js')).toContain('assets/js/pages/lms-assignments-runtime.js?v=20260729-lmsassignfix1');
        expect(assignmentsSource).toContain('function renderWorkspace(courseId)');
        expect(assignmentsSource).toContain('async function createAssignment(courseId)');
        expect(assignmentsSource).toContain('async function submitAssignment(courseId, assignmentId)');
        expect(assignmentsSource).toContain('function deleteAssignment(courseId, assignmentId)');
        expect(assignmentsSource).toContain('function closeLmsAssignmentGradeModal()');
        expect(assignmentsSource).toContain('function saveLmsAssignmentSubmissionGrade(courseId, assignmentId, studentId)');
        expect(assignmentsSource).toContain('function gradeLmsAssignmentSubmission(courseId, assignmentId, studentId)');
        expect(assignmentsSource).toContain('lms-route-card-grid--wide');
        expect(assignmentsSource).toContain('lms-route-divider-top');
        expect(assignmentsSource).toContain('lms-route-card-stack');
        expect(assignmentsSource).toContain('lms-route-copy-prewrap');
        expect(assignmentsSource).toContain('renderLmsStoredFileAttachmentShell(assignment.attachment');
        expect(assignmentsSource).toContain('lms-assignment-card');
        expect(assignmentsSource).toContain('lms-assignment-card-head');
        expect(assignmentsSource).toContain('lms-assignment-rubric-shell');
        expect(assignmentsSource).toContain('lms-assignment-policy-row');
        expect(assignmentsSource).toContain('lms-assignment-student-controls');
        expect(assignmentsSource).toContain('lms-assignment-student-toolbar');
        expect(assignmentsSource).toContain('lms-assignment-student-file-pill');
        expect(assignmentsSource).toContain('lms-assignment-student-actions');
        expect(assignmentsSource).toContain('lms-assignment-student-detail-grid');
        expect(assignmentsSource).toContain('lms-assignment-student-detail-card');
        expect(assignmentsSource).toContain('lms-assignment-student-detail-copy');
        expect(assignmentsSource).toContain('lms-assignment-staff-summary');
        expect(assignmentsSource).toContain('lms-assignment-review-summary-grid');
        expect(assignmentsSource).toContain('lms-assignment-review-summary-card');
        expect(assignmentsSource).toContain('lms-assignment-submission-bar lms-route-actions-mt-10');
        expect(assignmentsSource).toContain('lms-assignment-submission-card');
        expect(assignmentsSource).toContain('lms-assignment-submission-detail-grid');
        expect(assignmentsSource).toContain('lms-assignment-submission-detail-card');
        expect(assignmentsSource).toContain('lms-assignment-submission-detail-copy');
        expect(assignmentsSource).toContain('lms-assignment-submission-actions lms-route-actions-mt-10');
        expect(assignmentsSource).toContain('lms-assignment-feedback-shell');
        expect(assignmentsSource).toContain('lms-assignment-feedback-shell is-empty');
        expect(assignmentsSource).toContain('lms-assignment-submission-file-shell is-empty');
        expect(assignmentsSource).toContain('lms-assignment-review-empty-shell');
        expect(assignmentsSource).toContain('lms-assignment-empty-copy');
        expect(assignmentsSource).toContain('lms-assignment-submission-status-pill is-graded');
        expect(assignmentsSource).toContain('lms-assignment-submission-status-pill is-pending');
        expect(assignmentsSource).toContain('Pending review');
        expect(assignmentsSource).toContain("label: 'Submission file'");
        expect(assignmentsSource).toContain('lms-assignment-attachment-empty-shell');
        expect(assignmentsSource).toContain('lms-assignment-grade-empty-shell');
        expect(assignmentsSource).toContain("overlay.id = 'lms-assignment-grade-modal'");
        expect(assignmentsSource).toContain("overlay.className = 'lms-quiz-board-overlay lms-assignment-grade-overlay lms-glass-dialog-overlay'");
        expect(assignmentsSource).toContain('lms-assignment-grade-summary-grid');
        expect(assignmentsSource).toContain('lms-assignment-grade-summary-card');
        expect(assignmentsSource).toContain('lms-assignment-grade-response-card');
        expect(assignmentsSource).toContain('lms-assignment-grade-editor');
        expect(assignmentsSource).toContain('lms-assignment-grade-status-pill ${submission.score == null ? \'is-pending\' : \'is-graded\'}');
        expect(assignmentsSource).toContain('lms-assignment-grade-actions');
        expect(assignmentsSource).not.toContain('style="margin-bottom:16px;"');
        expect(assignmentsSource).not.toContain('style="padding:16px 20px;"');
        expect(assignmentsSource).not.toContain('style="white-space:pre-wrap;"');
        expect(assignmentsSource).not.toContain('prompt(');
        expect(readSource('assets/css/lux-modals.css')).toContain('lms-glass-dialog-overlay');
        expect(readSource('assets/css/lux-modals.css')).toContain('lms-quiz-board-overlay');
        expect(routeCss).toContain('lms-assignment-review-summary-grid');
        expect(routeCss).toContain('lms-assignment-review-summary-card');
        expect(routeCss).toContain('lms-assignment-student-detail-grid');
        expect(routeCss).toContain('lms-assignment-student-detail-card');
        expect(routeCss).toContain('lms-assignment-student-detail-copy');
        expect(routeCss).toContain('lms-assignment-review-empty-shell');
        expect(routeCss).toContain('lms-assignment-empty-copy');
        expect(routeCss).toContain('lms-assignment-attachment-empty-shell');
        expect(routeCss).toContain('lms-assignment-submission-detail-grid');
        expect(routeCss).toContain('lms-assignment-submission-detail-copy');
        expect(routeCss).toContain('lms-assignment-submission-status-pill.is-pending');
        expect(routeCss).toContain('lms-assignment-submission-status-pill.is-graded');
        expect(assignmentsSource).toContain("lms-assignment-grade-modal");
        expect(routeCss).toContain('lms-assignment-grade-summary-grid');
        expect(routeCss).toContain('lms-assignment-grade-status-pill.is-pending');
        expect(routeCss).toContain('lms-assignment-grade-status-pill.is-graded');
        expect(routeCss).toContain('lms-assignment-grade-actions');
        expect(lmsSource).not.toContain('function renderWorkspace(courseId)');
        expect(lmsSource).not.toContain('async function createAssignment(courseId)');
        expect(lmsSource).not.toContain('async function submitAssignment(courseId, assignmentId)');
        expect(lmsSource).not.toContain('function deleteAssignment(courseId, assignmentId)');
        expect(lmsSource).not.toContain('function closeLmsAssignmentGradeModal()');
        expect(lmsSource).not.toContain('function saveLmsAssignmentSubmissionGrade(courseId, assignmentId, studentId)');
        expect(lmsSource).not.toContain('function gradeLmsAssignmentSubmission(courseId, assignmentId, studentId)');
    });
});
