import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('LMS assignments module split', () => {
    it('moves LMS assignment workspace rendering and submission helpers out of lms.js and into the dedicated module', () => {
        const lmsHtml = readSource('lms.html');
        const lmsSource = readSource('assets/js/pages/lms.js');
        const assignmentsSource = readSource('assets/js/pages/lms-assignments-runtime.js');
        const routeCss = ''; /* purged retired lms-route.css */

        expect(assignmentsSource).toContain('function buildLmsSubmissionDraftKey(resourceKey, assignmentId, userId = getCurrentUserId() || \'student\')');
        expect(assignmentsSource).toContain('window.submitAssignment = window.submitAssignment || submitAssignment');
        expect(readSource('assets/js/pages/lms-classroom-tabs-runtime.js')).toContain('assets/js/pages/lms-assignments-runtime.js?v=20260729-lmsassignfix1');
        expect(assignmentsSource).toContain('function renderWorkspace(courseId)');
        expect(assignmentsSource).toContain('async function createAssignment(courseId)');
        expect(assignmentsSource).toContain('async function submitAssignment(courseId, assignmentId)');
        expect(assignmentsSource).toContain('function deleteAssignment(courseId, assignmentId)');
        expect(assignmentsSource).toContain('function closeLmsAssignmentGradeModal()');
        expect(assignmentsSource).toContain('function saveLmsAssignmentSubmissionGrade(courseId, assignmentId, studentId)');
        expect(assignmentsSource).toContain('function gradeLmsAssignmentSubmission(courseId, assignmentId, studentId)');
        expect(assignmentsSource).toContain('lms-route-card-grid--wide');
        expect(assignmentsSource).toContain('lms-route-divider-top');
        expect(assignmentsSource).toContain('lms-route-card-stack');
        expect(assignmentsSource).toContain('lms-route-copy-prewrap');
        expect(assignmentsSource).toContain('renderLmsStoredFileAttachmentShell(assignment.attachment');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-card-stack lms-assignment-card"');
        expect(assignmentsSource).toContain('class="lms-route-card-head lms-assignment-card-head"');
        expect(assignmentsSource).toContain('class="lms-route-kv lms-assignment-rubric-shell"');
        expect(assignmentsSource).toContain('class="lms-route-inline lms-route-inline-between lms-route-inline-gap-10 lms-route-inline-center lms-assignment-policy-row"');
        expect(assignmentsSource).toContain('class="lms-route-divider-top lms-assignment-student-controls"');
        expect(assignmentsSource).toContain('class="lms-route-inline lms-route-inline-between lms-route-inline-gap-10 lms-route-inline-center lms-assignment-student-toolbar"');
        expect(assignmentsSource).toContain('class="lms-route-pill lms-assignment-student-file-pill"');
        expect(assignmentsSource).toContain('class="lms-route-actions lms-assignment-student-actions"');
        expect(assignmentsSource).toContain('class="lms-route-card-grid lms-assignment-student-detail-grid"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-student-detail-card"');
        expect(assignmentsSource).toContain('class="lms-route-copy lms-route-copy-mt-6 lms-assignment-student-detail-copy"');
        expect(assignmentsSource).toContain('class="lms-route-inline lms-route-inline-between lms-route-inline-gap-12 lms-route-inline-center lms-assignment-staff-summary"');
        expect(assignmentsSource).toContain('class="lms-route-card-grid lms-assignment-review-summary-grid"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-review-summary-card"');
        expect(assignmentsSource).toContain('class="lms-assignment-submission-bar lms-route-actions-mt-10"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-submission-card"');
        expect(assignmentsSource).toContain('class="lms-route-card-grid lms-assignment-submission-detail-grid"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-submission-detail-card"');
        expect(assignmentsSource).toContain('class="lms-route-copy lms-route-copy-mt-6 lms-assignment-submission-detail-copy"');
        expect(assignmentsSource).toContain('class="lms-assignment-submission-actions lms-route-actions-mt-10"');
        expect(assignmentsSource).toContain('class="lms-route-file-shell lms-route-actions-mt-10 lms-assignment-feedback-shell"');
        expect(assignmentsSource).toContain('class="lms-route-file-shell lms-route-actions-mt-10 lms-assignment-feedback-shell is-empty"');
        expect(assignmentsSource).toContain('class="lms-route-file-shell lms-route-actions-mt-10 lms-assignment-submission-file-shell is-empty"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-review-empty-shell"');
        expect(assignmentsSource).toContain('class="lms-route-copy lms-route-copy-mt-6 lms-assignment-empty-copy"');
        expect(assignmentsSource).toContain('class="lms-route-pill lms-assignment-submission-status-pill is-graded"');
        expect(assignmentsSource).toContain('class="lms-route-pill lms-assignment-submission-status-pill is-pending">Pending review</span>');
        expect(assignmentsSource).toContain("label: 'Submission file'");
        expect(assignmentsSource).toContain('class="lms-route-file-shell lms-assignment-attachment-empty-shell"');
        expect(assignmentsSource).toContain('class="lms-route-file-shell lms-route-actions-mt-12 lms-assignment-grade-empty-shell"');
        expect(assignmentsSource).toContain("overlay.id = 'lms-assignment-grade-modal'");
        expect(assignmentsSource).toContain("overlay.className = 'lms-quiz-board-overlay lms-assignment-grade-overlay lms-glass-dialog-overlay'");
        expect(assignmentsSource).toContain('class="lms-route-card-grid lms-assignment-grade-summary-grid"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-grade-summary-card"');
        expect(assignmentsSource).toContain('class="lms-route-card lms-route-panel-compact lms-assignment-grade-response-card"');
        expect(assignmentsSource).toContain('class="lms-route-panel lms-route-panel-compact lms-assignment-grade-editor"');
        expect(assignmentsSource).toContain('class="lms-route-pill lms-assignment-grade-status-pill ${submission.score == null ? \'is-pending\' : \'is-graded\'}"');
        expect(assignmentsSource).toContain('class="lms-route-actions lms-route-actions-mt-16 lms-assignment-grade-actions"');
        expect(assignmentsSource).not.toContain('style="margin-bottom:16px;"');
        expect(assignmentsSource).not.toContain('style="padding:16px 20px;"');
        expect(assignmentsSource).not.toContain('style="white-space:pre-wrap;"');
        expect(assignmentsSource).not.toContain('prompt(');
        expect(routeCss).toContain('.lms-assignment-grade-overlay {');
        expect(routeCss).toContain('.lms-assignment-review-summary-grid {');
        expect(routeCss).toContain('.lms-assignment-review-summary-card,');
        expect(routeCss).toContain('.lms-assignment-student-detail-grid {');
        expect(routeCss).toContain('.lms-assignment-student-detail-card {');
        expect(routeCss).toContain('.lms-assignment-student-detail-copy {');
        expect(routeCss).toContain('.lms-assignment-review-empty-shell,');
        expect(routeCss).toContain('.lms-assignment-empty-copy {');
        expect(routeCss).toContain('.lms-assignment-attachment-empty-shell,');
        expect(routeCss).toContain('.lms-assignment-submission-detail-grid {');
        expect(routeCss).toContain('.lms-assignment-submission-detail-copy {');
        expect(routeCss).toContain('.lms-assignment-submission-status-pill.is-pending {');
        expect(routeCss).toContain('.lms-assignment-submission-status-pill.is-graded {');
        expect(routeCss).toContain('.lms-assignment-grade-modal {');
        expect(routeCss).toContain('.lms-assignment-grade-summary-grid {');
        expect(routeCss).toContain('.lms-assignment-grade-status-pill.is-pending {');
        expect(routeCss).toContain('.lms-assignment-grade-status-pill.is-graded {');
        expect(routeCss).toContain('.lms-assignment-grade-actions {');
        expect(lmsSource).not.toContain('function renderWorkspace(courseId)');
        expect(lmsSource).not.toContain('async function createAssignment(courseId)');
        expect(lmsSource).not.toContain('async function submitAssignment(courseId, assignmentId)');
        expect(lmsSource).not.toContain('function deleteAssignment(courseId, assignmentId)');
        expect(lmsSource).not.toContain('function closeLmsAssignmentGradeModal()');
        expect(lmsSource).not.toContain('function saveLmsAssignmentSubmissionGrade(courseId, assignmentId, studentId)');
        expect(lmsSource).not.toContain('function gradeLmsAssignmentSubmission(courseId, assignmentId, studentId)');
    });
});
