import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('planner legacy delegation regressions', () => {
    it('keeps legacy scheduler and broad-calendar interactions on delegated hooks', () => {
        const plannerSource = readSource('assets/js/pages/planner.js');
        const routeCss = readSource('assets/css/admin-scheduler-route.css');

        expect(plannerSource).toContain('function bindPlannerLegacyDelegates()');
        expect(plannerSource).not.toContain('function ensurePlannerLegacyInteractiveStyles()');
        expect(plannerSource).not.toContain("const style = document.createElement('style');");
        expect(plannerSource).toContain('data-scheduler-open="1"');
        expect(plannerSource).toContain('data-scheduler-edit="1"');
        expect(plannerSource).toContain('data-scheduler-stats="1"');
        expect(plannerSource).toContain('data-scheduler-delete="1"');
        expect(plannerSource).toContain('class="sch-board-shell"');
        expect(plannerSource).toContain('class="sch-board-header"');
        expect(plannerSource).toContain('class="sch-board-timezone"');
        expect(plannerSource).toContain('class="sch-board-day-header${idx === 0 ? \' is-today\' : \'\'}"');
        expect(plannerSource).toContain('class="sch-board-time-slot"');
        expect(plannerSource).toContain('class="scheduler-col sch-board-day-column"');
        expect(plannerSource).toContain('class="sch-board-lane${fIdx < activeFaculties.length - 1 ? \' is-divider\' : \'\'}"');
        expect(plannerSource).toContain('class="grid-slot-interactive sch-grid-slot"');
        expect(plannerSource).toContain('class="calendar-event-card sch-event-card ${eventToneClass}"');
        expect(plannerSource).toContain('function syncPlannerSchedulerEventMetrics(root = document) {');
        expect(plannerSource).toContain('data-sch-top="${topPx}" data-sch-height="${heightPx - 8}"');
        expect(plannerSource).toContain('syncPlannerSchedulerEventMetrics(container);');
        expect(plannerSource).toContain('class="sch-event-draft-badge">DRAFT</div>');
        expect(plannerSource).toContain('class="sch-event-card-title"');
        expect(plannerSource).toContain('class="sch-event-card-meta${si.prof === \'TBD\' ? \' is-missing\' : \'\'}"');
        expect(plannerSource).toContain('class="sch-event-card-room${si.room === \'TBD\' ? \' is-missing\' : \'\'}"');
        expect(plannerSource).toContain('class="fas fa-trash trash-hover sch-event-card-utility sch-event-card-utility--delete"');
        expect(plannerSource).toContain("function getPlannerPaletteToneClass(facultyName)");
        expect(plannerSource).toContain('class="sch-palette-group ${toneClass}"');
        expect(plannerSource).toContain('class="palette-item sch-palette-item ${toneClass}"');
        expect(plannerSource).toContain('class="sch-palette-item-copy"');
        expect(plannerSource).toContain('class="fas fa-plus-circle sch-palette-item-icon"');
        expect(plannerSource).toContain("item.classList.add('is-selected');");
        expect(plannerSource).toContain("function getBroadCalendarEventToneClass(eventRecord = {})");
        expect(plannerSource).toContain('class="lux-calendar-event ${getBroadCalendarEventToneClass(ev)}"');
        expect(plannerSource).not.toContain('class="palette-item" data-admin-planner-palette-subject="${escapeHtml(sub.id)}" data-admin-planner-palette-name="${escapeHtml(sub.name)}" style="background:white;');
        expect(plannerSource).not.toContain("el.style.borderColor = 'var(--kiu-border)'");
        expect(plannerSource).not.toContain("item.style.background = '#f1f8ff'");
        expect(plannerSource).not.toContain('class="lux-calendar-event" style="background:${ev.color || \'#dbeafe\'}; color:${ev.textColor || \'#1e40af\'};"');
        expect(plannerSource).not.toContain('let html = `<div style="display: flex; flex-direction: column; min-height: 800px;');
        expect(plannerSource).not.toContain('class="grid-slot-interactive" style="height: 120px; width: 100%;');
        expect(plannerSource).not.toContain('<div style="position:absolute; top:-6px; right:-6px; background:#a4262c;');
        expect(plannerSource).not.toContain('class="calendar-event-card" data-scheduler-edit="1" data-scheduler-course="${escapeHtml(si.courseId)}" data-scheduler-group="${escapeHtml(si.id)}" style="position: absolute;');
        expect(plannerSource).not.toContain('<div style="font-weight: 700; color: #201f1e; font-size: 11px;');
        expect(plannerSource).not.toContain('style="top: ${topPx}px; height: ${heightPx - 8}px;"');
        expect(routeCss).toContain('.sch-palette-group {');
        expect(routeCss).toContain('.sch-palette-item {');
        expect(routeCss).toContain('.sch-palette-item.is-selected {');
        expect(routeCss).toContain('.sch-palette-empty {');
        expect(routeCss).toContain('.sch-palette-tone-cs {');
        expect(routeCss).toContain('.lux-calendar-event.lux-calendar-event--academic {');
        expect(routeCss).toContain('.lux-calendar-event.lux-calendar-event--deadline {');
        expect(routeCss).toContain('.sch-board-shell {');
        expect(routeCss).toContain('.sch-board-header {');
        expect(routeCss).toContain('.sch-board-time-slot {');
        expect(routeCss).toContain('.sch-board-lane.is-divider {');
        expect(routeCss).toContain('.sch-grid-slot {');
        expect(routeCss).toContain('.sch-event-card {');
        expect(routeCss).toContain('.sch-event-card.is-cs {');
        expect(routeCss).toContain('top: var(--sch-event-top, 0px);');
        expect(routeCss).toContain('height: var(--sch-event-height, 0px);');
        expect(routeCss).toContain('.sch-event-draft-badge {');
        expect(routeCss).toContain('.sch-event-card-utility--delete {');
        expect(routeCss).toContain('.grid-slot-interactive:hover {');
        expect(routeCss).toContain('.calendar-event-card:hover {');
        expect(plannerSource).toContain('data-bc-nav="-1"');
        expect(plannerSource).toContain('data-bc-year="${y}"');
        expect(plannerSource).toContain('data-bc-date="${dateStr}"');
        expect(plannerSource).toContain('data-bc-add="1"');
        expect(plannerSource).not.toContain('onclick="openSchedulerModal(');
        expect(plannerSource).not.toContain('onclick="event.stopPropagation(); openSchedulerEditModal(');
        expect(plannerSource).not.toContain('onclick="event.stopPropagation(); showSlotStats(');
        expect(plannerSource).not.toContain('onclick="event.stopPropagation(); deleteSection(');
        expect(plannerSource).not.toContain('onclick="bcNav(');
        expect(plannerSource).not.toContain('onclick="bcJumpYear(');
        expect(plannerSource).not.toContain('onclick="bcDayClick(');
        expect(plannerSource).not.toContain('onclick="bcAddEvent()');
        expect(plannerSource).not.toContain('onmouseenter="this.style.background=');
        expect(plannerSource).not.toContain("onmouseenter=\"this.style.boxShadow=");
        expect(plannerSource).not.toContain('onmouseleave="this.style.background=');
        expect(plannerSource).not.toContain("onmouseleave=\"this.style.boxShadow=");
        expect(plannerSource).not.toContain('data-study-card-assessment-key');
        expect(plannerSource).not.toContain('study-card-assessment-window');
        expect(plannerSource).not.toContain('data-planner-grade-details');
        expect(plannerSource).toContain("const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];");
        expect(plannerSource).not.toMatch(/Ã|â€”|ï¿½/);
    });
});
