import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('programs route regressions', () => {
    it('keeps programs free of dead social/page-pack imports and polling-based boot waits', () => {
        const html = readSource('programs.html');
        const programsPage = readSource('assets/js/pages/programs-page.js');
        const routeCss = readSource('assets/css/programs-route.css');
        const sharedSurfaceCss = readSource('assets/css/lux-surfaces.css');
        const navigation = readSource('assets/js/features/navigation.js');

        expect(html).not.toContain('assets/js/shared/social-hub.js');
        expect(html).not.toContain('assets/js/shared/social-render.js');
        expect(html).not.toContain('assets/js/shared/social-media.js');
        expect(html).not.toContain('assets/js/shared/messenger.js');
        expect(html).not.toContain('assets/js/pages/gradebook.js');
        expect(html).not.toContain('assets/js/pages/lms.js');
        expect(html).not.toContain('assets/js/pages/planner.js');
        expect(html).not.toContain('assets/js/pages/directories.js');
        expect(html).not.toContain('assets/js/pages/student-registration.js');
        expect(html).not.toContain('assets/js/pages/admin-registration.js');
        expect(html).not.toContain('assets/js/pages/registration.js');
        expect(html).toContain('assets/css/programs-route.css?v=20260530-progglass1');
        expect(html).toContain('assets/js/pages/programs-page.js?v=20260515-programs-page1');
        expect(html).toContain('id="programs-hero-title"');
        expect(html).toContain('id="programs-hero-copy"');
        expect(html).toContain('id="programs-hero-faculty-badge"');
        expect(html).toContain('class="page-hero-badge wave2-chip wave2-chip--hero lux-program-hero-chip"');
        expect(html).toContain('id="student-program-semester-filter"');
        expect(html).toContain('id="student-program-search"');
        expect(html).toContain('id="student-program-search-clear"');
        expect(html).toContain('id="student-program-filter-note"');
        expect(html).toContain('data-programs-search="1"');
        expect(html).toContain('data-programs-semester-filter="1"');
        expect(html).toContain('data-programs-clear-search="1"');
        expect(html).toContain("function ensureProgramsNavigateHooks(){if(typeof window.navigate!=='function')return false;hookProgramsNavigationVisualSync();return true}");
        expect(html).toContain("window.addEventListener('load', ensureProgramsNavigateHooks, {once:true});");
        expect(html).toMatch(
            /if \(String\(pageId \|\| ''\)\.toLowerCase\(\) === 'programs' && !result\?\.navigationSkipped\)/
        );
        expect(html).toContain('scheduleRouteContentRender(renderPrograms)');
        expect(html).not.toContain('window.setTimeout(syncProgramsVisualShell, 80)');
        expect(html).not.toContain('setInterval(function(){if(typeof window.navigate===');
        expect(html).not.toContain('programsNavigationHookTimer');
        expect(html).not.toContain('Boot Curriculum Library view on standalone load');
        expect(programsPage).toContain('window.studentEducationalProgramUiState = window.studentEducationalProgramUiState || {');
        expect(programsPage).toContain('function renderStudentEducationalProgramPage()');
        expect(programsPage).toContain('window.renderStudentEducationalProgramPage = renderStudentEducationalProgramPage;');
        expect(programsPage).toContain('function bindProgramsPageDelegates()');
        expect(programsPage).toContain('function ensureProgramsContentShell(root)');
        expect(programsPage).toContain('function renderProgramsOverviewRegion(context)');
        expect(programsPage).toContain('function renderProgramsModuleRailRegion(context)');
        expect(programsPage).toContain('function renderProgramsSubjectPanelRegion(context)');
        expect(programsPage).toContain('lux-program-shell-section lux-program-shell-section--overview');
        expect(programsPage).toContain('lux-program-shell-section lux-program-shell-section--module-rail');
        expect(programsPage).toContain('lux-program-shell-section lux-program-shell-section--subject-panel');
        expect(programsPage).toContain('class="lux-section-card__body lux-program-shell-body lux-program-shell-body--overview"');
        expect(programsPage).toContain('class="lux-program-metric lux-program-summary-card wave2-summary-card lux-strip-card surface-card"');
        expect(programsPage).toContain('class="lux-program-semester-chip lux-program-semester-timeline__chip');
        expect(programsPage).toContain('class="lux-module-rail lux-program-module-rail"');
        expect(programsPage).toContain('class="lux-module-option lux-program-module-option');
        expect(programsPage).toContain('class="lux-program-section-head lux-program-detail-head"');
        expect(programsPage).toContain('class="lux-program-focus-summary lux-program-detail-summary"');
        expect(programsPage).toContain('class="lux-program-module-facts lux-program-detail-facts"');
        expect(programsPage).toContain('class="lux-program-column-head lux-program-detail-columns"');
        expect(programsPage).toContain('class="lux-program-subject-list lux-program-detail-list"');
        expect(programsPage).toContain('class="lux-subject-row lux-program-subject-card');
        expect(programsPage).toContain('class="lux-empty-state lux-program-empty-state lux-program-empty-state--subjects"');
        expect(programsPage).toContain('class="lux-empty-state lux-program-empty-state lux-program-empty-state--panel"');
        expect(programsPage).toContain('class="lux-empty-state lux-program-empty-state lux-program-empty-state--loading"');
        expect(programsPage).toContain('class="lux-section-copy lux-program-overview-copy"');
        expect(programsPage).toContain('class="lux-program-progress__bar" style="--lux-program-load:');
        expect(programsPage).toContain('class="lux-section-copy lux-program-rail-copy"');
        expect(programsPage).toContain('class="lux-status-pill wave2-chip wave2-chip--pill lux-program-ects-pill"');
        expect(programsPage).toContain('class="lux-module-option__meter-bar" style="--lux-program-module-load:');
        expect(programsPage).toContain('class="lux-program-metric lux-program-summary-card wave2-summary-card lux-strip-card surface-card"');
        expect(programsPage).toContain('class="wave2-summary-label lux-program-summary-label"');
        expect(programsPage).toContain('class="wave2-summary-value lux-program-summary-value"');
        expect(programsPage).toContain('class="wave2-summary-copy lux-program-summary-copy"');
        expect(programsPage).toContain('class="lux-status-pill wave2-chip wave2-chip--pill"');
        expect(programsPage).toContain("contentBox.classList.add('lux-program-stage-host');");
        expect(programsPage).toContain('clearSearchButton.hidden = !preservedSearchQuery;');
        expect(programsPage).not.toContain("contentBox.style.overflowX = 'visible';");
        expect(programsPage).not.toContain("contentBox.style.padding = '24px';");
        expect(programsPage).not.toContain("clearSearchButton.style.display = preservedSearchQuery ? '' : 'none';");
        expect(programsPage).toContain('programs-overview-region');
        expect(programsPage).toContain('programs-module-rail-region');
        expect(programsPage).toContain('programs-subject-panel-region');
        expect(programsPage).toContain('overviewRegion.innerHTML = renderProgramsOverviewRegion(renderContext);');
        expect(programsPage).toContain('moduleRailRegion.innerHTML = renderProgramsModuleRailRegion(renderContext);');
        expect(programsPage).toContain('function renderProgramsSubjectPanelLoadingRegion(context)');
        expect(programsPage).toContain('function scheduleProgramsSubjectPanelRender(context, region)');
        expect(programsPage).toContain('window.requestIdleCallback');
        expect(programsPage).toContain('scheduleProgramsSubjectPanelRender(renderContext, subjectPanelRegion);');
        expect(programsPage).not.toContain('heroMetaEl.innerHTML');
        expect(programsPage).not.toContain('filterShell.innerHTML');
        expect(programsPage).not.toContain('before registration.');
        expect(programsPage).not.toContain('live subject counts from the Curriculum Library.');
        expect(programsPage).toContain('data-programs-semester=');
        expect(programsPage).toContain('data-programs-module-radio=');
        expect(programsPage).not.toContain('onclick=');
        expect(programsPage).not.toContain('oninput=');
        expect(programsPage).not.toContain('onchange=');
        expect(routeCss).toContain('.lux-program-stage-host {');
        expect(routeCss).toContain('.lux-program-shell-section--module-rail');
        expect(routeCss).toContain('.lux-program-shell-body {');
        expect(routeCss).toContain('.lux-program-summary-strip {');
        expect(routeCss).toContain('.lux-program-summary-card {');
        expect(routeCss).not.toContain('.wave2-summary-card {');
        expect(routeCss).toContain('.lux-program-summary-label');
        expect(routeCss).toContain('.lux-program-summary-value');
        expect(routeCss).toContain('.lux-program-summary-copy');
        expect(routeCss).toContain('.lux-program-hero-chip {');
        expect(sharedSurfaceCss).toContain('.wave2-chip--pill {');
        expect(routeCss).not.toContain('.wave2-chip--pill {');
        expect(routeCss).toContain('.lux-program-semester-timeline {');
        expect(routeCss).toContain('.lux-program-module-rail {');
        expect(routeCss).toContain('.lux-program-module-option {');
        expect(routeCss).toContain('.lux-program-detail-head {');
        expect(routeCss).toContain('.lux-program-detail-summary {');
        expect(routeCss).toContain('.lux-program-detail-facts {');
        expect(routeCss).toContain('.lux-program-detail-columns');
        expect(routeCss).toContain('.lux-program-detail-list {');
        expect(routeCss).toContain('.lux-program-subject-card {');
        expect(routeCss).toContain('.lux-program-empty-state--subjects {');
        expect(routeCss).toContain('.lux-program-empty-state--panel');
        expect(routeCss).toContain('.lux-program-overview-copy {');
        expect(routeCss).toContain('.lux-program-progress__bar {');
        expect(routeCss).toContain('.lux-program-rail-copy {');
        expect(routeCss).toContain('.lux-program-ects-pill {');
        expect(navigation).toContain("const STANDALONE_REGISTRATION_RUNTIME_GUARDS = {");
        expect(navigation).toContain("'programs': () => typeof window.renderStudentEducationalProgramPage === 'function'");
    });
});
