import { describe, expect, it } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('social post actions regressions', () => {
    it('keeps feed mutations, dialogs, and comment drafts in the render pipeline', () => {
        const source = readSource('assets/js/pages/social-page.js');
        const feedModule = readSource('assets/js/pages/social-feed.js');
        const runtimeSource = readSource('assets/js/shared/social-runtime-lite.js');
        const appSource = readSource('assets/js/app/app.js');
        const html = readSource('social.html');
        const sw = readSource('service-worker.js');

        expect(html).toMatch(/assets\/js\/pages\/social-page\.js\?v=/);
        expect(html).toMatch(/assets\/js\/shared\/social-runtime-lite\.js\?v=/);

        expect(appSource).toMatch(/assets\/js\/pages\/social-page\.js\?v=/);
        expect(appSource).toMatch(/assets\/js\/shared\/social-runtime-lite\.js\?v=/);

        const interactionsSource = readSource('assets/js/pages/social-page-interactions-runtime.js');
        expect(source).toContain('const postKey = window.postKey');
        expect(interactionsSource).toContain('const buildFeedFingerprint = window.buildFeedFingerprint');
        expect(readSource('assets/js/pages/social-chrome-model.js')).toContain('function postKey(postOrId)');
        expect(readSource('assets/js/pages/social-fingerprint-model.js')).toContain('function buildFeedFingerprint(runtime)');
        expect(source).toContain('function syncCommentDraftFromTarget(target)');
        expect(interactionsSource).toContain('function reactionLabel(reactionType)');
        expect(interactionsSource).toContain('function renderPostReactionMetrics(reactionCounts = {})');
        // Post card markup + reaction/save patches live in social-feed.js.
        expect(source + feedModule).toContain('const hasViewerReaction = Boolean(viewerReaction)');
        expect(source + feedModule).toContain('data-reaction-type="${escape(viewerReaction || \'like\')}"');
        expect(feedModule).toContain('function renderPost(post)');
        expect(feedModule).toContain('function patchPostReactions(postId)');
        expect(source).toContain('window.renderPost !== renderPost');
        expect(source).toContain('window.patchPostReactions !== patchPostReactions');
        const bootSource = readSource('assets/js/pages/social-page-boot-runtime.js');
        const feedRuntimeSource = readSource('assets/js/pages/social-page-feed-runtime.js');
        expect(source + feedModule).not.toContain('fa-heart social-neo-metric-heart');
        expect(bootSource).toContain('async function boot()');
        expect(bootSource).toContain('if (runHydrate) await runHydrate();');
        expect(feedRuntimeSource).toContain('text(dialog?.type || \'\')');
        expect(source).not.toContain('activeDialog()?.kind');
        const forceRenderSource = readSource('assets/js/pages/social-fingerprint-model.js');
        expect(forceRenderSource).toContain('page-open-profile|page-about-more|page-members-open|page-members-filter');
        expect(forceRenderSource).toContain('page-profile-back|page-profile-tab|page-profile-edit-|page-post-type');
        expect(interactionsSource).toContain('isSocialForceRenderReason(reason)');
        expect((source + feedModule)).toContain('\'post-react\'');
        expect((source + feedModule)).toContain('\'post-pin\'');
        expect((source + feedModule)).toContain("renderSocialPageNow('post-react')");
        expect((source + feedModule)).toContain("renderSocialPageNow('post-pin')");
        expect((source + feedModule)).toContain('patchCommentReactions(updatedPost, reactCommentId)');
        expect(interactionsSource).toContain('delete shell.center.__kiuLastMarkup');
        expect(runtimeSource).toContain('pendingRenderReason');
        const contentRuntimeSource = readSource('assets/js/shared/social-lite-content-runtime.js');
        expect(runtimeSource).toContain('function mergeFeedPost(post)');
        expect(runtimeSource).toContain('function invalidateSocialFeedRenderCache()');
        expect(runtimeSource).toContain('function isFeedRenderReason(reason = \'\')');
        expect(contentRuntimeSource).toContain('mergeFeedPost(updatedPost)');
        expect(runtimeSource).toContain('function applyOptimisticPostReaction(post, userId, reactionType = \'like\')');
        const reactToPostBlock = runtimeSource.match(/async function reactToPost[\s\S]*?(?=\n    async function )/)?.[0] || '';
        const reactToCommentBlock = runtimeSource.match(/async function reactToComment[\s\S]*?(?=\n    async function )/)?.[0] || '';
        expect(reactToPostBlock).not.toContain('await refreshFeed(true)');
        expect(reactToCommentBlock).not.toContain('await refreshFeed(true)');
        expect(interactionsSource).toContain("reason === 'dialog-close' || /^dialog-/.test(reason)");
        expect(bootSource).toContain('boundHost = host');
        expect((source + feedModule)).toContain('syncCommentDraftFromTarget(commentInput)');
        expect((source + feedModule)).toContain('const postId = postKey(commentForm.getAttribute(\'data-post-id\'))');
        expect((source + feedModule)).toContain('const postId = postKey(form.getAttribute(\'data-post-id\'))');
        expect((source + feedModule)).toContain('const bodySource = event.target?.name === \'commentBody\' ? event.target : commentInput');
        expect(readSource('assets/js/pages/social-feed.js')).toContain('const dialogCommentDraft = String(runtime.ui?.commentDraftByPost?.[dialogNormalizedPostId] || \'\')');
        expect(interactionsSource).toContain('CSS.escape(postId)');
        expect((source + feedModule)).toContain('data-action="post-compose-open"');
        expect((source + feedModule)).toContain('trigger.closest(\'.social-neo-composer-card\')');
        expect((source + feedModule)).toContain('composerTextarea?.value || runtime.ui?.composerText');
        expect((source + feedModule)).toContain('form[data-form="post-compose"]');
        expect((source + feedModule)).toContain('lux-glass-dialog-card--comments lux-glass-dialog-card lux-glass-dialog-card--social-glass lux-studio-panel sns-comments-dialog');
        expect((source + feedModule)).toContain('social-neo-surveys-hero-head');
        expect((source + feedModule)).toContain('social-neo-dialog-comment-stats');
        expect((source + feedModule)).toContain('lux-strip-card surface-card lux-soft-chrome home-hover-chip');
        expect((source + feedModule)).toContain('lux-glass-dialog-comment-preview lux-soft-chrome home-hover-chip');
        expect((source + feedModule)).toContain('lux-glass-dialog-comment-compose sns-comment-compose lux-soft-chrome home-hover-chip');
        expect((source + feedModule)).toContain('lux-glass-dialog-comment-scroll');
        expect((source + feedModule)).toContain('lux-glass-dialog-comment-preview');
        expect((source + feedModule)).toContain('lux-glass-dialog-comment-thread" id="lux-glass-dialog-comment-thread');
        expect((source + feedModule)).toContain('lux-glass-dialog-comment-compose sns-comment-compose');
        expect((source + feedModule)).not.toContain('lux-glass-dialog-body--comments lux-studio-body');
        expect((source + feedModule)).not.toContain('lux-glass-dialog-comment-thread lux-studio-section');
        expect((source + feedModule)).not.toContain('lux-glass-dialog-comment-preview lux-studio-section');
        expect(html).toContain('assets/css/lux-studio.css?v=');
        expect(readSource('assets/css/lux-modals.css')).toContain('width: min(1180px, calc(100vw - 32px))');
        expect(readSource('assets/css/lux-modals.css')).toContain('height: min(94dvh, 980px)');
        expect(readSource('assets/css/lux-modals.css')).toContain('.lux-glass-dialog-card--comments.lux-studio-panel > .sns-comment-compose');
        expect(readSource('assets/css/lux-modals.css')).not.toContain('.sns-comment-dialog-actions');
        expect(readSource('assets/css/lux-modals.css')).not.toContain('.sns-comment-chip-btn');
        expect((source + feedModule)).not.toContain('lux-glass-dialog-card--comments sn-mat-modal');
        expect(readSource('assets/css/lux-modals.css')).toContain('.lux-glass-dialog-card--comments.lux-studio-panel');
        expect(readSource('assets/css/lux-studio.css')).toContain('#social-neo-overlay-portal .lux-glass-dialog-card--comments');
        const commentsRuntime = readSource('assets/js/pages/social-feed-comments-runtime.js');
        expect(commentsRuntime).not.toContain('sns-comment-dialog-actions');
        expect(commentsRuntime).not.toContain('sns-comment-chip-btn');
        expect(commentsRuntime).toContain('lux-secondary-btn lux-secondary-btn-sm');
        expect(commentsRuntime).not.toMatch(/lux-secondary-btn-sm lux-secondary-btn/);
        expect(commentsRuntime).toContain('lux-primary-btn');
        expect(commentsRuntime).toContain('social-neo-comment-reactions');
        expect(commentsRuntime).toContain("renderCommentReactionButtons(fresh, postKey(updatedPost), 'dialog')");
        expect(commentsRuntime).toContain('lux-soft-chrome home-hover-chip sns-comment-dialog-bubble');
        expect(commentsRuntime).toContain("const dialogShellClass = context === 'dialog' ? ' lux-soft-chrome home-hover-chip' : ''");
        expect(commentsRuntime).toContain('.social-neo-dialog-comment-stats article:nth-child(2) strong');
        expect(feedModule).toContain("openDialog('comment-delete', { postId: delPostId, commentId: delCommentId })");
        expect(feedModule).not.toContain('isCommentDialog()) {\n                return withBusy(() => deleteCommentInline');
        expect(feedModule).toContain('social-comments-dialog-stack');
        expect(feedModule).toContain('FEED_OWNED_ACTION_DIALOG_CARD_CLASS');
        expect(feedModule).toContain('data-form="dialog-post-edit" data-action="noop" data-lux-transparency-exempt="1"');
        expect(feedModule).toContain('lux-glass-dialog-card--social-glass sn-mat-modal');
        expect(feedModule).toContain('lux-glass-dialog-card--comment-delete lux-glass-dialog-card lux-glass-dialog-card--social-glass');
        expect(readSource('assets/css/lux-modals.css')).toContain('.lux-glass-dialog-card--social-glass.sn-mat-modal[data-form^="dialog-"]');
        expect(feedModule).not.toContain('sn-mat-modal lux-studio-panel');
        expect(readSource('assets/css/lux-modals.css')).toContain('.sns-comment-dialog-bubble');
        expect(readSource('assets/css/lux-modals.css')).not.toMatch(/\.sns-comment-dialog-bubble\s*\{[^}]*background:/);
        expect(readSource('assets/css/lux-fouc-ht.css')).toContain('#social-neo-overlay-portal .lux-glass-dialog-card--comments');
        expect(readSource('assets/css/lux-fouc-ht.css')).not.toContain('.lux-glass-dialog-card--comments:has(.home-hover-chip:hover)');
        expect(readSource('assets/css/lux-modals.css')).toContain('.lux-glass-dialog-card--comments.lux-glass-dialog-card--social-glass');
        expect(readSource('assets/css/lux-modals.css')).toContain('.lux-glass-dialog-backdrop--comment-delete');
        expect(feedModule).not.toContain('isCommentDialog()) {\n                return withBusy(() => deleteCommentInline');
        expect(source).toContain('window.relayoutCommentTrunks || window.__kiuRelayoutCommentTrunks');
        expect(readSource('assets/js/pages/social-overlay-chrome.js')).toContain('requestAnimationFrame(() => relayoutCommentTrunks())');
        expect(source).not.toMatch(/function renderPost\(post\)[\s\S]*function renderPost\(post\)/);

        expect(sw).toContain('function isSocialRuntimeScriptRequest(url, request)');
        expect(sw).toContain('function handleSocialRuntimeScriptRequest(request, event)');
    });
});
