import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
  return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('social mobile runtime regressions', () => {
  it('uses runtime events instead of polling for mobile nav readiness', () => {
    const source = readSource('assets/js/pages/social-mobile.js');

    expect(source).toContain("const SOCIAL_RUNTIME_EVENT = 'kiu:social-runtime-update';");
    expect(source).toContain('window.addEventListener(SOCIAL_RUNTIME_EVENT, handleSocialRuntimeEvent);');
    expect(source).toContain("window.addEventListener('load', ensureNavigateHooks, { once: true });");
    expect(source).toContain("if (typeof window.resolvePortalRouteUrl === 'function') {");
    expect(source).not.toContain('setInterval(');
    expect(source).not.toContain('waitForNavigate');
  });

  it('keeps the social mobile shell on hidden-based visibility ownership instead of inline display stubs', () => {
    const html = readSource('social.html');
    const source = readSource('assets/js/pages/social-mobile.js');

    expect(html).toContain('<nav id="mobile-bottom-nav" aria-label="Mobile navigation" hidden>');
    expect(html).toContain('<em class="mob-badge" id="mob-badge-inbox" hidden>0</em>');
    expect(html).toContain('<div id="mobile-action-sheet" class="mob-sheet" hidden role="dialog"');
    expect(html).not.toContain('style="display:none;"');
    expect(source).toContain('function setElementShown(element, shown, displayValue = \'\') {');
    expect(source).toContain('badge.hidden = total <= 0;');
    expect(source).toContain('if (isElementShown(sheet)) {');
    expect(source).toContain('adminSwitch.hidden = ![\'admin\', \'student_service\', \'professor\', \'ta\'].includes(role);');
    expect(source).toContain('setElementShown(nav, isMobileViewport());');
  });

  it('forces a rerender when deferred social panel modules finish loading', () => {
    const source = readSource('assets/js/pages/social-page.js');
    const css = readSource('assets/css/social-rebuild.css');

    expect(source).toContain("function queueDeferredModuleRender(reason) {");
    expect(source).toContain('if (host) {');
    expect(source).toContain("host.__kiuLastRenderSignature = '';");
    expect(source).toContain('host.__kiuForceCenterOnly = true;');
    expect(source).toContain("ensureSocialMessagesModule().then(() => queueDeferredModuleRender('messages-module')).catch(() => null);");
    expect(source).toContain('const forceRender = /^(feed|feed-error|dialog-|comment-|post-save|post-pin|post-react|post-submit)/.test(reason)');
    expect(source).toContain("if (!forceRender && reason !== 'boot' && !/-module$/.test(reason) && host.__kiuLastRenderSignature === renderSignature) {");
    expect(source).toContain('social-neo-inline-gap-4');
    expect(source).toContain('social-neo-inline-items-start');
    expect(source).toContain('social-neo-flex-spacer');
    expect(source).toContain('social-neo-reply-target');
    expect(source).toContain('social-neo-composer-textarea');
    expect(source).toContain('social-project-task-card-head');
    expect(source).toContain('social-project-task-actions');
    expect(source).toContain('social-project-deliverable-card');
    expect(source).toContain('social-project-meeting-card');
    expect(source).toContain('social-project-checkin-card');
    expect(source).toContain('social-project-chat-launch');
    expect(source).toContain('social-project-detail-top');
    expect(source).toContain('social-neo-group-card-header');
    expect(source).toContain('social-neo-page-card-header');
    expect(source).toContain('social-neo-event-category-pill');
    expect(source).toContain('social-neo-person-start-gap-12');
    expect(source).toContain('social-neo-shell-nav-icon" data-panel-tone=');
    expect(source).toContain('social-neo-mobile-tab-icon" data-panel-tone=');
    expect(source).toContain('social-neo-shell-drawer-profile');
    expect(source).toContain('social-neo-shell-drawer-profile-card');
    expect(source).toContain('social-neo-shell-drawer-profile-chip');
    expect(source).toContain('social-neo-shell-drawer-profile-copy');
    expect(source).toContain('social-neo-shell-drawer-profile-name');
    expect(source).toContain('social-neo-shell-drawer-profile-subtitle');
    expect(source).toContain('social-neo-shell-drawer-actions');
    expect(source).toContain('social-neo-shell-drawer-action-btn');
    expect(source).toContain('social-neo-shell-drawer-nav');
    expect(source).toContain('social-neo-shell-drawer-nav-btn');
    expect(source).toContain('social-neo-shell-drawer-nav-main');
    expect(source).toContain('social-neo-shell-drawer-nav-icon');
    expect(source).toContain('social-neo-shell-drawer-nav-copy');
    expect(source).toContain('social-neo-shell-drawer-nav-title');
    expect(source).toContain('social-neo-shell-drawer-nav-helper');
    expect(source).toContain('social-neo-shell-drawer-nav-count');
    expect(source).toContain('social-neo-topbar-title');
    expect(source).toContain('social-neo-topbar-description');
    expect(source).toContain('social-neo-topbar-pills');
    expect(source).toContain('social-neo-topbar-pill');
    expect(source).toContain('social-neo-topbar-pill-value');
    expect(source).toContain('social-neo-topbar-pill-label');
    expect(source).toContain('social-neo-topbar-tabs');
    expect(source).toContain('social-neo-topbar-tab');
    expect(source).toContain('social-neo-feed-story-card');
    expect(source).toContain('social-neo-feed-story-strip');
    expect(source).toContain('social-neo-feed-story-item');
    expect(source).toContain('social-neo-feed-story-ring');
    expect(source).toContain('social-neo-feed-story-label');
    expect(source).toContain('social-neo-feed-filter-card');
    expect(source).toContain('social-neo-feed-filter-head');
    expect(source).toContain('social-neo-feed-filter-copy');
    expect(source).toContain('social-neo-feed-filter-title');
    expect(source).toContain('social-neo-feed-filter-description');
    expect(source).toContain('social-neo-feed-filter-refresh');
    expect(source).toContain('social-neo-feed-filter-scope-field');
    expect(source).toContain('social-neo-feed-filter-scope-select');
    expect(source).toContain('social-neo-feed-filter-stats');
    expect(source).toContain('social-neo-feed-filter-stat');
    expect(source).toContain('social-neo-feed-filter-stat-value');
    expect(source).toContain('social-neo-feed-filter-stat-label');
    expect(source).toContain('social-neo-rail-card');
    expect(source).toContain('social-neo-rail-head');
    expect(source).toContain('social-neo-rail-head-copy');
    expect(source).toContain('social-neo-rail-title');
    expect(source).toContain('social-neo-rail-item');
    expect(source).toContain('social-neo-rail-item-copy');
    expect(source).toContain('social-neo-rail-item-title');
    expect(source).toContain('social-neo-rail-item-meta');
    expect(source).toContain('social-neo-rail-item-action');
    expect(source).toContain('social-neo-rail-directory-item');
    expect(source).toContain('social-neo-rail-person');
    expect(source).toContain('social-neo-rail-person-copy');
    expect(source).toContain('social-neo-rail-person-name');
    expect(source).toContain('social-neo-rail-person-meta');
    expect(source).toContain('social-neo-rail-person-action');
    expect(source).toContain('social-neo-rail-overview-stats');
    expect(source).toContain('social-neo-rail-overview-stat');
    expect(source).toContain('social-neo-rail-overview-value');
    expect(source).toContain('social-neo-rail-overview-label');
    expect(source).toContain('social-neo-rail-call-card');
    expect(source).toContain('social-neo-rail-call-actions');
    expect(source).toContain('social-neo-rail-call-open');
    expect(source).toContain('social-neo-rail-call-end');
    expect(source).toContain('social-neo-rail-empty');
    expect(source).toContain('social-neo-dialog-head');
    expect(source).toContain('social-neo-dialog-heading');
    expect(source).toContain('social-neo-dialog-title');
    expect(source).toContain('social-neo-dialog-subtitle');
    expect(source).toContain('social-neo-dialog-close-btn');
    expect(source).toContain('social-neo-dialog-actions');
    expect(source).toContain('social-neo-dialog-cancel-btn');
    expect(source).toContain('social-neo-dialog-submit-btn');
    expect(source).toContain('social-neo-dialog-preview-title');
    expect(source).toContain('social-neo-dialog-checkbox-line');
    expect(source).toContain('social-neo-dialog-checkbox-copy');
    expect(source).toContain('aria-pressed="');
    expect(source).toContain('social-neo-shell-topbar-action-btn');
    expect(source).toContain('social-neo-shell-profile-name');
    expect(source).toContain('social-neo-shell-profile-subtitle');
    expect(source).toContain('social-neo-shell-nav-title');
    expect(source).toContain('social-neo-shell-nav-helper');
    expect(source).toContain('social-neo-shell-nav-count-label');
    expect(source).toContain('social-neo-mobile-tab-label');
    expect(source).toContain('social-neo-mobile-tab-count');
    expect(source).toContain('social-neo-post-author-copy');
    expect(source).toContain('social-neo-post-author-name');
    expect(source).toContain('social-neo-post-author-meta');
    expect(source).toContain('social-neo-post-head-actions');
    expect(source).toContain('social-neo-post-scope-badge');
    expect(source).toContain('social-neo-post-page-label');
    expect(source).toContain('social-neo-post-pinned-pill');
    expect(source).toContain('social-neo-post-head-action-btn');
    expect(source).toContain('social-neo-post-metrics');
    expect(source).toContain('social-neo-post-metric');
    expect(source).toContain('social-neo-post-action-row');
    expect(source).toContain('social-neo-post-action-btn');
    expect(source).toContain('social-neo-post-reaction-btn');
    expect(source).toContain('social-neo-post-save-btn');
    expect(source).toContain('social-neo-composer-scope-field');
    expect(source).toContain('social-neo-composer-scope-label');
    expect(source).toContain('social-neo-composer-scope-select');
    expect(source).toContain('social-neo-composer-audience-field');
    expect(source).toContain('social-neo-composer-audience-label');
    expect(source).toContain('social-neo-composer-audience-select');
    expect(source).toContain('social-neo-composer-attach-btn');
    expect(source).toContain('social-neo-composer-story-btn');
    expect(source).toContain('social-neo-composer-event-btn');
    expect(source).toContain('social-neo-composer-submit-btn');
    expect(source).toContain('social-neo-story-header-copy');
    expect(source).toContain('social-neo-story-composer-title');
    expect(source).toContain('social-neo-story-upload-shell');
    expect(source).toContain('social-neo-story-composer-actions');
    expect(source).toContain('social-neo-story-composer-cancel-btn');
    expect(source).toContain('social-neo-story-composer-submit-btn');
    expect(source).toContain('social-neo-rail-overview-label');
    expect(source).toContain('social-neo-rail-call-copy');
    expect(source).toContain('social-neo-rail-call-title');
    expect(source).toContain('social-neo-rail-call-status');
    expect(source).toContain('social-neo-rail-call-open-btn');
    expect(source).toContain('social-neo-rail-call-end-btn');
    expect(source).toContain('social-neo-inline-between-gap-8-wrap');
    expect(source).toContain('social-neo-muted-mt-8');
    expect(source).toContain('social-neo-btn-pointer');
    expect(source).toContain('social-neo-event-category-pill is-');
    expect(source).toContain('social-neo-entity-card social-neo-entity-card--study');
    expect(source).toContain('social-neo-pill-icon');
    expect(source).toContain('data-project-tone="');
    expect(source).toContain('social-neo-comment-depth-');
    expect(source).toContain('social-neo-btn-pointer');
    expect(source).toContain('social-neo-empty-left');
    expect(source).not.toContain('style="padding:12px 16px !important"');
    expect(source).not.toContain('style="background:${panelColors[panel.id]');
    expect(source).not.toContain('style="--tab-color:');
    expect(source).not.toContain('style="background:linear-gradient(135deg,rgba(var(--sn-accent-rgb),.10),transparent 60%),var(--sn-bg) !important"');
    expect(source).not.toContain('style="--event-accent:');
    expect(source).not.toContain('style="--project-accent:');
    expect(source).not.toContain('style="margin-left:');
    expect(source).not.toContain('style="border-left:3px solid #8b5cf6"');
    expect(source).not.toContain('style="font-size:8px"');
    expect(source).not.toContain('style="background:linear-gradient(135deg,rgba(16,185,129,.15),rgba(16,185,129,.03))"');
    expect(source).not.toContain('style="margin-top:8px"');
    expect(source).not.toContain('style="justify-content:space-between;gap:8px;flex-wrap:wrap"');
    expect(source).not.toContain('style="cursor:pointer"');
    expect(css).toContain('.social-neo-inline-gap-4');
    expect(css).toContain('.social-neo-inline-between-gap-8-wrap');
    expect(css).toContain('.social-neo-inline-items-start');
    expect(css).toContain('.social-neo-flex-spacer');
    expect(css).toContain('.social-neo-reply-target');
    expect(css).toContain('.social-neo-composer-textarea');
    expect(css).toContain('.social-project-task-card-head');
    expect(css).toContain('.social-project-task-actions');
    expect(css).toContain('.social-project-deliverable-card');
    expect(css).toContain('.social-project-meeting-card');
    expect(css).toContain('/* Theme normalization: keep Social on the active luxury palette instead of panel-specific blue/purple/green/orange overrides. */');
    expect(css).toContain('/* Final Social theme lock: this must remain after every route section. */');
    expect(css).toContain('--sn-blue-rgb: var(--lux-accent-rgb, 200, 130, 42);');
    expect(css).toContain('body.lux-route-social .social-neo-shell-nav-icon,');
    expect(css).toContain('body.lux-route-social .social-project-metric-card,');
    expect(css).toContain('body.lux-route-social .public-social-page-card.is-active {');
    expect(css).toContain('background: rgba(var(--lux-accent-rgb), .08) !important;');
    expect(css).toContain('.social-project-checkin-card');
    expect(css).toContain('.social-project-chat-launch');
    expect(css).toContain('.social-project-detail-top');
    expect(css).toContain('.social-neo-event-category-pill.is-university');
    expect(css).toContain('.social-neo-section-card--official');
    expect(css).toContain('.social-neo-empty-left');
    expect(css).toContain('.social-neo-muted-mt-8');
    expect(css).toContain('.social-neo-event-feature--career');
    expect(css).toContain('.social-neo-entity-card--study');
    expect(css).toContain('.social-neo-pill-icon');
    expect(css).toContain(".social-project-metric-card[data-project-tone='orange']");
    expect(css).toContain(".social-project-ring-card[data-project-tone='teal']");
    expect(css).toContain('.social-neo-comment.is-reply.social-neo-comment-depth-1');
    expect(css).toContain('.social-neo-comment.is-reply.social-neo-comment-depth-3');
    expect(css).toContain(".social-neo-shell-nav-icon[data-panel-tone='feed']");
    expect(css).toContain(".social-neo-mobile-tab-icon[data-panel-tone='messages']");
    expect(css).toContain(".social-neo-side-icon[data-panel-tone='alerts']");
    expect(css).toContain('.social-neo-shell-drawer-profile-card');
    expect(css).toContain('.social-neo-shell-drawer-profile-chip');
    expect(css).toContain('.social-neo-shell-drawer-profile-copy');
    expect(css).toContain('.social-neo-shell-drawer-profile-name');
    expect(css).toContain('.social-neo-shell-drawer-profile-subtitle');
    expect(css).toContain('.social-neo-shell-drawer-actions');
    expect(css).toContain('.social-neo-shell-drawer-action-btn');
    expect(css).toContain('.social-neo-shell-drawer-nav');
    expect(css).toContain('.social-neo-shell-drawer-nav-btn');
    expect(css).toContain('.social-neo-shell-drawer-nav-main');
    expect(css).toContain('.social-neo-shell-drawer-nav-icon');
    expect(css).toContain('.social-neo-shell-drawer-nav-copy');
    expect(css).toContain('.social-neo-shell-drawer-nav-title');
    expect(css).toContain('.social-neo-shell-drawer-nav-helper');
    expect(css).toContain('.social-neo-shell-drawer-nav-count');
    expect(css).toContain('.social-neo-topbar-title');
    expect(css).toContain('.social-neo-topbar-description');
    expect(css).toContain('.social-neo-topbar-pills');
    expect(css).toContain('.social-neo-topbar-pill');
    expect(css).toContain('.social-neo-topbar-pill-value');
    expect(css).toContain('.social-neo-topbar-pill-label');
    expect(css).toContain('.social-neo-topbar-tabs');
    expect(css).toContain('.social-neo-topbar-tab');
    expect(css).toContain('.social-neo-feed-story-card');
    expect(css).toContain('.social-neo-feed-story-strip');
    expect(css).toContain('.social-neo-feed-story-item');
    expect(css).toContain('.social-neo-feed-story-ring');
    expect(css).toContain('.social-neo-feed-story-label');
    expect(css).toContain('.social-neo-feed-filter-copy');
    expect(css).toContain('.social-neo-feed-filter-title');
    expect(css).toContain('.social-neo-feed-filter-description');
    expect(css).toContain('.social-neo-feed-filter-stat');
    expect(css).toContain('.social-neo-feed-filter-stat-value');
    expect(css).toContain('.social-neo-rail-card');
    expect(css).toContain('.social-neo-rail-head');
    expect(css).toContain('.social-neo-rail-head-copy');
    expect(css).toContain('.social-neo-rail-title');
    expect(css).toContain('.social-neo-rail-item-copy');
    expect(css).toContain('.social-neo-rail-item-title');
    expect(css).toContain('.social-neo-rail-item-meta');
    expect(css).toContain('.social-neo-rail-item-action');
    expect(css).toContain('.social-neo-rail-person');
    expect(css).toContain('.social-neo-rail-person-copy');
    expect(css).toContain('.social-neo-rail-person-name');
    expect(css).toContain('.social-neo-rail-person-meta');
    expect(css).toContain('.social-neo-rail-person-action');
    expect(css).toContain('.social-neo-rail-overview-stat');
    expect(css).toContain('.social-neo-rail-overview-value');
    expect(css).toContain('.social-neo-rail-call-actions');
    expect(css).toContain('.social-neo-rail-call-open');
    expect(css).toContain('.social-neo-rail-call-end');
    expect(css).toContain('.social-neo-rail-empty');
    expect(css).toContain('.social-neo-dialog-head');
    expect(css).toContain('.social-neo-dialog-heading');
    expect(css).toContain('.social-neo-dialog-title');
    expect(css).toContain('.social-neo-dialog-subtitle');
    expect(css).toContain('.social-neo-dialog-close-btn');
    expect(css).toContain('.social-neo-dialog-actions');
    expect(css).toContain('.social-neo-dialog-cancel-btn');
    expect(css).toContain('.social-neo-dialog-submit-btn');
    expect(css).toContain('.social-neo-dialog-preview-title');
    expect(css).toContain('.social-neo-dialog-checkbox-line');
    expect(css).toContain('.social-neo-dialog-checkbox-copy');
    expect(css).toContain('.social-neo-shell-topbar-action-btn');
    expect(css).toContain('.social-neo-shell-profile-name');
    expect(css).toContain('.social-neo-shell-profile-subtitle');
    expect(css).toContain('.social-neo-shell-nav-title');
    expect(css).toContain('.social-neo-shell-nav-helper');
    expect(css).toContain('.social-neo-shell-nav-count-label');
    expect(css).toContain('.social-neo-mobile-tab-label');
    expect(css).toContain('.social-neo-mobile-tab-count');
    expect(css).toContain('.social-neo-post-author-copy');
    expect(css).toContain('.social-neo-post-author-name');
    expect(css).toContain('.social-neo-post-author-meta');
    expect(css).toContain('.social-neo-post-head-actions');
    expect(css).toContain('.social-neo-post-scope-badge');
    expect(css).toContain('.social-neo-post-page-label');
    expect(css).toContain('.social-neo-post-pinned-pill');
    expect(css).toContain('.social-neo-post-head-action-btn');
    expect(css).toContain('.social-neo-post-metrics');
    expect(css).toContain('.social-neo-post-metric');
    expect(css).toContain('.social-neo-post-action-row');
    expect(css).toContain('.social-neo-post-action-btn');
    expect(css).toContain('.social-neo-post-reaction-btn');
    expect(css).toContain('.social-neo-post-save-btn');
    expect(css).toContain('.social-neo-composer-scope-field');
    expect(css).toContain('.social-neo-composer-scope-label');
    expect(css).toContain('.social-neo-composer-scope-select');
    expect(css).toContain('.social-neo-composer-audience-field');
    expect(css).toContain('.social-neo-composer-audience-label');
    expect(css).toContain('.social-neo-composer-audience-select');
    expect(css).toContain('.social-neo-composer-attach-btn');
    expect(css).toContain('.social-neo-composer-story-btn');
    expect(css).toContain('.social-neo-composer-event-btn');
    expect(css).toContain('.social-neo-composer-submit-btn');
    expect(css).toContain('.social-neo-story-header-copy');
    expect(css).toContain('.social-neo-story-composer-title');
    expect(css).toContain('.social-neo-story-upload-shell');
    expect(css).toContain('.social-neo-story-composer-actions');
    expect(css).toContain('.social-neo-story-composer-cancel-btn');
    expect(css).toContain('.social-neo-story-composer-submit-btn');
    expect(css).toContain('.social-neo-rail-overview-label');
    expect(css).toContain('.social-neo-rail-call-copy');
    expect(css).toContain('.social-neo-rail-call-title');
    expect(css).toContain('.social-neo-rail-call-status');
    expect(css).toContain('.social-neo-rail-call-open-btn');
    expect(css).toContain('.social-neo-rail-call-end-btn');
  });

  it('keeps the social events composer and identity in the render signature so event controls refresh', () => {
    const source = readSource('assets/js/pages/social-page.js');

    expect(source).toContain("text(currentUser()?.role || 'student')");
    expect(source).toContain('text(currentUserId() || \'\')');
    expect(source).toContain("text(typeof currentFacultyCode === 'function' ? currentFacultyCode() : '')");
    expect(source).toContain("text(ui.eventsComposerSection || '')");
    expect(source).toContain("text(ui.activeScopeType || '')");
    expect(source).toContain("text(ui.activeScopeId || '')");
    expect(source).toContain("text(ui.eventScope || '')");
    expect(source).toContain('Boolean(ui.eventIsOnline)');
    expect(source).toContain("text(ui.eventImageFile?.name || '')");
  });
});
