import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readAsset(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf-8');
}

describe('Student Service split workspace regressions', () => {
    it('persists and restores the selected top-level lane', () => {
        const source = readAsset('assets/js/pages/student-service.js');

        expect(source).toContain("const STUDENT_SERVICE_LANES = ['service', 'qa'];");
        expect(source).toContain("const STUDENT_SERVICE_UI_PREFS_KEY = 'KIU_STUDENT_SERVICE_UI_PREFS';");
        expect(source).toContain('serviceLane: readStudentServiceStoredLane(key)');
        expect(source).toContain('qaComposerExpanded: false');
        expect(source).toContain('function setStudentServiceLane(lane, rerender = true)');
        expect(source).toContain('function clearStudentServiceLaneChoice()');
        expect(source).toContain('writeStudentServiceStoredLane(getStudentServiceLane());');
    });

    it('renders a social-style Q&A feed inside the split workspace instead of the old split-pane workbench', () => {
        const source = readAsset('assets/js/pages/student-service.js');
        const css = readAsset('assets/css/student-service-route.css');
        const mobileCss = readAsset('assets/css/mobile-responsive.css');

        expect(source).toContain('function renderStudentServiceLaneChooser(');
        expect(source).toContain('function renderStudentServiceLaneSwitcher(');
        expect(source).toContain('student-service-hero-action-cluster');
        expect(source).toContain('student-service-hero-action--primary');
        expect(source).toContain('student-service-hero-action--secondary');
        expect(source).toContain('student-service-hero-shell');
        expect(source).toContain('student-service-hero-main-shell');
        expect(source).toContain('student-service-hero-kicker');
        expect(source).toContain('student-service-hero-title');
        expect(source).toContain('student-service-hero-copy');
        expect(source).toContain('student-service-hero-aside-shell');
        expect(source).toContain('student-service-hero-meta');
        expect(source).toContain('student-service-hero-badge--role');
        expect(source).toContain('student-service-hero-badge--lane');
        expect(source).toContain('student-service-hero-badge--knowledge');
        expect(source).toContain('student-service-hero-aside-head');
        expect(source).toContain('student-service-hero-aside-stat-label');
        expect(source).toContain('student-service-hero-aside-stat-value');
        expect(source).toContain('student-service-summary-section');
        expect(source).toContain('student-service-summary-card--signal-a');
        expect(source).toContain('student-service-summary-card--signal-b');
        expect(source).toContain('student-service-summary-card--signal-c');
        expect(source).toContain('student-service-workflow-section');
        expect(source).toContain('student-service-workflow-step-title');
        expect(source).toContain('student-service-workflow-step-description');
        expect(source).toContain('student-service-qa-composer-prompt-title');
        expect(source).toContain('student-service-qa-composer-prompt-copy');
        expect(source).toContain('student-service-qa-compose-form');
        expect(source).toContain('student-service-qa-mode-switch');
        expect(source).toContain('student-service-qa-mode-btn');
        expect(source).toContain('student-service-qa-field-row');
        expect(source).toContain('student-service-qa-anonymous-toggle');
        expect(source).toContain('student-service-qa-similar-title');
        expect(source).toContain('student-service-qa-compose-actions');
        expect(source).toContain('student-service-qa-card-author-name');
        expect(source).toContain('student-service-qa-card-author-date');
        expect(source).toContain('student-service-qa-card-stat');
        expect(source).toContain('student-service-qa-detail-meta');
        expect(source).toContain('student-service-qa-answer-author-name');
        expect(source).toContain('student-service-qa-answer-author-role');
        expect(source).toContain('student-service-qa-answer-time');
        expect(source).toContain('student-service-qa-answer-actions');
        expect(source).toContain('student-service-qa-reply-shell');
        expect(source).toContain('student-service-qa-related-copy');
        expect(source).toContain('student-service-qa-detail-actions');
        expect(source).toContain('student-service-qa-detail-actions--moderation');
        expect(source).toContain('student-service-qa-answer-author-copy');
        expect(source).toContain('student-service-qa-empty-note');
        expect(source).toContain('student-service-qa-owner-note');
        expect(source).toContain('student-service-qa-detail-action-btn');
        expect(source).toContain('student-service-qa-detail-action-btn--feedback');
        expect(source).toContain('student-service-qa-detail-action-btn--moderation');
        expect(source).toContain('student-service-qa-answer-accept-btn');
        expect(source).toContain('student-service-qa-composer-open-btn');
        expect(source).toContain('student-service-qa-composer-collapse-btn');
        expect(source).toContain('student-service-qa-composer-minimize-btn');
        expect(source).toContain('student-service-qa-card-toggle-btn');
        expect(source).toContain('student-service-qa-empty-state');
        expect(source).toContain('student-service-qa-reply-input');
        expect(source).toContain('student-service-qa-reply-submit-btn');
        expect(source).toContain('function getStudentServiceStatusClass(');
        expect(source).toContain('function getStudentServiceQuestionStatusClass(');
        expect(source).toContain('role="group" aria-label="Workspace lanes"');
        expect(source).toContain('role="group" aria-label="Choose Student Service lane"');
        expect(source).toContain('function renderStudentServiceStudentQaHub(');
        expect(source).toContain('function renderStudentServiceQuestionComposer(');
        expect(source).toContain('function renderStudentServiceQuestionFeed(');
        expect(source).toContain('function renderStudentServiceStaffQaFeed(');
        expect(source).toContain('function renderStudentServiceResponderServiceLane(');
        expect(source).toContain('class="content-box surface-card student-service-detail-card"');
        expect(source).toContain('class="student-service-detail-toggle"');
        expect(source).toContain('class="student-service-detail-title"');
        expect(source).toContain('class="student-service-detail-icon"');
        expect(source).toContain('class="student-service-detail-body"');
        expect(source).toContain('class="student-service-loading-state"');
        expect(source).toContain('class="fas fa-spinner fa-spin student-service-loading-icon"');
        expect(source).toContain("return renderStudentServiceStaffWorkbench(container, visibleArticles, visibleTickets, { lane: 'qa' });");
        expect(source).toContain("return renderStudentServiceResponderServiceLane(container, visibleArticles);");
        expect(source).toContain("renderStudentServiceLaneChooser(role, currentUser, visibleArticles, visibleTickets)");
        expect(source).toContain('student-service-page-body:lane-chooser');
        expect(source).not.toContain('This workbench keeps private tickets, public Q&A, and knowledge articles in one moderated workspace.');
        expect(source).not.toContain('style="padding:0;"');
        expect(source).not.toContain('style="width:100%; display:flex; align-items:center; justify-content:space-between; gap:12px; padding:16px 18px; border:none; background:transparent; cursor:pointer; text-align:left;"');
        expect(source).not.toContain('style="font-size:13px; font-weight:800; color:var(--lux-text);"');
        expect(source).not.toContain('style="font-size:18px; color:var(--lux-text-muted);"');
        expect(source).not.toContain('style="padding:0 18px 18px;"');
        expect(source).not.toContain('style="text-align:center; padding:80px 20px; color:var(--lux-text-muted);"');
        expect(source).not.toContain('style="font-size:32px; margin-bottom:16px; display:block;"');
        expect(source).not.toContain('style="--student-service-status-bg:');
        expect(source).not.toContain('class="page-hero-badge admin-chip"');
        expect(source).toContain('class="admin-hero student-service-hero lux-hero-stage"');
        expect(source).not.toContain('class="page-hero-title admin-hero-title"');
        expect(source).not.toContain('class="page-hero-copy admin-hero-subtitle"');
        expect(source).not.toContain('class="admin-hero-actions student-service-hero-actions student-service-hero-action-cluster"');
        expect(css).toContain('.student-service-lane-switcher-shell');
        expect(css).toContain('.student-service-lane-switcher-btn');
        expect(css).toContain('.student-service-lane-choice-grid');
        expect(css).toContain('.student-service-lane-choice-card');
        expect(css).toContain('.student-service-lane-choice-stats');
        expect(css).toContain('.student-service-lane-choice-cta');
        expect(css).toContain('.student-service-hero-shell');
        expect(css).toContain('.student-service-hero-main-shell');
        expect(css).toContain('.student-service-hero-kicker');
        expect(css).toContain('.student-service-hero-title');
        expect(css).toContain('.student-service-hero-copy');
        expect(css).toContain('.student-service-hero-aside-shell');
        expect(css).toContain('.student-service-hero-meta');
        expect(css).toContain('.student-service-hero-badge');
        expect(css).toContain('.student-service-hero-badge--role');
        expect(css).toContain('.student-service-hero-badge--lane');
        expect(css).toContain('.student-service-hero-badge--knowledge');
        expect(css).toContain('.student-service-hero-action-cluster');
        expect(css).toContain('.student-service-hero-action--primary');
        expect(css).toContain('.student-service-hero-action--secondary');
        expect(css).toContain('.student-service-hero-aside-head');
        expect(css).toContain('.student-service-hero-aside-stat-label');
        expect(css).toContain('.student-service-hero-aside-stat-value');
        expect(css).toContain('.student-service-summary-section');
        expect(css).toContain('.student-service-summary-card--signal-a');
        expect(css).toContain('.student-service-summary-card--signal-b');
        expect(css).toContain('.student-service-summary-card--signal-c');
        expect(css).toContain('.student-service-workflow-section');
        expect(css).toContain('.student-service-workflow-step-title');
        expect(css).toContain('.student-service-workflow-step-description');
        expect(css).toContain('.student-service-qa-composer-prompt-title');
        expect(css).toContain('.student-service-qa-composer-prompt-copy');
        expect(css).toContain('.student-service-qa-compose-form');
        expect(css).toContain('.student-service-qa-mode-switch');
        expect(css).toContain('.student-service-qa-mode-btn');
        expect(css).toContain('.student-service-qa-field-row');
        expect(css).toContain('.student-service-qa-anonymous-toggle');
        expect(css).toContain('.student-service-qa-similar-title');
        expect(css).toContain('.student-service-qa-compose-actions');
        expect(css).toContain('.student-service-qa-card-author-name');
        expect(css).toContain('.student-service-qa-card-author-date');
        expect(css).toContain('.student-service-qa-card-stat');
        expect(css).toContain('.student-service-qa-detail-meta');
        expect(css).toContain('.student-service-qa-answer-author-name');
        expect(css).toContain('.student-service-qa-answer-author-role');
        expect(css).toContain('.student-service-qa-answer-time');
        expect(css).toContain('.student-service-qa-answer-actions');
        expect(css).toContain('.student-service-qa-reply-shell');
        expect(css).toContain('.student-service-qa-card-head');
        expect(css).toContain('.student-service-qa-card-author');
        expect(css).toContain('.student-service-qa-card-author-copy');
        expect(css).toContain('.student-service-qa-card.is-open');
        expect(css).toContain('.student-service-qa-card-main');
        expect(css).toContain('.student-service-qa-chip-row');
        expect(css).toContain('.student-service-qa-card-title');
        expect(css).toContain('.student-service-qa-card-preview');
        expect(css).toContain('.student-service-qa-card-accepted');
        expect(css).toContain('.student-service-qa-card-footer');
        expect(css).toContain('.student-service-qa-card-detail');
        expect(css).toContain('.student-service-qa-detail');
        expect(css).toContain('.student-service-qa-related-copy');
        expect(css).toContain('.student-service-qa-detail-actions');
        expect(css).toContain('.student-service-qa-detail-actions--moderation');
        expect(css).toContain('.student-service-qa-answer-list');
        expect(css).toContain('.student-service-qa-answer-head');
        expect(css).toContain('.student-service-qa-answer-author');
        expect(css).toContain('.student-service-qa-answer-author-copy');
        expect(css).toContain('.student-service-qa-answer-card.is-accepted');
        expect(css).toContain('.student-service-qa-answer-meta');
        expect(css).toContain('.student-service-qa-answer-copy');
        expect(css).toContain('.student-service-qa-empty-note');
        expect(css).toContain('.student-service-qa-owner-note');
        expect(css).toContain('.student-service-qa-detail-action-btn');
        expect(css).toContain('.student-service-qa-answer-accept-btn');
        expect(css).toContain('.student-service-qa-composer-open-btn');
        expect(css).toContain('.student-service-qa-composer-collapse-btn');
        expect(css).toContain('.student-service-qa-composer-minimize-btn');
        expect(css).toContain('.student-service-qa-card-toggle-btn');
        expect(css).toContain('.student-service-qa-empty-state');
        expect(css).toContain('.student-service-qa-reply-input');
        expect(css).toContain('.student-service-qa-reply-submit-btn');
        expect(css).toContain('.student-service-status.is-positive');
        expect(css).toContain('.student-service-status.is-warning');
        expect(css).toContain('.student-service-status.is-review');
        expect(css).toContain('.student-service-status.is-neutral');
        expect(css).toContain('.student-service-qa-composer-card');
        expect(css).toContain('.student-service-qa-feed');
        expect(css).toContain('.student-service-qa-card');
        expect(css).toContain('.student-service-qa-answer-card');
        expect(css).toContain('.student-service-detail-card');
        expect(css).toContain('.student-service-detail-toggle');
        expect(css).toContain('.student-service-detail-title');
        expect(css).toContain('.student-service-detail-icon');
        expect(css).toContain('.student-service-detail-body');
        expect(css).toContain('.student-service-loading-state');
        expect(css).toContain('.student-service-loading-icon');
        expect(css).not.toContain('.student-service-summary-card:nth-child(');
        expect(css).not.toContain('.page-hero-badge');
        expect(css).not.toContain('.page-hero-title');
        expect(css).not.toContain('.page-hero-copy');
        expect(css).not.toContain('.admin-hero-title');
        expect(css).not.toContain('.admin-hero-subtitle');
        expect(css).toContain('.student-service-qa-composer-collapsed');
        expect(css).toContain('.student-service-qa-filter-row');
        expect(mobileCss).not.toContain('.student-service-qa-composer-collapsed');
        expect(mobileCss).not.toContain('.student-service-qa-filter-row');
    });

    it('loads the split-workspace student-service bundle through a real standalone entry', () => {
        const studentServiceHtml = readAsset('student-service.html');
        const indexHtml = readAsset('index.html');
        const appJs = readAsset('assets/js/app/app.js');
        const studentsAdminHtml = readAsset('students-admin.html');

        expect(indexHtml).toContain('id="page-student-service"');
        expect(indexHtml).not.toContain('assets/js/pages/student-service.js?v=20260505-studentsvc-account-fades2');
        expect(appJs).toContain("const STUDENT_SERVICE_RUNTIME_SCRIPT = 'assets/js/pages/student-service.js?v=20260505-studentsvc-account-fades2';");
        expect(appJs).toContain('window.ensurePortalStudentServiceRuntimeLoaded = function ensurePortalStudentServiceRuntimeLoaded()');
        expect(studentServiceHtml).toContain('id="page-student-service"');
        expect(studentServiceHtml).toContain('assets/css/student-service-route.css?v=20260530-ssvcglass1');
        expect(studentServiceHtml).toContain('assets/js/features/navigation.js?v=20260429-shellinit1');
        expect(studentServiceHtml).toContain('assets/js/pages/student-service.js?v=20260505-studentsvc-account-fades2');
        expect(studentServiceHtml).toContain('bootStandaloneStudentServicePage');
        expect(studentServiceHtml).not.toContain("window.location.replace(target);");
        expect(studentServiceHtml).not.toContain('assets/js/pages/student-service-qa.js');
        expect(studentServiceHtml).not.toContain('assets/js/pages/student-service-service.js');
        expect(studentsAdminHtml).not.toContain('assets/js/pages/student-service.js');
        expect(studentsAdminHtml).toContain('assets/css/index-luxury.css');
        expect(studentsAdminHtml).toContain('assets/css/students-admin-lms.css');
        expect(studentsAdminHtml).toContain('assets/css/mobile-responsive.css');
    });

    it('keeps the student-service standalone page free of the old standalone mobile shell bootstrap', () => {
        const studentServiceHtml = readAsset('student-service.html');

        expect(studentServiceHtml).not.toContain('window.__KIU_STANDALONE_MOBILE_SHELL_CONFIG = {');
        expect(studentServiceHtml).not.toContain('assets/js/pages/standalone-mobile-shell.js?v=20260518-standalone-shell1');
        expect(studentServiceHtml).not.toContain('(function initMobileExperience(){');
        expect(studentServiceHtml).not.toContain('setInterval(function(){if(typeof window.navigate===');
    });

    it('keeps repeated student-service cards on route-scoped content-visibility guardrails', () => {
        const css = readAsset('assets/css/student-service-route.css');

        expect(css).toContain('body.lux-route-student-service .student-service-ticket-card,');
        expect(css).toContain('body.lux-route-student-service .student-service-ops-ticket,');
        expect(css).toContain('body.lux-route-student-service .student-service-qa-card,');
        expect(css).toContain('body.lux-route-student-service .student-service-qa-answer-card {');
        expect(css).toContain('content-visibility: auto;');
        expect(css).toContain('contain-intrinsic-size: 0 280px;');
    });

    it('adds efficient-tier blur and shadow fallbacks for repeated student-service surfaces', () => {
        const css = readAsset('assets/css/student-service-route.css');

        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-student-service .student-service-summary-card,");
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-student-service .student-service-article-card,");
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-student-service .student-service-qa-card,");
        expect(css).toContain("body[data-lux-performance='efficient'].lux-route-student-service .student-service-qa-answer-card {");
        expect(css).toContain("body[data-lux-performance='efficient'].lux-light-mode.lux-route-student-service .student-service-summary-card,");
        expect(css).toContain("body[data-lux-performance='efficient'].lux-light-mode.lux-route-student-service .student-service-article-card,");
        expect(css).toContain('-webkit-backdrop-filter: blur(10px) saturate(118%) !important;');
        expect(css).toContain('backdrop-filter: blur(8px) saturate(112%) !important;');
    });

    it('delegates the Q&A, ops, and service-workbench actions instead of emitting inline hooks', () => {
        const source = readAsset('assets/js/pages/student-service.js');
        const qaModule = readAsset('assets/js/pages/student-service-qa.js');
        const serviceModule = readAsset('assets/js/pages/student-service-service.js');
        const combined = `${source}\n${qaModule}\n${serviceModule}`;

        expect(source).toContain('function bindStudentServiceDelegatedInteractions()');
        expect(source).toContain("const STUDENT_SERVICE_QA_MODULE_URL = 'assets/js/pages/student-service-qa.js?v=20260516-studentsvcqa-module1';");
        expect(source).toContain("const STUDENT_SERVICE_SERVICE_MODULE_URL = 'assets/js/pages/student-service-service.js?v=20260516-studentsvcservice-module1';");
        expect(source).toContain('function ensureStudentServiceQaModule()');
        expect(source).toContain('function ensureStudentServiceServiceModule()');
        expect(source).toContain('renderStudentServiceQaModuleLoading(container,');
        expect(source).toContain('renderStudentServiceServiceModuleLoading(container,');
        expect(combined).toContain('data-student-service-open-panel="tickets"');
        expect(combined).toContain('data-student-service-open-ticket=');
        expect(combined).toContain('data-student-service-focus-area=');
        expect(combined).toContain('data-student-service-question-filter-field="qaStatus"');
        expect(combined).toContain('data-student-service-question-filter-input="qaSearch"');
        expect(combined).toContain('data-student-service-open-question=');
        expect(combined).toContain('data-student-service-panel-switch=');
        expect(combined).toContain('data-student-service-ticket-filter-input=');
        expect(combined).toContain('data-student-service-save-article=');
        expect(combined).not.toContain('onclick=');
        expect(combined).not.toContain('oninput=');
        expect(combined).not.toContain('onchange=');
        expect(source).toContain('student-service-ops-card lux-summary-surface lux-summary-surface--panel');
        expect(source).toContain('student-service-ops-card student-service-ops-card--queue lux-summary-surface lux-summary-surface--panel');
    });
});
