import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

function readSource(relativePath) {
    return readFileSync(join(process.cwd(), relativePath), 'utf8');
}

describe('timetable route regressions', () => {
    it('keeps the timetable html free of inline control handlers and dead studio fallback markup', () => {
        const html = readSource('timetable.html');
        const timetableRuntime = readSource('assets/js/pages/timetable-runtime.js');
        const navigationSource = readSource('assets/js/features/navigation.js');
        const layoutCss = readSource('assets/css/layout.css');
        const routeCss = readSource('assets/css/timetable-route.css');
        const themePrimer = readSource('assets/js/theme-primer.js');
        const utilities = readSource('assets/js/shared/utilities.js');
        const luxuryCss = readSource('assets/css/index-luxury.css');
        const timetableStructuralBranch = utilities.slice(
            utilities.indexOf("document.body.classList.contains('lux-route-timetable')"),
            utilities.indexOf("document.body.classList.contains('lux-route-profile')")
        );
        const inlineHandlerMatches = html.match(/on(click|input|change|mouseover|mouseout|mouseenter|mouseleave)=/g) || [];

        expect(inlineHandlerMatches).toHaveLength(0);
        expect(html).not.toContain('id="modal-studio"');
        expect(html).not.toContain('<style>');
        expect(html).toContain('assets/css/timetable-route.css');
        expect(html).toContain('assets/js/theme-primer.js?v=20260604-styleguard2');
        expect(html).toContain('assets/css/timetable-route.css?v=20260606-ttcompact1');
        expect(html).toContain('assets/css/index-luxury.css?v=20260531-partbg4');
        expect(html).toContain('assets/js/shared/utilities.js?v=20260605-blurfix1');
        expect(html).toContain('assets/js/pages/timetable-runtime.js?v=20260606-ttcompact1');
        expect(html).toContain('assets/js/features/navigation.js?v=20260605-ttboot1');
        expect(html).not.toContain('assets/js/pages/planner.js');
        expect(html).toContain('<nav id="prof-nav" aria-label="Professor navigation stub"');
        expect(html).toContain('<nav id="top-nav" aria-label="Top navigation stub"');
        expect(html).toContain('<nav id="admin-nav" aria-label="Admin navigation stub"');
        expect(html).toContain('data-timetable-filter="semester"');
        expect(html).toContain('data-timetable-filter="faculty"');
        expect(html).toContain('data-timetable-week-shift="-1"');
        expect(html).toContain('data-timetable-week-shift="1"');
        expect(html).toContain('data-schedule-current-week="1"');
        expect(html).toContain('data-schedule-view="sessions"');
        expect(html).toContain('data-schedule-view="timetable"');
        expect(html).toContain('function ensureTimetableRouteReady()');
        expect(html).toContain('window.__timetableStaticControlsBound');
        expect(html).toContain('class="lux-timetable-view-switcher lux-card"');
        expect(html).toContain('class="schedule-week-nav lux-timetable-week-nav lux-card"');
        expect(html).not.toContain('lux-timetable-next-compact');
        expect(html).not.toContain('id="timetable-insight-next"');
        expect(html).toContain('class="lux-timetable-hero-focus lux-hero-side"');
        expect(html).toContain('Your next class');
        expect(html).toContain('lux-timetable-focus-subline');
        expect(html).toContain('id="timetable-hero-focus-time"');
        expect(html).toContain('id="timetable-hero-focus-facts"');
        expect(html).toContain('class="lux-timetable-focus-head"');
        expect(html).toContain('class="lux-hero lux-timetable-hero lux-summary-surface--hero"');
        expect(html).toContain('class="lux-card lux-timetable-command"');
        expect(html).toContain('class="lux-card lux-timetable-stage"');
        expect(html).not.toContain('â€”');
        expect(html).not.toContain('id="timetable-insight-next-time"');
        expect(html).toContain('Management &amp; Business');
        expect(html).toContain('Arts &amp; Humanities');
        expect(html).toContain('class="fas fa-circle timetable-stage-status-dot"');
        expect(html).toContain('<button class="mob-sheet-btn" type="button" id="mob-act-admin"><span class="mob-sheet-icon"');
        expect(html).not.toContain('<button class="mob-sheet-btn" id="mob-act-admin"><div class="mob-sheet-icon"');
        expect(html).toContain('function bindTimetableStaticControls()');
        expect(html).not.toContain('session-modal');
        expect(html).not.toContain('schedule-drawer');
        expect(timetableRuntime).toContain('function ensureScheduleSurfaceRegions(container) {');
        expect(timetableRuntime).toContain("const { frame } = showScheduleSurfaceFrame(container);");
        expect(timetableRuntime).toContain("container.dataset.scheduleSurfaceView = view;");
        expect(timetableRuntime).toContain('function getScheduleToneToken(facultyCode) {');
        expect(timetableRuntime).toContain('function buildScheduleToneDataAttribute(facultyCode) {');
        expect(timetableRuntime).toContain('function renderTimetable() {');
        expect(timetableRuntime).toContain('[data-schedule-current-week], [data-timetable-action="current-week"]');
        expect(timetableRuntime).toContain('currentWeekButton.dataset.scheduleCurrentWeek = \'1\'');
        expect(navigationSource).toContain("activePageId === 'timetable' && typeof window.renderTimetable === 'function'");
        expect(navigationSource).toContain('window.__kiuStandaloneRouteContentBootKey = bootKey');
        expect(navigationSource).toContain('refreshStandaloneDesktopRouteContent(pageId, { reason: \'standalone-default-content\' })');
        expect(timetableRuntime).toContain('emptyMessage: `No timetable sessions found for ${formatWeekRangeLabel(weekStart)}.`');
        expect(timetableRuntime).not.toContain('schedule-session-modal');
        expect(timetableRuntime).toContain("shell.className = `schedule-grid-shell lux-timetable-grid-shell lux-card");
        expect(timetableRuntime).toContain("shell.dataset.ttGrid = '1'");
        expect(timetableRuntime).toContain('queueLuxuryTransparencyRefresh');
        expect(timetableRuntime).toContain("toggle.className = 'schedule-view-switcher lux-timetable-view-switcher surface-card lux-panel lux-card lux-builder-card lux-summary-surface lux-summary-surface--panel';");
        expect(timetableRuntime).toContain("weekNav.className = 'schedule-week-nav lux-timetable-week-nav surface-card lux-panel lux-card lux-builder-card lux-summary-surface lux-summary-surface--panel';");
        expect(timetableRuntime).toContain("overviewRow.className = 'schedule-overview-row lux-timetable-overview-row surface-card lux-panel lux-card lux-builder-card lux-summary-surface lux-summary-surface--panel';");
        expect(timetableRuntime).toContain('class="schedule-chip lux-status-pill lux-timetable-chip"');
        expect(timetableRuntime).toContain("shell.style.setProperty('--sch-shell-min-height',");
        expect(timetableRuntime).toContain("body.style.setProperty('--sch-body-min-height',");
        expect(timetableRuntime).toContain("section.className = 'schedule-day-section lux-timetable-day-section surface-card lux-panel lux-card lux-builder-card lux-summary-surface lux-summary-surface--panel';");
        expect(timetableRuntime).toContain('class="sch-time-slot lux-timetable-time-slot" style="--sch-slot-height:');
        expect(timetableRuntime).toContain('class="sch-slot-bg lux-timetable-slot-bg" style="--sch-slot-height:');
        expect(timetableRuntime).toContain('class="schedule-now-line" style="--sch-now-top:');
        expect(timetableRuntime).toContain('class="schedule-session-grid lux-timetable-session-grid${dayItems.length >= 4 ? \' lux-timetable-session-grid--dense\' : \'\'}"');
        expect(timetableRuntime).toContain('class="schedule-session-card lux-timetable-session-card lux-strip-card surface-card lux-panel lux-card lux-builder-card lux-summary-surface lux-summary-surface--panel${markerClass}"');
        expect(timetableRuntime).toContain('class="schedule-session-code-row lux-timetable-session-code-row"');
        expect(timetableRuntime).toContain('class="schedule-session-code lux-timetable-session-code"');
        expect(timetableRuntime).toContain('class="schedule-session-pill lux-timetable-session-pill type"');
        expect(timetableRuntime).toContain('class="schedule-session-title lux-timetable-session-title"');
        expect(timetableRuntime).toContain('class="schedule-session-subtitle lux-timetable-session-subtitle"');
        expect(timetableRuntime).toContain('formatTimetableHeroFocusTitle(item)');
        expect(timetableRuntime).toContain('lux-timetable-session-grid--dense');
        expect(routeCss).toContain('.lux-timetable-session-grid');
        expect(routeCss).toContain('minmax(220px, 1fr)');
        expect(routeCss).toContain('.lux-timetable-session-grid--dense');
        expect(routeCss).toContain('.lux-timetable-session-card');
        expect(routeCss).toContain('padding: 12px 14px !important');
        expect(timetableRuntime).toContain('class="schedule-session-meta-row lux-timetable-session-meta-row"');
        expect(timetableRuntime).toContain('class="lux-secondary-btn schedule-session-action lux-timetable-session-action"');
        expect(timetableRuntime).toContain('class="sch-time-col lux-timetable-time-col"');
        expect(timetableRuntime).toContain('class="sch-day-col lux-timetable-day-col ${isToday ? \'today\' : \'\'}"');
        expect(timetableRuntime).toContain('dayLanes.className = \'sch-day-lanes lux-timetable-day-lanes\';');
        expect(timetableRuntime).toContain('class="sch-lane lux-timetable-lane"');
        expect(timetableRuntime).toContain("board.className = 'schedule-sessions-board lux-timetable-sessions-board';");
        expect(timetableRuntime).toContain('class="ev-draft sch-week-badge lux-timetable-week-badge" ${toneAttr}>WEEK</div>');
        expect(timetableRuntime).toContain('class="sch-event lux-timetable-event${markerClass}" ${toneAttr} style="--sch-event-top:');
        expect(timetableRuntime).toContain('class="sch-event-topline lux-timetable-event-topline"');
        expect(timetableRuntime).toContain('class="sch-event-code lux-timetable-event-code"');
        expect(timetableRuntime).toContain('class="sch-event-pill lux-timetable-event-pill"');
        expect(timetableRuntime).toContain('class="ev-title lux-timetable-event-title"');
        expect(timetableRuntime).toContain('class="ev-meta lux-timetable-event-meta"');
        expect(timetableRuntime).toContain("showScheduleSurfaceEmpty(container, emptyMessage, 'schedule-grid-empty lux-timetable-grid-empty');");
        expect(timetableRuntime).not.toContain('kiu-btn-blue');
        expect(timetableRuntime).not.toContain('kiu-btn-outline');
        expect(timetableRuntime).not.toContain('style="height:${slotHeight}px; cursor:default;"');
        expect(timetableRuntime).not.toContain('style="top:${nowTopPx}px;"');
        expect(timetableRuntime).not.toContain('style="background:${color};"');
        expect(timetableRuntime).not.toContain('style="--sch-week-badge-bg:');
        expect(timetableRuntime).not.toContain('--sch-event-line:${color}');
        expect(routeCss).toContain('.lux-timetable-grid-shell {');
        expect(routeCss).toContain('.lux-timetable-time-slot,');
        expect(routeCss).toContain('.lux-timetable-week-badge {');
        expect(routeCss).toContain('.lux-timetable-event {');
        expect(routeCss).toContain('.lux-timetable-grid-empty {');
        expect(routeCss).toContain('.lux-timetable-view-switcher {');
        expect(routeCss).toContain('.lux-timetable-week-nav {');
        expect(routeCss).toContain('.lux-timetable-overview-row {');
        expect(routeCss).toContain('.lux-timetable-chip {');
        expect(routeCss).toContain('.lux-timetable-sessions-board {');
        expect(routeCss).toContain('.lux-timetable-day-section {');
        expect(routeCss).toContain('.lux-timetable-session-card {');
        expect(routeCss).toContain('.lux-timetable-session-code-row {');
        expect(routeCss).toContain('.lux-timetable-session-action {');
        expect(routeCss).toContain('.lux-timetable-time-col,');
        expect(routeCss).toContain('.lux-timetable-day-lanes {');
        expect(routeCss).toContain('.lux-timetable-lane {');
        expect(routeCss).toContain('[data-sch-tone="current"]');
        expect(routeCss).toContain('.lux-timetable-event:hover {');
        expect(routeCss).toContain('background: var(--sch-tone-accent, var(--lux-accent));');
        expect(routeCss).toContain('border-left-color: var(--sch-tone-accent, var(--lux-accent));');
        expect(routeCss).toContain('--tt-fade-surface');
        expect(routeCss).toContain('--tt-fade-chip');
        expect(routeCss).toContain('--tt-fade-row');
        expect(routeCss).toContain('--tt-grid-header-bg');
        expect(routeCss).toContain('--tt-grid-time-rail-bg');
        expect(routeCss).toContain('--tt-grid-cell-bg');
        expect(routeCss).toContain('.lux-timetable-grid-shell .sch-time-slot span');
        expect(layoutCss).toContain('body:not(.lux-route-timetable) .sch-time-col');
        expect(luxuryCss).toContain('body.lux-route-admin-scheduler:not(.lux-light-mode) .sch-header-row');
        expect(routeCss).toContain('--tt-fade-blur');
        expect(routeCss).toContain('background: var(--tt-fade-surface) !important');
        expect(routeCss).toContain('Home-style command center restyle');
        expect(routeCss).toContain('.lux-timetable-focus-head');
        expect(routeCss).toContain('.lux-timetable-focus-time');
        expect(routeCss).toContain('.lux-timetable-focus-facts');
        expect(routeCss).toContain('.lux-timetable-focus-meta');
        expect(routeCss).not.toMatch(/\.lux-timetable-focus-meta span,\s*\nbody\.lux-route-timetable \.schedule-chip/);
        expect(timetableRuntime).toContain('function formatTimetableHeroFocusTitle(session)');
        expect(timetableRuntime).toContain('function renderTimetableHeroFocusPanel(');
        expect(timetableRuntime).toContain('function renderTimetableHeroFocusFacts(session');
        expect(timetableRuntime).not.toContain('timetable-insight-next');
        expect(timetableRuntime).not.toContain('renderTimetableNextCompactFacts');
        expect(routeCss).not.toContain('lux-timetable-next-compact');
        expect(routeCss).toContain('grid-template-areas:');
        expect(routeCss).toMatch(/grid-template-areas:[\s\S]*"view"[\s\S]*"chips"[\s\S]*"week"/);
        expect(routeCss).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))');
        expect(routeCss).toContain('.lux-timetable-overview-row');
        expect(routeCss).toContain('html.lux-high-transparency body.lux-route-timetable');
        expect(luxuryCss).not.toContain('clean academic');
        expect(luxuryCss).not.toContain('compat-repair');
        expect(luxuryCss).not.toContain('body.lux-route-timetable .lux-timetable-command {');
        expect(luxuryCss).not.toContain('html.lux-transparency-pending .lux-timetable-command');
        expect(timetableStructuralBranch).toContain("el.classList.contains('lux-timetable-hero')");
        expect(timetableStructuralBranch).toContain("el.classList.contains('lux-timetable-command')");
        expect(timetableStructuralBranch).toContain("el.classList.contains('lux-timetable-session-card')");
        expect(utilities).toContain('const isTimetableGridCell = (el) => {');
        expect(utilities).toContain('TIMETABLE_GRID_CELL_CLASS_NAMES');
        expect(utilities).toContain('isTimetableGridCell(el) ||');
        expect(utilities).toContain('.lux-timetable-grid-shell, .schedule-grid-shell[data-tt-grid="1"]');
        expect(utilities).not.toContain('const isTimetableLargeSurface');
        expect(utilities).not.toContain('if (isTimetableLargeSurface)');
        expect(utilities).not.toContain("'.lux-timetable-command', '.lux-timetable-insight'");
        expect(utilities).toContain('const isTimetableLayoutWrapper = (el) => document.body.classList.contains(\'lux-route-timetable\')');
        expect(utilities).toContain("el.classList.contains('lux-timetable-controls')");
        expect(utilities).toContain("el.classList.contains('schedule-toolbar-host')");
        expect(themePrimer).toContain("document.body.classList.contains('lux-route-timetable')");
        expect(themePrimer).toContain('applyFlatSurfaceOverrides');
        expect(html).not.toContain('function flattenTimetableControlRows()');
        expect(html).not.toContain('setTimeout(flattenTimetableControlRows, 700);');
    });

    it('keeps timetable on the shared standalone mobile shell contract instead of navigate polling', () => {
        const html = readSource('timetable.html');

        expect(html).toContain('window.__KIU_STANDALONE_MOBILE_SHELL_CONFIG = {');
        expect(html).toContain("activeTarget: 'timetable'");
        expect(html).toContain('assets/js/pages/standalone-mobile-shell.js?v=20260520-timetable-mobile1');
        expect(html).not.toContain('(function initMobileExperience(){');
        expect(html).not.toContain("var ht=setInterval(function(){if(typeof window.navigate==='function')");
    });
});
